### ISSUE TITLE
incorrect reference to arithmetic

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1006]
```
accepts =
  sieve apps using resp, us:
    resp == some('CONFIRMED') and us == some('Yes')
  end
```
(note lack of parens)
produces the error
"Reading this arithmetic expression errored:"

There's no arithmetic anywhere here.

**Comment by blerner** [comment]
Related to #999

**Comment by blerner** [comment]
What wording would you like?  "infix" is jargon, and you can't reliably say "logic" instead of "arithmetic" because in general these operators are mixed and ill-formed anyway...  You have available to you the names of _both_ operators involved in this expression (which in this case are `and` and the rightmost `==`) -- remember, it's a binop expression no matter how many operators you threw in there without parens...

**Comment by schanzer** [comment]
What _do_ we call "the stuff inside the body of the table operation"? Do we have a name for the expression used in a sieve, or in a transform?

(e.g. - I'm tempted to say something along the lines of "reading the sieve expression errored")

**Comment by blerner** [comment]
Be very careful here: the sieve part of the expression did not itself error.  This is a well-formedness error because of mixed infix operators, not because of a syntax error.

**Comment by shriram** [comment]
@blerner I don't see @schanzer's comment as being confused about this, though the warning is always wise.

Concretely, why not just remove the word "arithmetic" and say just "expression"? That would cover all cases of binops that need to be parenthesized.

**Comment by schanzer** [comment]
I like Shriram's suggestion. At the same time, I'm still curious about what we call expressions in this position.
