### ISSUE TITLE
Idea: `provide` shorthand

### ISSUE THREAD

**Issue by belph** [brownplt/pyret-lang#1015]
Right now, if we want a module to provide a certain series of names, we need to do the following:
```
provide {
  foo: foo,
  bar: bar,
  baz: baz,
  # ...
} end
```
It would be great if the following could be equivalent, now that we have tuples:
```
provide {
  foo;
  bar;
  baz;
  # ...
} end
```
Thoughts?

**Comment by jpolitz** [comment]
Yup.  I think the curly-braces are silly, too.

There's some existing discussion of this at https://github.com/brownplt/pyret-lang/wiki/TM005---More-structured-module-system,-to-facilitate-data,-renaming,-bringing-identifiers-into-local-scope

The "back-end" infrastructure for this has been done for some time.

Designing a user-facing syntax for it has languished.

**Comment by blerner** [comment]
The braces were only needed because we were trying to use object literals
there directly. Now that we're trying to provide more structured
infirmation, that no longer makes sense. Neither does using tuple syntax,
though: you'd now have some wonky well formedness rule to specify "provide
can only take a tuple of identifiers..." Anyway, that wiki page has some
better/more generally applicable ideas, so we ought to get back to that.

**Comment by blerner** [comment]
Closing; we've got a new module import system nearly ready now.
