### ISSUE TITLE
Odd location reported for an error

### ISSUE THREAD

**Issue by kfisler** [brownplt/pyret-lang#1070]
(I'd expect this goes to Jack Wrenn, but I don't see him under the possible assignees)

This is from one of my students today.  The actual error in her code is in the if-line just below the function doc (calling hm-time with a time, when it should be the time constructor).  But the error report shows up on the first example in the where clause.  I attached the screen shot of the error, but rerunning the code should suffice to reproduce.

```
data Time:
  | hm-time( hours, minutes)
end

fun is-earlier(time1 :: Time, time2 :: Time) -> Boolean:
  doc: "determine whether first time is earlier than second time" 
  if hm-time(time1) > hm-time(time2):
    true
  else: 
    false
  end 
where:
  is-earlier(hm-time(01, 30), hm-time(02, 30)) is true
  is-earlier(hm-time(03, 25), hm-time(01, 45)) is false
  is-earlier(hm-time(01, 45), hm-time(01, 30)) is false
  is-earlier(hm-time(02, 20), hm-time(02, 30)) is true
end 
```

![screenshot 2017-07-13 15 26 55](https://user-images.githubusercontent.com/1503177/28184084-f002c9f4-67df-11e7-841c-b60ae6d7cb21.png)

**Comment by blerner** [comment]
This looks like the Erratic Stack Location Heuristic at work again...

**Comment by jpolitz** [comment]
This is almost entirely fixed now.  the `2 arguments` bit still doesn't highlight, which is unfortunate.

However, updates to looking up locations on the stack now produce this:

![image](https://user-images.githubusercontent.com/119891/28230194-d0d261be-689a-11e7-8eca-80cb4ca6489a.png)

**Comment by blerner** [comment]
The reason the `2 arguments` don't highlight is a bit amusing, and a bit complicated.  As it turns out, `hm-time( hours, minutes)` parses as a function application expression; in general, for this particular `constructor-arity-mismatch` error, it's expected to parse as a variant constructor.  Both of these have problems:

* When trying to deduce the arguments passed to the function application (or constructor application), we try to reparse the function *definition* location to extract its formal parameters.  If the function *definition* location in fact looks like a function *application* location, as can happen in `let add3 = (_ + 3) in add3("too many", "args")` or `let fumble = foobar(3, _, 5) in fumble("too many", "args")`, there is a check in the error's renderer that filters the arguments to find the underscores, because *those* are the actual arguments to this curried function.  That check got copied/pasted into the code for the `constructor-arity-mismatch`, though, and in that setting there are no underscores, so the test is exactly wrong here.  Turning it off allows `hours` and `minutes` to be highlighted purple in the image above.  This is a minor change (error.arr, line 1309, remove the call to `.filter(is-underscore)`) and should be done.

* But... Unfortunately, variant definitions aren't valid top-level things, unlike function definitions.  If the definition of `hm-time` were changed to have a type annotation anywhere in it, e.g. `hm-time(hours :: Number, minutes)`, then it would not parse successfully, and you'd get an error message where `2 arguments` was *not* highlighted purple, and neither would be `hours :: Number` and `minutes`.  This is unfortunate, since if `hm-time` were defined as a function, i.e. `fun hm-time(hours :: Number, minutes): ... end`, then it *would* parse successfully and the parameters *would* therefore be highlighted.  This is an annoying inconsistency that is *not* the fault of the error-rendering code, but rather of the limitations of trying to reparse a fragment of a program in isolation.

Rampant speculation follows.

I have a **very** rough idea of how to address this at the parser level, but it will cause the parser to become ambiguous (in a limited, hopefully-controllable fashion), and this ambiguity increases the parser size very slightly (<1%), and increases parsing times slightly (1-5%, I think).  The ambiguity comes from the unannotated cases: a `variant-constructor` can look like a simple bare identifier, or like a function call using only names.  I.e. if the entire program is `some-name`, or `hm-time(hours, minutes)`, those can be parsed in two separate ways, and currently only one way (namely, as an identifier or as a function-application, respectively) is valid as a whole-program parse.  If I add the ability to recognize variant-constructors as whole program parses, I need to re-engineer the pyret-parser library and its callers to reject such parses everywhere *except* in the error message renderers...  (This isn't completely trivial: the naive approach would say "Oh, if there are two parses, take the one that isn't the variant-constructor", but the annoying case is the inverse, where there used to be zero successful parses and now there's one.  And, I need to be utterly sure that this grammar change can only increase the number of parses by at most one in these error cases and nowhere else.  I'm pretty sure of that, but I want to double check.)

This change will also change parse errors slightly.  In particular, if a student writes `hm-time(hours :: Number, minutes)` as their _entire_ program right now, they'll get a "Pyret didn't understand your program around `::`" error.  With this change, Pyret would parse the above as a variant-constructor, but then we could perhaps say something like "This is not a valid complete program."


Finally, to head off Shriram's likely comment: yes, you could solve this entirely if you rewrote the entire parser as a handwritten recursive-descent thingummy.  I still think that cure is worse than the disease.

**Comment by jswrenn** [comment]
As of 2c13b0984213e404fa30fddec2398d596a58ea8e, the definition site is highlighted, too:
![screenshot-localhost-5000 2017-08-01 13-34-36](https://user-images.githubusercontent.com/3820879/28838441-53b9f14c-76be-11e7-8c6f-591d7eb0ce60.png)

**Comment by kfisler** [comment]
This looks much better -- thanks!
