### ISSUE TITLE
really misleading parse error message

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1074]
![image](https://user-images.githubusercontent.com/75030/28282015-2e0487fc-6ae6-11e7-9fbb-ff17671a25e3.png)

It seems intuitive that the fix is to remove that extra space, but of course that has nothing at all to do with the problem. Indeed, the error still seems to be at the same locus:

![image](https://user-images.githubusercontent.com/75030/28282083-722c6fd0-6ae6-11e7-9458-531f654538f2.png)

**Comment by blerner** [comment]
This is bad, and it's not easily fixable.  The parser *has* to make distinctions about spaces-before-parens, or else parsing becomes ambiguous -- `foo (1 + 2)` is now two-expressions-on-a-line and also a spacey-fun-app.  "Fixing" this by detecting such problems is tantamount to solving the ambiguous-parsing problem, which just isn't doable.  This can't be fixed by a well-formedness check (that happens after parsing succeeds), and it can't be fixed by a "bad-fun-app" expression rule that allows for spaces in the application (that would make the parser super expensive on all *normal, perfectly fine* applications).  I don't know what to recommend, here.

**Comment by schanzer** [comment]
Cheap recommendation until something better comes along: `Is there a missing colon (:), comma (,), string marker ("), keyword, or an extra space where there shouldn't be?`

**Comment by jpolitz** [comment]
For single-argument functions, this isn't that bad, because we can check if
the second expression is an s-paren.  I just tried adding this and it works
pretty well:

+++ b/src/arr/compiler/well-formed.arr
@@ -234,10 +234,20 @@ fun ensure-distinct-lines(loc :: Loc,
prev-is-template :: Boolean, stmts :: List
             | builtin(_) => ensure-distinct-lines(loc, prev-is-template,
rest) # No need to preserve builtin() locs
             | srcloc(_, start-line2, _, _, _, _, _) =>
               when (end-line1 == start-line2):
                 if A.is-s-template(first) and prev-is-template:
                   add-error(C.template-same-line(loc, first.l))
                 else if not(A.is-s-template(first)) and
not(prev-is-template):
-                  add-error(C.same-line(loc, first.l))
+                  if A.is-s-paren(first):
+                    add-error(C.wf-err-split("There are two expressions on
the same line, and the second starts with a parenthesis.  When using a
function, there cannot be a space after the function.", [list: first.l,
loc]))
+                  else:
+                    add-error(C.same-line(loc, first.l))
+                  end

Annoyingly, it doesn't work at the top level because

f (5)

is turned into

trace-value(f) trace-value((5))

at the top level.

Ben – do you know why wrap-toplevels happens before well-formed?


For multi-argument functions it's more difficult, I think, because it's
actually a parse error when there are commas within the thing in
parentheses.  That might be able to get a special parser rule somehow –
maybe parens around comma-separated expressions can be a specially-parsed
ill-formed expression?  I don't fully understand what the consequences of
that would be.




On Mon, Jul 17, 2017 at 8:16 PM, Emmanuel Schanzer <notifications@github.com

**Comment by blerner** [comment]
I have no idea.  Are there any other Pyret expressions that can begin with a left paren?  Or is it just s-paren?  I'm a bit skittish about saying "Oh, well, we can add a special parsing rule `spacey-app := expr LPARENSPACE arg COMMA args RPAREN`, because the way this could be ambiguous is in the one-argument function case, and we'll just happily parse that as an s-paren and complain later in well-formedness."  That's a *very* brittle argument to make...

**Comment by schanzer** [comment]
Given how frequently these errors are cropping up, can we implement my "cheap solution" for now?

**Comment by schanzer** [comment]
"Cheap solution" is implemented, and I don't see other issues cropping up that would suggest it's insufficient. OK to close?

**Comment by blerner** [comment]
@jpolitz I think you're probably right, we could reorder wrap-toplevel with check-well-formed; I probably wrote it this way because I wanted to ensure the wrapping was also well-formed, but I'm fairly confident in that.

**Comment by schanzer** [comment]
@blerner the cheap solution works well-enough-ish for Bootstrap's purposes, and the root issue here is a parsing limitation that shows up in a number of other issues. That makes this all but redundant. OK to close?

**Comment by schanzer** [comment]
@blerner ?

**Comment by blerner** [comment]
I think this is the same issue as #1113 and is being handled by the same slightly-hacky solution there.
