### ISSUE TITLE
pie chart needs to show more info

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1079]
We have teachers plotting GDPs of _all_ countries in the world. Needless to say, there are lots of tiny slivers. Resizing the draw window doesn't cause the pie-chart to increase size, which is a bit surprising to them but understandable. The bigger problem is that mousing over the wedges shows some of the data but not all: in particular, it doesn't show the name of the country, which is only presented on the outside of the pie chart. But all these names overwrite one another, so not putting that info in the mouse-over hides vital information.

Put differently, I'd suggest having a test case that has 100s of elements. That would reveal some of the usability problems.

**Comment by blerner** [comment]
For the first problem, we do have a stretchable pie chart, right? We made it for the physics folks doing energy simulations?

**Comment by shriram** [comment]
Not sure. If we do, why have both kinds?

**Comment by blerner** [comment]
Because the physics folks wanted the "click and drag to expand the window" to map semantically onto "pump energy into the system".  And they wanted a non-resizable one for systems that you couldn't pump energy into.

**Comment by sorawee** [comment]
> Resizing the draw window doesn't cause the pie-chart to increase size, which is a bit surprising to them but understandable.

Resizing does increase the size (you need to click the resize button). Compare 
![screenshot from 2017-07-19 00-25-32](https://user-images.githubusercontent.com/9099577/28350708-e0264578-6c18-11e7-841a-0f86321cef41.png)

with

![screenshot from 2017-07-19 00-25-53](https://user-images.githubusercontent.com/9099577/28350710-e35475ee-6c18-11e7-9233-805df67a2839.png)

The effect is not much noticeable, however. The reason is that by design, the smallest pie chart window takes a lot of vertical space already, and the chart size depends on the vertical space, so resizing it up can't make the chart size much bigger.

The adjustable pie chart that @blerner mentions could make some pie smaller, not bigger, so I don't think it's the solution.

> The bigger problem is that mousing over the wedges shows some of the data but not all: in particular, it doesn't show the name of the country

To be fixed.

> I'd suggest having a test case that has 100s of elements

You mean 100 pies? I don't think that's a good use of pie chart...

**Comment by shriram** [comment]
I think the redraw is totally non-obvious​: nobody here realized there was
such an option. How about making it a button, say "Redraw", so people
realize that this is something it does? People are used to systems that are
more naturally reactive, so when it doesn't automatically resize, the
assumption is that it … doesn't.

**Comment by shriram** [comment]
Also, @sorawee, this comment is not useful:

> You mean 100 pies? I don't think that's a good use of pie chart...

A participant pulls in a countries dataset and looks at GDP. It's entirely legitimate to do so (e.g., to see the relative impact of large economies like China or the USA). The fact that there's 200 countries doesn't affect this legitimacy.

**Comment by blerner** [comment]
@shriram's  comment brings to mind another interesting DS assignment question: "Show a pie chart of some-dataset, but summarize all items less than some-threshold as 'other'."  I don't see that as working well with our current set of table-queries...  I raise this assignment as potentially motivating additional features (perhaps) to the pie-chart API, as well as to the tables API...

**Comment by shriram** [comment]
Good example for @jpolitz to consider in his experiments w/ methods.

**Comment by schanzer** [comment]
Google charts is now implemented on CPO. @sorawee , OK to close?
