### ISSUE TITLE
non-boolean in `sieve` causes _internal error_

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1094]
```
presidents =
  table: name, state
    row: "Joe", "CA"
    row: "Ben", "MA"
  end

sieve presidents using state: state == "CA" end
```
works fine. But if you replace
```
state == "CA"
```
with
```
"CA"
```
or
```
5
```
you get "Internal errors prevented this error message from being shown. Please report this as a bug."

**Comment by blerner** [comment]
Hah.  That's a funny one; it's an easy error to fix, but the follow-up error that you get is ugly afterward.  I'll handle this.

**Comment by blerner** [comment]
(Btw, a smaller repro for the same error is `raw-array-filter(lam(x): 5 end, [raw-array: "true", "false"])`.  The internal-error problem is just that `ffi` is an unbound variable in `raw_array_filter`, and should be `thisRuntime.ffi`.)

**Comment by blerner** [comment]
@jpolitz please review these commits: the first one fixes the internal error, but in the second in particular I changed how `type-mismatch` contract errors render, to always render their name.  Otherwise, this would generate the message "the *annotation* [[highlighting `state`]] was not satisfied by the value `"CA"`", which is maddeningly uninformative.  But I don't know whether every single one of our type-mismatch errors have *good* names worthy of displaying...
