### ISSUE TITLE
`^` should give a better error

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1112]
For better or worse, people are used to `^` meaning exponentiation in other languages. So the error for `^` should consider giving an error that says it isn't exponentiation but rather a special kind of application.

**Comment by blerner** [comment]
This appears to be long-since fixed, inasmuch as it says "function application expression":
![image](https://github.com/brownplt/pyret-lang/assets/918464/d0b1b58c-4b59-482b-8c83-9db879b2d4b1)

But it's quite entertainingly claiming `3` is the "left side", and I don't see a good way to fix that, in general...

**Comment by blerner** [comment]
I'm going to close this as good-enough for now.
