### ISSUE TITLE
y-max method not implemented on bar charts in plot-list library

### ISSUE THREAD

**Issue by crowe3717** [brownplt/pyret-lang#1123]
Title says it all

**Comment by blerner** [comment]
Having an explicit range (x/y-max/min) allows easier comparison between two graphs...

**Comment by crowe3717** [comment]
It also allows you to see changes more easily when the values are changing during a simulation.

**Comment by sorawee** [comment]
@blerner it only makes sense here to do `y-min`/`y-max`, since bar-chart's x axis is discrete, not continuous. They could be strings for example, and it makes no sense to set `x-max`/`x-min` for strings.

@crowe3717 thx for the suggestion :) I have implemented this already in my local version, but I can't update the website it yet because the infrastructure is not ready yet.

**Comment by blerner** [comment]
Fair point about x-axis extreme values.  Just make sure that the other plots (scatter, line, whatever) whose x-axis values could be specified, _can_ be specified.

**Comment by blerner** [comment]
@sorawee where are your changes, and what do you need from me or Joe to get them merged?  Got another request about this today...

**Comment by sorawee** [comment]
In progress. I promised @schanzer to finish it by this month, though I think it's really close now. Please give me a few more days.
