### ISSUE TITLE
Need stack trace when having an error in check block

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#1128]
![screenshot from 2017-08-05 22-02-44](https://user-images.githubusercontent.com/9099577/28999972-e9c98f08-7a29-11e7-96a4-dbcca2a77efb.png)

This is really difficult to debug without the stack trace. I don't even know what statement exactly causes the issue.

**Comment by jpolitz** [comment]
Can you share the program? There should be a stack trace there, and it may not be shown because it's not present.

**Comment by sorawee** [comment]
```
fun test(x :: String):
  x
where:
  a = test(1)
  a is 1
end
```
![screenshot from 2017-08-05 23-10-02](https://user-images.githubusercontent.com/9099577/29000232-50d74b3c-7a33-11e7-85a7-a5bdd870b414.png)

**Comment by blerner** [comment]
Note that if you vary the example program by eliminating the definition of `a`, as follows,
```
fun test(x :: String):
  x
where:
  test(1) is 1
end
```
you *do* get a stack trace:
![image](https://user-images.githubusercontent.com/918464/29424791-01bb993e-834f-11e7-9324-708d4b3773c8.png)
though there is now a problem with it -- but that's a separate issue from this one, caused by some code changes I made.
