### ISSUE TITLE
When there is an error in testing, the actual value should be given as well

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#1129]
I was really surprised for a moment for this error:

```
check:
  v1 = {a: lam(): 1 end}
  v2 = {a: lam(): 1 end}
  v1 is v2
end
```

![screenshot from 2017-08-05 22-30-28](https://user-images.githubusercontent.com/9099577/29000058-e4298676-7a2d-11e7-8955-2e053e4375e3.png)

When I read the error, I thought that perhaps the checker is wrong, because it does not blame my code and instead blame two functions that I didn't realize that they exist in my code. This would be worse if the object is much larger and more complex. 

By printing the actual left and right values, users are reminded that functions are in the object.

**Comment by blerner** [comment]
This is ironic.  We have most of the infrastructure in place for reporting this result better: `NotEqual` and `Unknown` both have a `reason` field that explains the access path taken that results in two sub-values being compared that resulted in the problem (see the use of `current.path` in `equalHelp` in runtime).  But we don't quite create that access path reliably (e.g. https://github.com/brownplt/pyret-lang/blob/master/src/js/base/runtime.js#L1870 ignores the current path and similarly line 1879 and others), we don't use it in rendering the results, and we've strongly considered removing it altogether for performance reasons.  It was originally added precisely for cases like these, but never was used.  

I don't know what we want to do here: the current design is both wasteful and yet not informative enough.  Manipulating strings while we're running equality checks is not efficient.  One possibility is to rewrite the equality algorithm so that instead of maintaining strings, it uses a linked-list of access paths (i.e. "the foo field of the bar ref of the 0th raw-array index of the x field of the given object"), and that we somehow use that information better in the rendered output.  This is a non-trivial UI ask, because it implies we need a better way to show a "diff" of two values.  And imagine how lousy the UI will be when you're comparing two Lists, and the umpteenth element of them is different -- you'd have to slog through a *really* long access path to explain why they're different.

**Comment by blerner** [comment]
After #1386 is landed, this particular error will look much better:
![image](https://user-images.githubusercontent.com/918464/43670413-654bb8d4-9759-11e8-95c2-483df6de4f9f.png)

In general, the frequency of "unexpected exceptions" should go way, way down.

**Comment by schanzer** [comment]
@sorawee @blerner this error is now even better on CPO. OK to close?

![image](https://user-images.githubusercontent.com/77126/76869715-143d2000-683f-11ea-98ca-ac838f6f47da.png)

**Comment by sorawee** [comment]
I wouldn't say that it is better. In fact, I'd say that the current result is very subpar. "predicate" links to `v2` which is in no way a predicate, so this is really misleading.

**Comment by sorawee** [comment]
Also, if we evaluate `v2`, we'd find that no error occurs. Even more confusing.

**Comment by sorawee** [comment]
Note that this is fixed in Horizon already, as the label indicates.

**Comment by jpolitz** [comment]
<img width="1904" alt="image" src="https://user-images.githubusercontent.com/119891/89936598-c13a7f80-dbc8-11ea-8ca1-23ba3d767aba.png">
