### ISSUE TITLE
Enhancing contract syntax to include parameter names

### ISSUE THREAD

**Issue by blerner** [brownplt/pyret-lang#1131]
Promoting an email thread to a feature request, and related to #1114 --- and I'd really like to come to consensus on this concurrently with that other issue, so that we change the behavior all at once and in a predictable way:

Currently, our syntax for contracts doesn't allow students or teachers to include the parameter names in the definition.  Concretely, we can write

```
num-exp :: Number, Number -> Number
circle :: Number, String, String -> Image
```
but we can't write "The first number to num-exp is a base and the second is the exponent" or "The first string is outline/solid and the second is a color"  Ironically, we don't even follow this in our documentation, and we write

```
num-exp :: (base :: Number, exp :: Number) -> Number
circle :: (radius :: Number, mode :: String, color :: String) -> Image
```
which is a nice syntax, but is incompatible with what we currently have implemented.  We have several potential syntaxes here, differing in the placement and necessity of parens:

1. `circle :: Number, String, String -> Image` as a top-level unparenthesized annotation
1.5. `circle :: (Number, String, String -> Image)` as a top-level parenthesized annotation
2. `circle :: (radius :: Number, mode :: String, color :: String -> Image)`
3. `circle :: (radius :: Number, mode :: String, color :: String) -> Image` as in our documentation
4. `circle :: radius :: Number, mode :: String, color :: String -> Image`

I'm not quite confident that (4) is unambiguously parseable (in the higher-order or refinement-annotation cases), so I'd really like to rule that out as not-worth-the-risk.  (1) and (1.5) are our current implementation, and so (2) is the closest to that...but (3) matches our docs and seems to be the most "natural" for people who've been writing them this week.

Thoughts?

**Comment by blerner** [comment]
(ping @shriram @jpolitz @schanzer to get their feedback)

**Comment by schanzer** [comment]
If I understand you correctly, it sounds like you're proposing supporting both (1) _and_ one of the others, right? Because I don't want to lose (1) for the sake of BS:A, and possibly DS as well.

I'm happy to defer to you and rule out (4), and I have my own reasons for disliking it. I'd also like to rule out (2), which sort of hides the fact that the Range is truly separate. ("`color` a function type?"). That leaves me really happy with (3).

**Comment by jpolitz** [comment]
I'm happy with the look of (3).

Can we add

```
a-arrow :=
 RPAREN [ann COMMA] ... [ann] LAPAREN ann
```

to the grammar for function annotations to allow it to be consistent?

My only concern is that these aren't copy-pastable to parameters that take functions, and will require moving the paren after the range.

**Comment by blerner** [comment]
Emmanuel, (1) is a hack to the grammar that we added at your request, yes. I think I'm suggesting that we switch from (1) to (3), actually: I don't really want to have two semi-hacky syntaxes for this one special case.  I recognize that in the simplest cases eg Number->Number, the parentheses are visually unnecessary, but I'm not sure whether I think that's a sacrifice worth making.

The problem with (3) and (4) is the end of the range type is not delimited, so in the higher order case, `(a, b, c) -> d, e, f -> g` is ambiguous -- parentheses could go from a to d, or from d to g, so Joe, I don't think we can add this syntax in all positions.

One thing nice about (3) is that the stuff after the :: is syntactically identical to the stuff after the function name in a function definition. One thing not nice about (3) is... that the stuff after the :: is syntactically identical, which makes it feel more redundant.

**Comment by shriram** [comment]
I love the idea — it plays really well into the DR — and I will avoid getting involved in choosing a syntax [anything I ask for will probably turn out to be ambiguous anyway!] so we can converge on something in a reasonable time (-:.

Questions:

1. Can I also name the output? Sometimes it's useful to do so:
```
get-client :: (database :: List<Person>, name :: String) -> (client :: Person)
# Consumes a database and a person whose name must be in it, and computes the client who has that unambiguous name.
```

2. Semantics: when I define the function, do I have to give the parameters the same names? Or is this legal?
```
fun get-client(db, n):
  …
end
```
?

**Comment by blerner** [comment]
I'm worried about (2) also.  I think it should be a well-formedness error if they disagree.

I don't know what to think about (1), because it confuses parameter names with "what names might be in scope?"  I'd rather the return value be anonymous...

**Comment by schanzer** [comment]
@blerner , yes I know you added it at my request (thanks!) -- I was asking if you were proposing a _switch_, or merely an _addition_. I see now it's a switch, and I'm okay with it since Pyret is new enough in the Bootstrap world that we don't have a lot of legacy to worry about.

I know we've mostly settled on proposal (3), but it's worth pointing out:
2. `circle :: (radius :: Number, mode :: String, color :: String -> Image)`
3. `circle :: (radius :: Number, mode :: String, color :: String) -> Image`

(2) has the advantage of working nicely with higher-order functions. The whole "domain->range in parens" rule is simple and consistent. (3) works nicely with the syntax of functions calls/headers, obeying the "all the arguments and parameters in parens" rule. One of these scales down, while the other scales up.

### Back to well-formedness...

Clarifying question: are you proposing that all contracts must include parameter names? Or that they _can_ include them?

Fully agree that it should be a well-formedness error if the names don't match. Also agreed that we should only allow names for things that are in scope.

**Comment by shriram** [comment]
Just to be clear, contracts must _not_ *require* parameter names. This had better be optional. I can't imagine Ben means otherwise, but I want to be clear about this (else I withdraw support for the whole idea).

I'm fine with a well-formedness error if names don't match, and with not allowing a name on return for now. A different way to think about the latter is that we only need names for disambiguation, whereas since there's only one return value, we can speak of _the_ value and there's nothing to disambiguate. We can still give it a meaningful description in prose, but we don't need to distinguish between anything.

**Comment by blerner** [comment]
Correct -- parameter names are optional.

So concretely:

* I'd _like_ to eliminate option (1), `circle :: Number, String, String -> Image` (i.e., the non-parenthesized syntax we added for Emanuel), because it's the anonymous analogue of option 4 that we've ruled out -- this is *probably* orthogonal to this proposal, but aesthetically closely related.
* Option (1.5) is not going away -- we like that, and it extends to the higher-order case.
* Option (2), `circle :: (radius :: Number, mode :: String, color :: String -> Image)` is compositional, but the close parens are annoyingly placed ("Why aren't they where the arguments are?")
* Option (3) matches docs, matches intuition, but is incompatible with option (1.5), and is ambiguous in the higher-order case.
* Shriram's option (1) is a no-go; return values are anonymous.
* Shriram's option (2) is a well-formedness error.

I'm really torn on options (2) and (3) -- if we settle on (2) because of higher-order consistency, then we need to reformat the docs to match.

**Comment by blerner** [comment]
Ugh, another reason against the no-parens version: `foo :: bar, baz :: quux -> fumble` is just a jumbled mess.  I assume that if you name *any* parameter, you must name *all* parameters, agreed?  If so, then the only way to parse this is as a named-parameter, no-paren function-annotation, `(foo :: bar, baz :: quux -> fumble)`.  Which means, if students forget a single parameter name, then they'll get horrid error parse errors -- in this case, you have a free-floating annotation with no name being annotated.

Otherwise if we allow a mix of present and missing names, it'll parse as `foo :: (bar #| type or name? |#, baz :: quux -> fumble)`.  Which is just horrid...

**Comment by blerner** [comment]
Talked with Joe for a bit, and we came up with a compromise solution:  We're going to have the following syntaxes:

* A standard arrow annotation can look like `(A, B, C -> D)`
* An arrow annotation with parameter names must have an extra set of parentheses around the arguments: `((a :: A, b :: B, c :: C) -> D)`
* Top-level contracts may optionally elide the outermost parens, per Emmanuel's request.

That implies that at top-level contracts, there are _four_ valid syntaxes in the simplest cases (I'm switching to names rather than numbers, to avoid confusion with the numbered options from earlier in this conversation):

A. `foo :: (A, B, C -> D)` -- the bog-standard annotation we currently have
B. `foo :: A, B, C -> D` -- Emmanuel's requested top-level shorthand
C. `foo :: ((a :: A, b :: B, c :: C) -> D)` -- new named-parameter annotation
D. `foo :: (a :: A, b :: B, c :: C) -> D` -- new named-parameter + Emmanuel's shorthand

Joe thinks this is a feature-not-a-bug, because it allows students to be a bit flexible about where their parens go for simple cases, and it allows us to continue to document functions as we have been (i.e., that example (D) incorporates our documentation style, option (3) from earlier).  I'm a bit disappointed that there are extra syntaxes, but I can live with it.  And I'm pretty sure that this avoids the two parsing ambiguities I was worried about above, so I think this works.  Higher-order function require arrow annotations to be nested, so the inner arrow-annotations must be surrounded by parens (as they already are required to be).  If you want to name the parameters to the inner arrow-annotation, you'll need a second set of parens around the arguments (as in (C) above).

I think this is a final proposal -- @shriram @schanzer @jpolitz please confirm you're ok with it, and I'll run with it.

**Comment by jpolitz** [comment]
Looks good!

**Comment by schanzer** [comment]
If you're disappointed in the possible forms, I'm totally comfortable killing off A. In fact, I _could_ be comfortable killing off D as well, since "naming your inputs" is a new feature that justifies new syntax or stricter rules.

Otherwise, LGTM

**Comment by blerner** [comment]
Hah! Syntax A is the only one we definitely need to keep -- I wanted to ditch B and D 😎. (Somewhere, Shriram is quietly chuckling that we're relearning the benefits of s-expression syntax...)

Ok, I'll take this as consensus and work on implementing it.
