### ISSUE TITLE
List library should have `andmap` and `ormap`

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1157]
EOM

**Comment by blerner** [comment]
It does, they're called any and all.

**Comment by shriram** [comment]
Can we have these as aliases?

**Comment by blerner** [comment]
You wanted them not to be aliases, because they're shitty names (at the very least, Pyret-style-wise, it should be and-map and or-map).  And because if they're available by default then you need to go through stupid contortions to define them yourself in class (the way that in Fundies we have to define my-map "oh for no special reason")...

**Comment by shriram** [comment]
I don't understand. If they're _methods_, what difference does it matter what they're called? They don't interfere with any new top-level definitions.

**Comment by blerner** [comment]
Wait, what?  "List library should have andmap and ormap".  Since when are you asking for _methods_?  I thought you were asking for new _functions_ in the library.

**Comment by shriram** [comment]
Sorry, I was thinking they could be methods.

**Comment by sorawee** [comment]
@shriram the method `.all` and `.any` have been around for more than two years. Is that enough? Or would you rather have `.and-map` and `.or-map` too?

**Comment by schanzer** [comment]
@shriram ping?
