### ISSUE TITLE
indenter reindents inside comment

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1161]
Here's a comment:

```
#|
(define (only-valid cs-in-w valid-cs)
  (cond
    [(empty? cs-in-w) #true]
    [(cons? cs-in-w)
     (if (member (first cs-in-w) valid-cs)
         (only-valid (rest cs-in-w) valid-cs)
         #false)]))

|#
```

Selecting-all and reindenting causes the `define` line to move inward.

Indenting should not mess with comments, that too multi-line comments…

**Comment by blerner** [comment]
I have no idea what "that too multi-line comments..." means.

Regardless, the intent here is just like with triple-quoted strings: If there is a line of (comment or string) content that is currently indented to column 0, then indent it properly to match the beginning of the (comment or string).  This is eminently necessary: if you start writing a (comment or string), then you expect that when you press enter, it should auto-indent to where the (comment or string) starts, because you're writing a block of content.  However, if the line is indented to anything other than column 0, the indenter assumes you intended for whatever it is to be where you placed it, and will not reindent it.

I'd like to close this as by-design, wont-fix.

**Comment by shriram** [comment]
I view comments and doc-strings differently. Doc-strings are part of the code. Comments are by definition things that aren't part of the code. For instance, I may have pasted in ASCII art generated by some other tool, and it's a critical part of my documentation, and maybe I need to copy it back out into some tool someday. Changing its indents seems wrong.

Can't it be that for multi-line comments, the first line's default indent is 0, but _whatever_ it already is, the indenter leaves it alone?

I pasted a bit of Racket code on purpose: the code is now less readable after the indent, and it may have happened off-screen so I didn't even realize it was happening.

I don't always have the luxury of re-indenting everything before pasting. Heck, I don't even know how to do it easily in general except with a multi-key sequence in Emacs!

**Comment by blerner** [comment]
I don't -- strings may have values and comments may not, but they're both intended to be legible useful parts of the code.  And the initial lines indent should *not* be zero for a block comment, any more than the first line after _any_ block-opening thing should be the same as its opening thing.  Besides, you have to remember that block comments are supposed to work not just at the toplevel, but nested within other code, too -- a zero indent would be *horrid* in those settings.

"Pasting random stuff I wrote elsewhere that's jammed up against the left margin" is the only scenario in which the current heuristic (which is optimized to handwritten comments, temporarily commenting-out chunks of existing code, and even ascii art (which basically always has at least a 1-character margin of space)) fails.  I don't think it's worthwhile to support it, sorry.
