### ISSUE TITLE
Opening a saved document while a new, non saved, document is open.  

### ISSUE THREAD

**Issue by zacharymor** [brownplt/pyret-lang#1172]
When I tried opening a file when a file was already open it gave me two options - One, open in this tab and save the current file first, or Two, open in another tab and keep the current file in its tab. I chose option one, but because, what I assume was, the current file wasn't saved yet, it just attempted to save the file but kept saying "saving…" and never opened the new file, without ever saving the initial file or maybe prompting me to save it as new, or throw some message about it not being saved yet.

**Comment by jpolitz** [comment]
Thanks for reporting – there should be a timeout on that save so that the whole thing at least fails if the save request isn't getting through in, say, 5-10 seconds.

This workflow is working for me right now on a fresh file, but there's any number of reasons (bad WiFi, slowness in the request to Google, etc) that the save would appear to hang.

If I could bother you for a few minutes of effort, could you try opening the original file, and using the Open option to see if it succeeds on another try? I'm curious if this was a one-time thing, or if it's a repeated issue for you or for this file.

**Comment by schanzer** [comment]
This UI no longer exists, making this issue irrelevant. Closing.
