### ISSUE TITLE
duplicate error report

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1178]
[In CLI version.]
```
Cleaning up and generating standalone...
The identifier `map-all-to-1` at file:///Users/sk/Desktop/CodePyret/setops.arr:17:31-17:43 is unbound. It is used but not previously defined.
The identifier `map-all-to-1` at file:///Users/sk/Desktop/CodePyret/setops.arr:17:31-17:43 is unbound. It is used but not previously defined.
There were compilation errors
```

**Comment by blerner** [comment]
Useless bug-report without a program to reproduce it with.

If your particular usage happens to be within a check/examples/where block, this is a known problem due to our desugaring, and is not trivially easy to fix.

**Comment by shriram** [comment]
Yes, it was inside a `check` block.

**Comment by jpolitz** [comment]
This is annoying; I revisited this just now thinking "well this is a stupid issue to have, must be easy to fix".

This is because type-checking happens late, and needs original check blocks to function well, but check block desugaring happens early, and would really like to simply get rid of check blocks entirely. The easy way to get check information to the type checker is to leave them in, but it leads to this situation. We need a "post-desugar-check" set of visitors that ignore vestigial check blocks that are only for TC, or maybe a bit of object extension on key points in our existing visitors to track "in a vestigial check block"-ness.

Or we need to not handle check blocks so early and defer that pass until later, which interacts with name resolution and other issues.

Or, and maybe this is a useful high-level observation, we should just uniqify the errors reported before reporting them. It's not crazy to imagine a system that could report the same error from multiple passes, and would want this behavior anyway.
