### ISSUE TITLE
Feature Request: options to run tests

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#1228]
Right now, if we have

`a.arr`

```
provide *
check:
  1 is 1
end
```

`b.arr`

```
import file("a.arr") as F
check:
  2 is 2
end
```

Both tests will be run and reported when `pyret b.arr`. Ideally, there should be options to:

1. Run tests only on `b.arr` (the running file)
2. Run no tests

**Comment by jpolitz** [comment]
For anyone who wants to grab this, at the CLI all the plumbing exists for this, it's mainly threading the option through.

In CPO it's more work because the UI of the run dropdown gets involved.

On the `server-dev` branch, you can add a new option to `pyret.arr`, and follow the logic that's used for turning off check-mode dynamically in runtime-options (https://github.com/brownplt/pyret-lang/commit/5a7e6816496a30fdf6453c1bca41ccabfb4c79d1)

In the standalone file that starts things up, there's a line that either makes a check context or doesn't depending on a checkAll flag; this can be modified:

https://github.com/brownplt/pyret-lang/blob/5a7e6816496a30fdf6453c1bca41ccabfb4c79d1/src/js/base/handalone.js#L171

The way the two arguments to `make-check-context` work is that the first is always run (assumed to be the main module) and the second, if true, triggers running for everything:

https://github.com/brownplt/pyret-lang/blob/5a7e6816496a30fdf6453c1bca41ccabfb4c79d1/src/arr/trove/checker.arr#L535

It would be pretty straightforward to make a three-valued command line option for "all", "none", or "main".

It would also be nice to add some dynamic options to, for example, run all tests whose name contains a given substring, or whose module name contains a given substring, to support more granular testing.

**Comment by purag** [comment]
Just to be clear, this CLI option would replace no-check-mode and check-all, right?

**Comment by jpolitz** [comment]
I think they should stay just for backwards-compatibility (e.g. I would rather a PR not delete them right away).

But I don't mind the idea of having a single option that can be used in lieu of the existing ones that's better.

**Comment by purag** [comment]
Yeah, no worries. In case someone provides conflicting options (i.e. `-no-check-mode --checks all`), which do you think should take precedence? Another option would be to print-error.

**Comment by jpolitz** [comment]
I'd prefer error if they conflict. If that seems wrong to you, I'd prefer that the new option overrides the old (old clients can't be surprised by that, and you can get the new behavior by adding new CLI args to existing commands).
