### ISSUE TITLE
internal error from type-checking

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1238]
This program produces two errors. For the first, it's not at all clear what is going wrong (presumably a type error in the shared code?). The second leads to an internal error.

```
provide *
provide-types *

import shared-gdrive("mapdata.arr", "0B7QCewoirq6sRVQ1bEM3UjFKX1E") as M

type Loc = M.Loc
type LocPath = M.LocPath
type Tour = M.Tour

loc = M.loc
root = M.root
loc-path = M.loc-path
get-loc-maker = M.get-loc-maker
get-dist = M.get-dist
brown-loc-list = M.brown-loc-list

tour = M.tour
brown-tours = M.brown-tours
```

**Comment by blerner** [comment]
To be clear: this produces two errors *when running with the typechecker* -- running unchecked produces no errors.

The internal error appears to be a field-not-found error: coming from compile-structs.arr, line 1056, it's trying to get the `.id` field of an `a-dot` annotation.  @jswrenn this looks like it's for you: `render-fancy-reason` and `render-reason` are inconsistent about the assumptions they make about the annotation (which, per line 1044, is *any* `A.Ann`), and it looks like `render-reason` is more general.

I don't know exactly what the other problem is yet, but it definitely is a type error coming from the imported file, based on the warning printed to the console: `This position could not be hinted because it is not in this editor: Object { inclusiveLeft: true, inclusiveRight: true, doc: Object, source: "shared-gdrive://mapdata.arr:0B7QCew…", _textMarker: Object, highlighter: Object, 2 more… }`
