### ISSUE TITLE
error message typo

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1248]
![image](https://user-images.githubusercontent.com/75030/32553916-2ba3c746-c466-11e7-8a77-feb288cf781a.png)

Notice the extra period after "It". Also, should there be a period at the end?

**Comment by blerner** [comment]
I've fixed the typo in the commit above, but that error message is lousy in a different way: I assume that `s2` is a `[array: ...]` and not a `[raw-array: ...]`, since raw-arrays don't have methods.  So then why does the message refer to `raw-array-set`?  (Answer: because the index checking isn't done until the underlying `raw-array-set` runtime function call occurs.)  I think we need to bite the bullet and admit that `Array` as a datatype distinct from `RawArray` isn't really working, and clean them up.

**Comment by blerner** [comment]
@jpolitz , feel free to cherry-pick this commit over to master if it needs immediate changing.
