### ISSUE TITLE
'from-rows:' Table constructor

### ISSUE THREAD

**Issue by schanzer** [brownplt/pyret-lang#1261]
(This issue comes from a slack conversation between, @jpolitz , @blerner and I)
For Bootstrap:DS, it would be a significant win if students could create their Sample Tables and Result Tables _programmatically_. I'm thinking something like the following:
```
mittens = get-row(animals, 0)
boots = get-row(animals, 5)
rex = get-row(animals, 8)
bowser = get-row(animals, 17)
princess = get-row(animals, 2)

examples:
  sample = [from-rows: mittens, boots, rex, bowser, princess]
  result = [from-rows: boots, mittens, princess]
  get-sorted-cats(sample) is result
end
```

Needless to say, the `from-rows` constructor would need to confirm that the rows being passed in have the same columns, in the same order, and of the same types. Anything that violates this should throw an error.

**Comment by blerner** [comment]
Context:
* schanzer 
@joe and @blerner - suppose i have a fixed number of Rows, all with the same columns. Is there a way I could provide a function that consumes them and produces a table?

  Thinking ahead to DS 1.1

* blerner 
  hmm.  it kinda should be possible, using list.fold and table.add-row, but I can't see how to get the initial set of columns correct, since it doesn't look like you can introspect on rows to find out their columns

  if you have a list of column names, and a list of rows, then it's easy enough, I think: start with `table: end`, the fold `add-column` of the column names (with an empty list of values each time, since you have an empty list of rows), then fold `add-row` over each row to add the rows one-by-one.

  it's kludgy and slow, but it should work

* joe 
  I'd say it's elegant and slow :-)

  I think this would have to be an alternate table constructor, so it would probably be `table.from-rows(rows)`

  Easy to add

* blerner 
  well, the need for an extra array of the column headers is the kludgy part

  table.from-rows seems like an interesting constructor

* schanzer
  Such a thing would be enormously handy

  I’ve already got a workflow where kids define a handful of values, representing individual rows. These are used for examples in design recipes for filter and build functions

  It would be great to have students use those same values to construct “starter” and “end” tables, which can then be used inside example blocks for functions that consume and produce tables (or for table methods) (edited)

* schanzer 
  I’m imagining something like:
```
midnight = animals-table.row-n(0)
chubbers = animals-table.row-n(1)
sasha = animals-table.row-n(2)
max = animals-table.row-n(3)

is-kitten :: (cat :: Row) -> Boolean
fun is-kitten(cat):
  cat["age"] < 1
end
examples:
  is-kitten(max) is true
  is-kitten(sasha) is true
  is-kitten(midnight) is false
  is-kitten(chubbers) is false
end

get-kittens :: (animals :: Table) -> Table
   animals.filter(is-kitten).order-by("name")
end
examples:
   sample = make-table(chubbers, sasha, midnight, max)
   result = make-table(max, sasha)
   get-kittens(sample) is result
end
```

* blerner 
  No -- you don't get variadic functions :wink:  You can write `[table-from-rows: chubbers, sasha, midnight, max]` if you insist,

  or `make-table([list: chubbers, sasha, midnight, max])`

* schanzer 
  fine fine :stuck_out_tongue:

* and yes, `table-from-rows:` would be perfect

* esp if I can rename it something shorter :wink:

* blerner 
  bearing in mind that we want to make sure the name stays legible/pronounceable, and that it can't clash with existing names, you're welcome to workshop that name with Joe (since he's gonna implement it :wink: ) (edited)

* schanzer 
  `[rows:]`?

  I’m guessing this is something hard/distant, yes? as in, absolutely no way it could be done before Thanksgiving?

  I’m sort of hoping the answer is yes, since it would require a nontrivial modification to the curriculum, and I’m desperately trying to get into polish mode

  actually, it almost doesn’t matter what we call it, since I’ll almost certainly be creating a wrapper function that takes 4 inputs (rows or booleans) and makes the table for them. I’m trying to cut down the number of concepts they have to learn to get started, and `[constructor: ]` notation is one of them

* joe 
 This isn't that hard; I can do this before TG

  The lowest-level thing might be a primitive to get the column names from a row. Then the rest can be implemented in Pyret as a library, which makes many decisions easier

**Comment by jpolitz** [comment]
Finished a few weeks ago, forgot to close:

https://www.pyret.org/docs/latest/tables.html#%28part._tables_table-from-rows%29
https://www.pyret.org/docs/latest/tables.html#%28part._tables_.Row_get-column-names%29
