### ISSUE TITLE
error message only highlights on mouseover

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1291]
```
r = reactor:
  init: init-state,
  update: update
end
```
(assume `update` is defined). The error is the reactor handler named `update`, which should be called `on-tick`. The error reads

![image](https://user-images.githubusercontent.com/75030/34421162-af76999e-ebdb-11e7-9233-df6ffaa8c951.png)

but there is no associated highlighting. However, when you hover over the "definitions…" line at the bottom of the error, the corresponding code does highlight…for some reason it doesn't unless you do.

**Comment by blerner** [comment]
I actually literally fixed this last night, since it was annoying me.  If you try this on pyret-horizon right now, you'll get 
![screenshot](https://user-images.githubusercontent.com/918464/34421313-993d2480-ebdc-11e7-91ff-a0148179205f.png)

It's debatable whether highlighting "Well-formedness" is the best place to put the highlighting, but it's better than the message above.  @jswrenn if you decide to revise these messages further: I've updated the signature for `wf-err` so that instead of taking a mere `String` as argument, it takes a `List<ErrorDisplay>` so that you can have richer output here.
