### ISSUE TITLE
Discrepancies between string color names and image-struct colors

### ISSUE THREAD

**Issue by tom-hoffman** [brownplt/pyret-lang#1316]
light-slate-gray and slate-gray don't work as color names.

dark-slate-gray does.

**Comment by blerner** [comment]
Hmm, more precisely: they don't work as *stringy* color names.  All three of them work from the image-structs library.  And they do work when used with spaces in the name instead of dashes.

@jpolitz I think the right thing to do here is have CPO/src/web/js/trove/image-lib.js load pyret/src/arr/trove/image-structs.arr (which it already does), reflectively enumerate the exported values, find the ones that are `Color`s, grab their names, and initialize the color database with them.  First upcase them, then also replace dashes with spaces, then also remove dashes entirely.  I think that should produce a uniform database.  On a whim, I tried doing it in emacs, just to see the discrepancies: 
* "blanched diamond"
* "dark goldenron"
* "light goldenron yellow"
* missing `transparent` in image-structs
* "cadet blue" is defined twice (slightly differently)
* "cornflower blue" is defined twice (slightly differently)

Probably worth fixing these too :)
