### ISSUE TITLE
column of numbers imports as strings

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1474]
In this sheet

https://docs.google.com/spreadsheets/d/1ldK-Xte5xCAPd6hz2wreBaJzuw-voe4q6ui9QkFGz8w/edit#gid=130903250

which is the Movies sheet linked here:

https://www.bootstrapworld.org/materials/fall2019/courses/data-science/en-us/resources/teachers/index.shtml

the "Rank" column imported as _strings_ instead of _numbers_. Therefore, running (say)
```
scatter-plot(movies-table, "title", "year", "rank")
```
would give an error.

However, I seem to have saved a change that fixes the original, so to reproduce it, you'd have to go back a version. (What I changed is the format: I changed it from Format | Number | Automatic to Format | Number | Number.)

**Comment by blerner** [comment]
1. The links above don't provide edit access, so we can't look at the history of the file.
2. How is this a pyret-lang bug, if the demo file previously wasn't formatted properly, now is formatted properly, and nothing needs to be changed in Pyret to make things work better?

**Comment by shriram** [comment]
Here's a link to the previous version:

https://docs.google.com/spreadsheets/d/1d4w5HAupOsYDYEQeJ5e1QMAIZs9F859ZQi6iRT9imkA/edit?usp=sharing

I'm trying to understand why it's working the way it is. I think most of the time, most people would not think to set the headers, yet Pyret seems to do the reasonable thing.

In the above sheet, let's look at these four columns:

- A (Rank)
- D (Total Gross)
- E (Domestic)
- F (Overseas)
Note that A and E are type Automatic, while D and F are typed Number.

When I pull this into Pyret
```
movies-sheet = load-spreadsheet("1d4w5HAupOsYDYEQeJ5e1QMAIZs9F859ZQi6iRT9imkA")

movies-table = load-table: rank, title, studio, total, domestic, overseas, year
  source: movies-sheet.sheet-by-name("2019", true)
end
```
`total`, `domestic`, and `overseas` are all numbers (e.g., I can add one) but `rank` is a string.

It's possible there's some weird content in the `rank` column that's causing this, in which case there's a good explanation. Absent that, `rank` seems the _most_ numeric of these: there's no decimals or commas, only digits (that I can see).

**Comment by blerner** [comment]
You can *see* that the first column is definitely not typed Number, because all the numeric-seeming values are *left*-aligned compared to all the other numeric-seeming columns.  My hunch is that this spreadsheet was created by initially not having column A present.  The rest of the data was entered.  Then someone added a new column before the previous column A, and so the new column A inherited the now-column-B's formatting of whatever B has, which I'm guessing isn't Number.  

Digging into the sheets.js library while running the code snippet above, the data that we get back from GSheets says that cell A2 (i.e. the value "1") has an `effectiveValue` of `{stringValue: "1"}`, whereas cell D2 has an `effectiveValue` of `{numberValue: 2788}`, which as as definitive as we can get that GSheets thinks column A contains strings.  There's nothing Pyret can do here.

**Comment by shriram** [comment]
As long as that's how it's being reported to Pyret, I agree, it's a non-issue.

(I did see that alignment, but it's worth noting Pyret also aligns its numbers to the left in tables…)
