### ISSUE TITLE
make default table display size be 10 rows

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1488]
It's not uncommon to have a 10-row table (e.g., `simulate-trace(r, 10)`). But the default for tables is to show 9 rows of data, so the last row gets obscured by a "click here". I'd suggest making 10 rows of data the default.

**Comment by BaibhaVatsa** [comment]
If this issue is still open, I would like to work on it. This would be my first issue so would love some pointers.

**Comment by sorawee** [comment]
@shriram it seems to show 10 lines well already... Am I missing anything? Also, the table rendering code was not touched since June, so it's not that this issue was recently fixed...

<img width="279" alt="Screen Shot 2019-10-16 at 03 37 28" src="https://user-images.githubusercontent.com/9099577/66911901-50393400-efc6-11e9-8a41-96a70e64535e.png">

**Comment by shriram** [comment]
Aaargh, sorry, it looks like you're right. I don't know what happened — I tried reproducing it and wasn't able to. Sorry, @BaibhaVatsa!
