### ISSUE TITLE
internal error in reporting?

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1493]
```
data Element: elt(v, ref parent :: Option<Element>) end

fun fynd(e :: Element) -> Element:
  cases (Option) e!parent:
    | none => e
    | some(v) => fynd(e!parent.value)
  end
end

fun union(e1 :: Element, e2 :: Element):
  e1p = fynd(e1)
  e2p = fynd(e2)
  when not(e1p <=> e2p):
    e1p!{parent: e2p}
  end
end

elts = map({(v): elt(v, none)}, range(0, 10))

union(elts.get(0), elts.get(2))
```

This program has a bug: the line
```
    e1p!{parent: e2p}
```
ought to be
```
    e1p!{parent: some(e2p)}
```

But the error is reported weirdly:

![image](https://user-images.githubusercontent.com/75030/67999716-ccbd4b00-fc33-11e9-8c49-6faa76ba1d19.png)

This has elements of the right stuff ("expected to get `Option`") but the rest of it looks like an internal error, especially the "Failed while initializing a graph", which I'm not sure is an error users should ever see (?).

**Comment by jpolitz** [comment]
Yeah, that's a bad error report, and users shouldn't see that graph message, that's internal state leaking. This should be a fancy rendering, and just say “Failed while updating a ref field at ... because: ...”.

Working on it; I think the right thing to do here is just change how the `ref-init`error renders.

**Comment by jpolitz** [comment]
Fixed by https://github.com/brownplt/pyret-lang/commit/73b1fe6d5e5b1ac3f0db597b4bdcd10d873a694b

I got confused by the initial error, though, because I thought the stateful warning outline was highlighting the value that violated the `Option` check, rather than the whole value:

![image](https://user-images.githubusercontent.com/119891/68048171-40477280-fc9d-11e9-9586-17a5aa1e0749.png)

**Comment by jpolitz** [comment]
(That outlining is on horizon but not master)

**Comment by jpolitz** [comment]
<img width="1625" alt="image" src="https://user-images.githubusercontent.com/119891/89936185-19bd4d00-dbc8-11ea-839e-1439a36577ab.png">
