### ISSUE TITLE
add set functions `pick` and `size`

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1510]
This chapter
https://papl.cs.brown.edu/2020/Collections_of_Structured_Data.html
suffers from `pick` and `size` not/no longer being functions.

Can we have `size` and `pick` available as functions, perhaps inside the `set` library, so we can write `set.size` and `set.pick`?

**Comment by blerner** [comment]
Just to clarify: you're unsatisfied with them being methods on the `Set` datatype?  (You already use `s.pick()` at least once in the page, and you use `song-list.length()` somewhere also, so methods aren't foreign at this point in the book.)

JFYI: I just checked, and we can't `include sets` directly into a file, because it will shadow the builtin `fold` and `any` functions (on lists), so you're going to have to `import` the `sets` module, or specifically include individual functions from it.  So it's still not going to be seamless to incorporate those functions into a file.
