### ISSUE TITLE
confusing error with check block order

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1544]
Consider this program:
```
check:
  canDerive(1) is true
end

"remove me" ## <-- this line

check:
  canDerive(2) is true
end

fun canDerive(x):
  true
end
```
When you run it, you get an error that `canDerive` is not bound. But comment out the expression in the middle (the "remove me" line) and everything is fine. This feels a bit fragile and not easy to explain.

**Comment by blerner** [comment]
On the contrary, this is both robust and easy to explain, and moreover was a deliberate design choice.  Every sequence of consecutive function definitions (ignoring check-blocks and examples-blocks) is mutually let-rec'ed together.  We avoid the unwanted problems of sticking everything in a single let-rec, and still have a rule that works for all introductory-course programming examples we've designed so far.  Your example here is a program whose design doesn't follow our DR rules, and whose behavior we therefore don't care to support.

You can add a variable binding into the middle of a run of let-rec-bound function definitions by prefixing it with the keyword `rec`.  If you wrote `rec x = "remove me"` instead, for instance, then your check blocks would both succeed.

Closing as wont-fix.

**Comment by shriram** [comment]
It showed up in a very real program I was wrote, where the structure of
blocks I had was entirely natural *and* did not have this exact structure.
I tried to distill it down into a concise example, but I guess we're going
to close it before even discussing it. Alright.

**Comment by jpolitz** [comment]
Would it help if there was a better explanation in the error message that explicitly listed the things that can precede a definition and still “see” the binding?

**Comment by shriram** [comment]
I just can't see being a priority right now to rework this, that too in a
NEW and complex way.

However, I'm a bit unclear on why "move to the bottom" isn't *always* the
right thing to do. If everything is functional, it doesn't matter. Where
state is involved, it actually provides a very useful pedagogic point. So
I'm not really seeing the "even more confusing scope errors due to
shadowing or due to mutation that are much gnarlier to explain or fix" for
standard, stateless student programs. Can you explain?

In the meanwhile, yes, Joe, a better error message would really help,
because this is brittle.

Shriram

**Comment by blerner** [comment]
Move-to-bottom preemptively _prevents_ even being able to express tests over mutable state or shadowed definitions, because the tests can _only_ see the final state in the file.  That means we wouldn't be able to teach testing of mutable state or shadowing, unless you _also_ mandated that every Pyret file is a module and explain that notion as well -- but that tethers together too many topics at once.

**Comment by shriram** [comment]
But the point is precisely that the test doesn't behave as they expect.

If they want to test with mutable state, they have to explicitly setup and
teardown the state instead of being able to just assume it's in the right
shape. Given that they *can* setup, I don't see why it *prevents* this from
being done — only makes it harder.

**Comment by blerner** [comment]
No, that makes it strictly worse.  Suppose you allowed check blocks in the middle of the file, but chose to execute them at the end of the file.  You have two options for the scope of those tests: the scope they're defined in (in the middle of the file), or the scope they execute in (at the end of the file).  If the former, then you have extremely misleading behavior for mutable state because they'll run at a different time than they're defined, and I'd argue somewhat misleading behavior about which shadowed definition gets tested (since students can easily write such test cases before they've fully grasped closures and closed-over scopes).  If the latter, then you have no way to test functions that get shadowed later (e.g. smart constructors that shadow data definition constructors).

Ok, so you say, it's your own fault for testing mutable state that way: can't you make a copy of the state to test it later?  And it's your own fault for testing shadowing functions: can't you make a copy of the names to test it later?  _Both_ of those require additional definitions, which brings us back to the original observation here, that definitions break up the let-rec groups of a file, and so even your workaround here causes additional problems, without solving any others.  I think it's a really valuable ability for students to be able to write a test case before and after functions that involve mutable state, so that they can observe things change and then can grow from there to learning how to write test fixtures.  And I think it's critical for students to be able to test any definition they write, which means I think it's a clunky workaround to say they can't test shadowed functions without stashing away an additional binding.

**Comment by jpolitz** [comment]
Right now we have a bug that doesn't work how @blerner describes with `shadow`, FWIW:


<img width="1436" alt="image" src="https://user-images.githubusercontent.com/119891/99426843-8330b400-28b9-11eb-9b3a-2bc2c90a5328.png">

AND we move evaluation to the end anyway:

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/119891/99426881-8af05880-28b9-11eb-82aa-c335b07d8f1e.png">

Note that moving check blocks to the end (while ostensibly capturing their original scope, bugs with shadow notwithstanding) is enshrined in PAPL: https://papl.cs.brown.edu/2020/State__Change__and_More_Equality.html#%28part._nature-mutation%29

Setting aside the shadow bug above for a moment...

I really like check blocks closing over their scope because it's in line with a useful principle: the compiler doesn't move code around until _after_ resolving scope.

That said, I think Ben's example of smart constructors has come up for maybe a single digit number of students. So in the spirit of easy things easy and clever things _possible_, I'm open to doing a little different design here.

Another approach here would be to admit more expression types into letrec-chains. For example, we could desugar standalone expressions into `rec _ = trace-value("remove-me")` which would allow for this particular example to work.

Of course, we'd be revisiting scope rules quite a bit if we wanted to implicitly have identifier definitions like `x = e` participate in letrec chains without an explicit marking, and I can see such a definition breaking up two check blocks as well.

**Comment by blerner** [comment]
I am extremely surprised by this behavior; I appear to have a completely backwards impression of our own semantics -- I thought we did close over our scope and didn't move tests to the end :(

I don't like the idea of allowing standalone statements in the middle of let-rec groups, because there's no bright-line distinction we can make to distinguish pure expressions from side-effectful expressions.  Having a literal value is one (fairly useless) thing; Shriram's actual example is more complex and wouldn't work here.  (Also, we explicitly have a well-formedness bug saying that `rec _ = anything` is a pointless anonymous rec variable...so that particular desugaring would in turn create additional problems we'd have to resolve.)

**Comment by jpolitz** [comment]
I don't think it's ever a problem to introduce something _after_ well-formedness checking if it has the semantics we want. WF is before desugaring or scope.

I don't get why side-effectful matters in letrec chains?

**Comment by blerner** [comment]
I'm concerned about two possibilities, actually:
- the free-floating expression refers to things that haven't been initialized yet _because of the letrec_, whereas they would've been if the letrec had been closed off prior to the free-floating expression,
- the free-floating expression mutates things and later let-rec'ed definitions are curried and as a result see those side-effects at some unexpected time.

We know that it's only really safe to have a letrec of delayed expressions (i.e. lambdas as RHS of bindings) so anything that breaks that rule is a recipe for trouble, unless there's a convincing and thorough semantic reason why it wouldn't cause problems.  This just feels like we're tempting trouble for no win at all.

**Comment by jpolitz** [comment]
I mean, we have a pretty well-designed error for precisely that case (modulo a grammatical error in the prose):

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/119891/99451134-99993880-28d6-11eb-817c-a562a79ccf79.png">

**Comment by shriram** [comment]
I have to admit the only semantics I find reasonable to understand *and
explain* is one that moves all the blocks to the end. I actually exploit it
when I teach state. And a large number of students are surprised for a
moment and then realize what has happened and say "Wait, it moves the check
blocks to the end!" And I say "Well, it'd have to, remember you're writing
tests before your write implementations", and they say … "Oh, of course!"
So I'd argue that's a nice, clean, simple semantics to use.

Btw, here's something that literally just now bit me. I had the code from

https://papl.cs.brown.edu/2020/Algorithms_That_Exploit_State.html#%28part._levenshtein%29

on my screen, ready to make some changes to it. Note that the tests go
first, so my file looks like

- memo table def (put on top the get it out of the way)
- tests for `levenshtein`
- `min3`
- `levenshtein`

Everything works fine.

Now I want to make some changes. I start by renaming `levenshtein` to
`lev`, changing the recursive calls. This is fine, but of course all the
tests are broken. So I write

levenshtein = lam(a, b): lev(a, b) end

and I get a long cascade of unbound identifiers. But if I write this as

fun levenshtein(a, b):
  lev(3, a, b)
end

then everything is fine.

Shriram

**Comment by shriram** [comment]
Related example. I had a bunch of functions like `f` of the form

fun p(…): …
f = p({(x, y): …})
check: … f … end

Then I introduced

fun q(…): …

below that to show the next step of the development, and then tried to move
all the `f` definitions to use `q` instead…and everything broke. I had to
move everything up, and that took multiple steps because I first had to
move `q`, then *also* move the `f`s, and then still wasn't done because I'd
separated the definition of `q` from its type, and I'd forgotten to move
the type with `q`.

I really don't see any value that was gained from all these steps, as
opposed to just leaving everything intact in the file and (implicitly)
moving the check block to the end.

**Comment by jpolitz** [comment]
This isn't a check block issue anymore. This is just about top-level scope, which is roughly the same argument as `let rec ... and` vs `let ... let ...` in Ocaml.

If the program just has sequences of declarations mixing `check`, `fun`, and `f = ...`, the `f = ...` lines can use `rec`.

Both of these programs run and the test passes, for example:

```
fun f(): lam(x): q(x) end end
check:
  p(5) is 10
end

fun q(x): x * 2 end
rec p = f()
```

**Comment by jpolitz** [comment]
This has been argued many times; the main tension is what `x = ...` means, and if `x = y y = x` should be a dynamic or static error (or, equivalently, if `x = ...` is `let` or `letrec`). It routinely comes up that someone expects `x = ...` to be `letrec`, but only when it is sandwiched between other `letrec`-like definitions. I'm not sure what to do about that.

**Comment by jpolitz** [comment]
So I guess, a question for @shriram – CS019 seems to be the place where we run into this (though curious if @kfisler has run into anything similar in 111). Should liberal use of `rec` be introduced early as you start to get into the HOF/stream patterns? Or does that not work pedagogically/is it the wrong kind of friction?

**Comment by blerner** [comment]
And does it _introduce_ problems in BS:* materials, where we'd now accept erroneous programs that we were properly rejecting before?  (Basically: is CS019 too advanced to be our target audience for this particular language default?)

**Comment by kfisler** [comment]
I'll admit I've gotten a bit lost trying to catch up on the whole thread. If the question is whether 111 runs into problems with the placement of check blocks: I don't believe we do, partly because we don't really work much with check blocks. The one place where we use them, they go at the bottom of the file anyway. We mostly use where blocks.

I don't have a good feel for how this might play out in a Bootstrap classroom though, simply because I don't know what those code files really look like in practice.

**Comment by shriram** [comment]
Joe's example that ends in
```
rec p = f()
```
is a great one, but also … so bizarre. I just can't imagine using `rec`
there. I had to run it to convince myself `rec` was relevant. To me `rec`
has always meant "make the name visible on the RHS", not "attach this
definition to the current running block of mutually-recursive functions".

Moreover, and perhaps more importantly, I think it's inaccurate to say that
this is a "top-level scope" question and "isn't a check block issue
anymore". If I take the same program and remove the check block
```

fun f(): lam(x): q(x) end end


fun q(x): x * 2 end
p = f()

```
then I no longer need the `rec`. `p(5)` is indeed `10`. So at least in this
example, and in the ones I'm running into, it's the check block that is
indeed intruding on the formation of mutually-recursive blocks. A semantics
that moved the check block to the end would avoid this problem and lead to
more natural mutually-recursive block formation.
