### ISSUE TITLE
Type-checking does not terminate

### ISSUE THREAD

**Issue by tdelv** [brownplt/pyret-lang#1553]
The following code does not terminate when run with "Type-check and Run":
```
cases (Option) some(1):
  | none => [list: none]
  | some(num) => [list: some(num)]
end
```

**Comment by ashdawngary** [comment]
The type checker is not terminating when coalescing the two branches of the cases(Option) statement:
`none => [list: none]` has type `List<forall A . (Option<A> % is-none)> % is-link` indicating a list of Optionals that are none.  Since none does not have a type bound to it (none is a valid element for `Option<X>` for all X), the checker cannot put any constraint on the bounded type of the option.  

For the second branch `some(num) => [list: some(num)]` the branch has `List<(Option<T> % is-some)> % is-link` where `T` is the type of `num`.  This reduces to `List<(Option<Number> % is-some)> % is-link` when cross referenced with what is provided in the cases statement.

Between the two cases, the type of the output needs to satisfy both constraints. This answer should be `List<(Option<Number>)> % is-link`

When executing the block above in Type-check and run, the type checker gathers context and constraints but there is unterminated recursion within the solver.  Profiling `arr/compiler/type-check-structs.arr` and `arr/compiler/type-check.arr` reveals that `solve-helper-refinements` (the function that resolves the refinement constraint portion of the constraint system), is recursively calling itself and adding extraneous substitutions to the solution being accumulated while the constraint system is untouched.  For reference, the constraint system when coming in looks something like:

`constraint-system([tree-set: ?-1], [list: ],
 [list: { ?-1; (List<forall A . (Option<A> % is-none)> % is-link) }, { ?-1; (List<(Option<Number> % is-some)> % is-link) }], [string-dict: ], [string-dict: ], constraint-system([tree-set: ?-1, ?-1, ?-1, ?-1, ?-1, ?-1, ?-1, ?-1, ?-1], [list: ], [list: ], [string-dict: ], [string-dict: ], constraint-system([tree-set: ], [list: ], [list: ], [string-dict: ], [string-dict: ], constraint-system([tree-set: ?-1], [list: ], [list: ], [string-dict: ], [string-dict: ], constraint-system([tree-set: ], [list: ], [list: ], [string-dict: ], [string-dict: ], constraint-system([tree-set: ], [list: ], [list: ], [string-dict: ], [string-dict: ], constraint-system([tree-set: ], [list: ], [list: ], [string-dict: ], [string-dict: ], no-constraints))))))))` which is one existential variable, `?-1`, with two refinement constraints on them, imposed by the two branches of the `cases` statment within the code.  

The function then collapses the two refinements under the same existential variable and assigns an id giving us `[list: { ?-1; (List<forall A . (Option<A> % is-none)> % is-link) }, { ?-1; (List<(Option<Number> % is-some)> % is-link) }]`

Within this step, `solve-helper-constraints` solves for the type A, that satisfies the constraint, and successfully deduces that Option<A> must be compatible with Option<Number> => A is a superclass of Number.

helper-constraints generates a intrim existential to convert from the `for-all` notation to an existential `forall A . (Option<A> % is-none)` to `Option<-1> % is-none`, thus helper-constraints returns two solutions: the solution to A, an intrim existential type, and the type of the list.

Within `helper-refinements`, it only expects 1 substitution, namely the existential variable representing the type of the output of the branches, but instead is provided with 2 solutions, the answer to the intrim existential too.  Then there is a check case which takes the set difference between the solutions given, and what was asked.  Since there is an extra solution, the recursion continues from the top with an extraneous accumulated solution, and the constraints seemingly untouched.

looking at the statement `if size(solutions - temp-vars) > 0`, then replace all solutions with types, and recurse.  I believe the author meant the opposite of this statement, namely if the difference of temp-vars by solutions `size(temp-vars-solutions) > 0`, then replace all intrim solutions and recurse.  The current way it is written creates infinite recursion if the solutions are redundantly constrained, but if something in temp-vars is not in solutions, the size of the difference of the two sets can still be zero.

It seems that the type checker reconciles the type of the block well after the change:
```
x = cases(Option) some(2):
  | none => [list: none]
  | some(num) => [list: some(num)]
end
y = cases(List) x:
  | empty => some(0)
  | link(first, rest) => first
end
z = cases(Option) y:
  | none => 0
  | some(num) => num + 10
end
z

```
 (should return 12 with no error)

```
x = cases(Option) some(2):
  | none => [list: none]
  | some(num) => [list: some(num)]
end
y = cases(List) x:
  | empty => some("dirt")
  | link(first, rest) => first
end
z = cases(Option) y:
  | none => 0
  | some(num) => num + 10
end
z
```
 (errors out, acknowledging that x is of type `List<Option<Number>>`)


```
x = cases(Option) some(2):
  | none => [list: none]
  | some(num) => [list: some(num)]
end
y = cases(List) x:
  | empty => some(2)
  | link(first, rest) => first
end
z = cases(Option) y:
  | none => "a"
  | some(num) => num + "a"
end
z
```
(errors out, acknowledging y has inferred type `Option<Number>`)

Let me know if what I am saying makes any sense.  This is my first "bug" I tried to understand concering cpo and pyret and I might not be conveying my findings correctly.
Thanks,
Neel Bhalla

**Comment by jpolitz** [comment]
Wow, great analysis. My first (somewhat quick) read suggests that you are right.

If you're interested, it would be great if you wanted to send in a PR for this. I'm happy to review more and help turn your examples to tests.
