### ISSUE TITLE
\u0007 == "a"

### ISSUE THREAD

**Issue by BenjaminHLee** [brownplt/pyret-lang#1554]
Control code U+0007 (["Bell character"](https://en.wikipedia.org/wiki/Bell_character)) appears as the lowercase "a" character. `"\u0007" == "\u0061"` is true. (U+0061 is Latin Small Letter A.)

To reproduce:
1. Open the CPO editor
2. Type `"\u0007" == "\u0061"` in the code section OR in the REPL input box
3. Run (output will be `true`)

**Comment by blerner** [comment]
Well this is weird: Typing `"\u0007"` will produce the string `"a"`, but typing `"\u0008"` will produce the string `"\b"` as expected...but `"\b"` is considered an incomplete string, since the `\b` escape code is not recognized.  (For that matter, neither is `\a`...)  Evidently, we have some bizarre edge cases to deal with in our escape sequences, that we haven't handled correctly in the past.

**Comment by BenjaminHLee** [comment]
Looks like `"\v"` and `"\f"` (`"\u000B"` and `"\u000C"`, respectively) are also not recognized.

**Comment by blerner** [comment]
Ok, there are two distinct issues you're noticing here.  Per [the ECMAscript spec, section 7.8.4](https://www.ecma-international.org/ecma-262/5.1/#sec-7.8.4), the only JavaScript single-character escape sequences are `\b`, `\f`, `\n`, `\t`, `\r`, `\v`, `\\`, `\'`, and `\"`.  Pyret makes a mistake [here](https://github.com/brownplt/pyret-lang/blob/horizon/src/js/base/runtime.js#L1447) and escapes `\u0007` as `\a` in output, when it shouldn't.  This percolates through compilation, since the compiler is itself written in Pyret, so that it takes the Pyret code `"\u0007" == "\u0061"` and generates JS code calling `equalAlways("\a", "a")`, and then JS says "well, `\a` isn't an escape sequence I know about, so I'll treat that as the normal letter `a`", which leads to the behavior you're seeing.

The second part is simply that Pyret only recognizes a [very few single-character escape sequences](https://github.com/brownplt/pyret-lang/blob/horizon/src/js/base/pyret-tokenizer.js#L45-L66): `\n`, `\r`, `\t`, `\\`, `\'` and `\"`, and then accepts `\uXXXX` and `\xXX` and `\OOO` multi-character escape sequences.  So we don't let you write `\v` or `\f` or `\b` as escape sequences in strings, though you can write them as `\u000b`, `\u000c` and `\u0008` respectively.
