### ISSUE TITLE
Expose num-round-to

### ISSUE THREAD

**Issue by schanzer** [brownplt/pyret-lang#1572]
This comes up in virtually every DS class and PD:

"How do I tell Pyret to show me a number, truncated to show the first _n_ digits"?

It's trivial to add to the DS library, but I'm wondering why it's not in Pyret itself? Joe says there's already a helper function defined, but it just isn't exposed. Can we expose it?

**Comment by blerner** [comment]
Do you mean this?
![image](https://user-images.githubusercontent.com/918464/107682980-0a01ec80-6c6f-11eb-8903-0a4dcb92e502.png)

**Comment by schanzer** [comment]
No. I want a number, which can be used in the chart libraries (among other things).

**Comment by blerner** [comment]
Hmm, that's not as readily definable or as meaningful.  It's also not what you asked -- "How do I tell Pyret to _show_ me a number truncated to _n_ digits?"

(1) Do you want rounding-at-0.5, rounding-to-even, truncation, floor, or ceiling?  (2) Do you want to specify digits, or power of ten (they're negatives of each other)?  (3) Do you really want to produce charts with modified data in them?  (E.g. if you round all the percentages in a pie chart, they might easily not add up to 100%)

This seems like a chart-rendering issue, rather than a "I really want to mangle the data" issue, no?  I could see wanting an option on charts to render their legends with only _n_ digits of precision (if GCharts allows us that flexibility!), but it seems less good to me to fudge the inputs to them...

What are the actual scenarios where chopping a number (for any of the five rounding modes above, or others) is needed?

**Comment by schanzer** [comment]
When viewing a table, having numbers with 10+ digits is just monstrous.￼ One of the first questions we get from teachers is "how do I just show such and such number of digits?"￼￼

To be more precise, I guess what I'm looking for is the ability to round to that number of digits.￼

**Comment by blerner** [comment]
That sounds like a view problem, not a model problem.  As in, it sounds like we ought to change how we render numbers and/or tables, to make that less extremely unwieldy.

I'm not saying that having different number-rounding functions is intrinsically a bad idea.  But this scenario doesn't sound like a good justification for using them: tables shouldn't have to destructively simplify their data.

**Comment by jpolitz** [comment]
As a programmer, it's frustrating to me that Pyret is clumsy here.
What E wants is available in the language already:

> string-tonumber(num-to-string-digits(1.23562346236, 3))
1.236

Why not just provide a helper that does this? It's convenient, it's
well-defined by num-to-string-digits already, and if we need N
different rounding variants we can add them as needed, but I don't
think that should stop us from providing something that teachers
explicitly want, and is a library convenience rather than a big new
feature.

In the meantime, E, you could add the above composition to the data
science teachpack.

**Comment by blerner** [comment]
I mean, that particular composition defines just 1 of the 10 possible meanings for "make numbers shorter" that I described above: specifically, "rounding-at-0.5 and by digits".  By contrast, we also have
- `num-floor`
- `num-ceiling`
- `num-round`
- `num-round-even`
- `num-truncate`

which are the five rounding meanings I suggested, but they only operate at the units place; they don't take a precision (or digits) argument.  It seems to me that we ought to have the following ten functions:

```
num-{floor, ceiling, round, round-even, truncate}-{digits, place}
```
which generalize the ones above: `num-{...}(n) == num-{...}-digits(n, 0)`.  And `num-{...}-digits(n, d) == num-{...}-place(n, 0 - d)`: the `-digits` versions have the purpose statement of "rounding `d` digits after the decimal place", while the `-place` versions have the purpose statement of "rounding to the 10^d place".

**Comment by blerner** [comment]
@schanzer , I've created the functions above.  I do _not_ think you should use them in the scenarios you've described, and think we ought to come up with a better rendering solution here (it seems quite odd to me that in BS:DS where you spend a lot of effort talking about the provenance and accuracy of data, that you'd deliberately mutilate it solely for presentational purposes...), but you'll have the functions available somewhat soon.

**Comment by schanzer** [comment]
Thanks! I really appreciate it, and I'm super-sympathetic to this being a View problem. But I've learned (from you!) that View changes are complex and can take significant time and engineering resources that won't materials for some time. I can't imagine any teachers would be bothered if we give them this as a bandaid now and then deprecate it in the future (i.e. - when they ask how to truncate, we tell them X instead of Y).
