### ISSUE TITLE
The object type `List<Number>` does not have a field named `rest`

### ISSUE THREAD

**Issue by danilbraun** [brownplt/pyret-lang#1573]
https://code.pyret.org/editor#share=1J66Lr2je3VFHboT2SZ73Mmcopb3x_GB9&v=a3ffc15

```
fun my-num-max(lst :: List<Number>) -> Number:
  doc: "Принимает список чисел и вывдит наибольший элемент этого списка."
  fold(lam(a, base): num-max(base, a) end, lst.first, lst.rest)
where: 
  my-num-max([list: 3, 7, 2]) is 7
  my-num-max([list: -3, 1, 0]) is 1
end

fun sum-max(lst :: List<List<Number>>) -> Number:
  doc: ```Принимает список списков чисел и выводит значение суммы
 наибольших элементов этих списков.```
  cases (List) lst:
    |empty => 0
    |link(fst, rst) => my-num-max(fst) + sum-max(rst)
  end
where:
  sum-max([list: [list: 1, 2, 3], [list: 7, 3, 5], [list: 10, 1 , 2]]) is 20
  sum-max([list: [list: -3, 1, 0], [list: 3, 1, 0], [list: 1, -3, 5]]) is 9
end
```

![](https://files.catbox.moe/43eiew.png)

**Comment by blerner** [comment]
This one isn't a type-checker bug, it's an actual bug in your code :)  Try calling `my-num-max([list: ])` -- there are no elements in the list at all, so accessing the `first` and `rest` fields is not allowed.

The remaining errors you see about unbound identifiers are just a cascading effect: since your program didn't compile, _nothing_ wound up defined and available to you in the interactions area.  I wouldn't worry about those errors, much -- they're annoying, yes, since you can't experiment in the interactions area to figure out what went wrong... We're trying to improve that sometime in the hopefully-near future, though.

**Comment by danilbraun** [comment]
> This one isn't a type-checker bug, it's an actual bug in your code :) 

Yes, I didn't pay attention.

> We're trying to improve that sometime in the hopefully-near future, though.

OK, thanks.
