### ISSUE TITLE
.pick is misnamed

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1620]
Following our convention that imperative operations are named `-now`, shouldn't `.pick` really be `.pick-now`, to indicate that the next time it may not give the same result?

(Arguably the same should be true for random numbers…)

**Comment by blerner** [comment]
Are you sure you still want this?  ISTM that the `-now` suffix connotes "the underlying data is mutable", rather than "this function is non-deterministic"...

**Comment by shriram** [comment]
If you disagree with the suggestion, I won't push for it too hard. There is a pedagogic benefit both ways. The benefit of the current approach is that there's no need to explain the `-now` part. The benefit of changing is you can say "See that `-now`? Remember that, it'll show up again, see if you can make a connection".

While `-now` has indeed been associated with mutability, I have always *read* it (and explained it) as "the next time you ask, you may not get the same answer, and Pyret is alerting you to that"). Put differently, be careful when comparing two `-now` results for equality. From that perspective, it seems to me that `.pick` ought to be `.pick-now`?

**Comment by blerner** [comment]
Hmmm, I can see "the next time you ask, you may not get the same answer" as an ok justification, but it always felt incomplete to me.  The biggest use of -now, to me, is `equal-always` vs `equal-now`, which very much is about the mutability of the underlying data as the _reason_ you may not get the same answer.

I don't feel too strongly either way, especially since we created .pick for its pedagogical use and I think you're the only current user :)  I also don't see how we can change this in a backwards-compatible way, though -- it's not something that a context can easily rename, for instance.

**Comment by shriram** [comment]
Right. I was thinking we could add `.pick-now` as an alias. But I think it's also fine to leave alone. Certainly, `random-now` has an odd ring to it.
