### ISSUE TITLE
extend expressions with variants

### ISSUE THREAD

**Issue by JakeWheat** [brownplt/pyret-lang#1647]
```
data Point1:
  | pt1(a,b)
end

check:
  pt1(1,2).{a:3} is pt1(3,2)
end
```
gives:

```
The left side was:
{a: 3, b: 2, $fieldNames: [raw-array: "a", "b"],  _match: <method:pt1>}
The right side was:
pt1(3, 2)
```
Also, what should you get when you do `pt1(1,2).{c:3}` ? Currently, it's

`{c: 3, a: 1, b: 2, $fieldNames: [raw-array: "a", "b"],  _match: <method:pt1>}`

I would have thought it should be:

`{c: 3, a: 1, b: 2}`

so that `pt1(1,2).{c:3} is {a:1,b:2,c:3}` passes.

**Comment by blerner** [comment]
This was a design decision we made a long time ago, and basically it's hard to make functional extension work nicely with data variants and claim that the extended value is still a data variant.  Suppose your data definition had type annotations on it:

```
data Point: pt1(a :: Number, b :: Number) end

my-pt = pt1(3, 4)

weird = my-pt.{a: "hi"}
```

Would you expect that `weird` is still a `Point`?  Building a data value does three things: it checks that the supplied field values match their required annotations, it sticks those values into a record, and it marks that record with some metadata indicating what data definition and variant created it.  Functional extension isn't responsible for all that -- it just creates a new value by copying everything over to a new record and then updating or adding the newly-supplied fields.  This in turn can violate any type constraints in the original data constructor, so the new value can't generally be considered a proper data value.  So functional extension copies everything except the metadata from the original value, and the resulting new value isn't marked as a data value any more.

Your example is slightly different, in that it adds new fields instead of overwriting existing ones.  But for consistency, we decided to make all functional extension of data values drop the metadata.  Basically: use data values when you want to use `cases`, and use records when you want to have plain objects, and we'll allow you to treat data values as records, but not vice versa.

**Comment by JakeWheat** [comment]
In your example, I would expect either the declaration of weird to either raise an error, or to to be a regular record.

What should the result of this be?

`pt1(1,2).{c:3} is {a:1,b:2,c:3}`

It seems like from your description, these should also pass:

`pt1(1,2).{a:3} is-not pt1(3,2)`  (does currently pass)

`pt1(1,2).{a:3} is {a:3, b:2}`

(Not trying to make a case for the priority of any fixes)

**Comment by blerner** [comment]
(also see #307 and other linked issues)
