### ISSUE TITLE
Students Unable to Use/View Starter Files

### ISSUE THREAD

**Issue by mbergdall** [brownplt/pyret-lang#1689]
Hello,

One of my high school math teachers' classrooms is having issues with students being able to view, access, or edit Pyret Starter Files from the [Bootstraps Math collection/curricula, located here](https://bootstrapworld.org/materials/spring2023/en-us/lessons/choosing-your-dataset/pages/datasets-and-starter-files.html)

Students use Chromebooks, and we confirmed all their website permissions exist. Is there something we may be missing? The site simply does not load. [Here's an example of a starter file they have tried recently.](https://code.pyret.org/editor#share=1lGjndLCWSEoIrV3ErZMXSn_-xakqGvrK)

Thanks!
-Matt

**Comment by liambeveridge** [comment]
Hello,

I'm just jumping in here to add some relevant details about what we are seeing on the student end! When we follow a link to a starter file, the page will load, but the left side of the page will be blank. I attached an image of this below, in addition to what we are seeing in the dev tools. We are thinking this may be due to some blocking or policy on the Chromebook, but we have not been able to find the culprit. In my testing, this has happened with any Pyret link I try to access, and on any chromebook (we've only tested with a couple Chromebooks, but we've heard this issue reported by various students).

![Screenshot 2023-04-05 9 27 56 AM](https://user-images.githubusercontent.com/32782502/230144579-14e7ff86-daa0-46c1-978a-993e06d10eb0.png)
![Screenshot 2023-04-05 9 27 18 AM](https://user-images.githubusercontent.com/32782502/230144627-7813be06-7772-4bde-ba4a-3a7d72d58b05.png)

**Comment by mbergdall** [comment]
Sure thing:


   - Is it all the starter files you've tried? - *Yes*
   - Have you seen the starter files load for other students in other
   classrooms also on Chromebooks? - *It loads on other students' personal
   computers, but I'm not sure if those are Chromebooks or not. *
   - Do you get a particular error message? For example, does it say "The
   file failed to load", "Pyret failed to load", show the spinning logo for a
   long time, show a blank screen, etc? *I have just contacted the student
   with the original issues. There are a few issues. 1) When they access a
   Starter file from the *Datasets & Starter Files
   <https://bootstrapworld.org/materials/spring2023/en-us/lessons/choosing-your-dataset/pages/datasets-and-starter-files.html>
*page,
   the file loads with the editor window filled in, but when they click the
   RUN button it either spins forever or doesn't register that it was clicked.
   2) When the student tries to open their own personal files by logging in on
   the *https://code.pyret.org/ *page, it only blips on the screen and
   won't load the page to even sign on - just gives a blank page that has the
   SIGN OUT button in the top right. The student has provided a quick video
   showing what's happening now. I've attached it below. *

Paula Leifer (she/her)
ORCA HS Math Dept
Mathematics Instructional Mentor
503-897-0351
[image: greetings and salutations]

**Comment by pleifer** [comment]
Here is the video: 
[Screen recording 2023-04-05 09.30.56.webm](https://user-images.githubusercontent.com/129982695/230147472-ecb043f6-4c62-46d7-a4af-7bdbd8b26581.webm)

**Comment by jpolitz** [comment]
Thanks for all the details. The `Network` tab of developer tools might also have useful information.

My guess is content blocking on the Chromebook or on the network in the classroom. At the bottom of this page there are several domains that need to be allowed in order for everything to work and load:

https://www.pyret.org/cpo-faq/

Do you have a way to check if these are all allowed?

```
code.pyret.org uses several domains to serve the programming
environment. If you are configuring an allowlist or denylist in a school
networking tool, the service requires the following domains:



*.pyret.org
--
*.googleapis.com
apis.google.com
*.gstatic.com
*.cloudfront.net

```

**Comment by liambeveridge** [comment]
Thank you! Adding those sites to the allowlist in our security software solved the issue!

**Comment by jpolitz** [comment]
Thanks for reaching out!
