### ISSUE TITLE
Kebab-case variable name selection

### ISSUE THREAD

**Issue by SkylerAusten** [brownplt/pyret-lang#1718]
Ahoy, me hearties!

In the online Pyret IDE, when you double-click `camelCase` and `underscore_case` variable names, it selects the full name.  However, when you double-click `kebab-case` variable names, it will only select the word or dash on which you double-click.

Here's an example where I double-clicked `underscore` and `kebab`:
<img width="190" alt="image" src="https://github.com/brownplt/pyret-lang/assets/40815998/1693c2c6-4d54-4287-ba93-dc2ea6702d1d">

Could the CodeMirror be configured to support kebab-case variables?

**Comment by blerner** [comment]
This is unlikely to happen any time soon -- it's not a CodeMirror _mode_ issue, but rather CodeMirror itself.  I think there's been some work in CM 6 that might support this, but we're on CM 5 and it's a very nontrivial amount of work to upgrade to v6...

In the meantime, what you want is achievable with the keyboard, since <kbd>Ctrl</kbd>+<kbd>Left</kbd> or <kbd>Ctrl</kbd>+<kbd>Right</kbd> will navigate the cursor to the end of the entire name.  So if you have `|kebab-name` and press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Right</kbd>, it'll select the entire name.
