### ISSUE TITLE
Add time-only and time-value functions to complement time-now

### ISSUE THREAD

**Issue by blerner** [brownplt/pyret-lang#1723]
We have `time-now`, that returns the current time in milliseconds since the epoch.  We should add
```
time-only :: <T> (( -> T) -> Number)
time-value :: <T> ( -> T) -> {T; Number}

fun time-only(f) block:
  start = time-now()
  f()
  stop = time-now()
  stop - start
end

fun time-value(f) block:
  start = time-now()
  ans = f()
  stop = time-now()
  { ans ; stop - start }
end
```
that are more usable/informative.

**Comment by shriram** [comment]
I would put a contract on these so that if someone were to accidentally pass in a non-thunk value they'll get a run-time error. I imagine a lot of students will write something like
```
time-only(some-big-computation())
```
and…not at all get what they expect. Of course they'll get an error at `f()` but a contract error may be better. (Ideally, they get an even more informative error that educates them, but that requires reflecting on value types and arity and what not.)

**Comment by shriram** [comment]
I might swap the order of values in `time-value` so that time comes first and value comes second, both matching the focus and the function's naem.

**Comment by blerner** [comment]
The first two lines of the code-snippet _are_ contracts :)

I kept the order that (I think) @schanzer requested in the planning doc; if you want to swap it, that's trivial and fine by me.

**Comment by blerner** [comment]
Where should these functions live?  In a helper library?  In essentials####?  Somewhere else?  `time-now` is defined by runtime itself, since it's a JS primitive, but these others are Pyret utility functions.

**Comment by jpolitz** [comment]
Hm. I think I'd make a new module called `timing`. Re-export `time-now` and define and export these two?
