### ISSUE TITLE
Difficult to understand error

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#203]
Load this program, then run go(), then type `1` followed by `u`. You get a run-time error.

The problem is because I made a mistake transforming the program. In line 35 I have

````
    calc-state(link(string-tonumber(w.current), w.stack.append), "")
````

but that should have been `w.stack` instead of `w.stack.append`. However,

1. The `link` operation does not appear to have checked for this! (https://github.com/brownplt/pyret-lang/issues/202)

2. The error is reported for line 69, which is
````
print(w)
````
It's odd that the error is reported about printing.

Program:

````
import world as W
import image as I

data World:
  | calc-state(stack :: List<Number>, current :: String)
end

INIT = calc-state([list: ], "")
BINOPSWITHOPS =
  [list: 
    {key: "a", imp: lam(x, y): x + y end},
    {key: "s", imp: lam(x, y): x - y end},
    {key: "m", imp: lam(x, y): x * y end},
    {key: "d", imp: lam(x, y): x / y end}]
BINOPS = for map(o from BINOPSWITHOPS): o.key end
DIGITS = [list: "0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
PUSH-KEY = "u"

TEST-W1 = INIT
TEST-W2 = calc-state([list: ], "123")
TEST-W3 = calc-state([list: 123, 55], "")
TEST-W4 = calc-state([list: 123, 55], "123")
TEST-W5 = calc-state([list: 1], "5")
TEST-W6 = calc-state([list: 123, 55, 47, 33], "56")
TEST-W7 = calc-state([list: 123, -55, 47, -33, 0], "35")

fun handle-digit(w :: World, d :: String) -> World:
  w.{current: w.current + d}
end

fun push-current-to-stack(w :: World) -> World:
  if w.current == "":
    w
  else:
    calc-state(link(string-tonumber(w.current), w.stack.append), "")
  end
end

fun handle-binop(w :: World, o :: String) -> World:
  shadow w = push-current-to-stack(w) # normalizes; shadowing prevents inadvertent use of wrong version
  if w.stack.length() < 2:
    w
  else:
    arg1 = w.stack.first
    arg2 = w.stack.rest.first
    ans = ask:
      | o == "a" then: arg1 + arg2
      | o == "s" then: arg1 - arg2
      | o == "m" then: arg1 * arg2
      | o == "d" then: num-floor(arg1 / arg2)
    end
    calc-state(w.stack.rest.rest + [list: ans], "")
  end
end
 
fun key-handler(w :: World, k :: String) -> World:
  ask:
    | BINOPS.member(k) then:
      handle-binop(w, k)
    | DIGITS.member(k) then:
      handle-digit(w, k)
    | k == PUSH-KEY then:
      push-current-to-stack(w)
    | otherwise: w
  end
end

fun drawer(w :: World) -> Scene:
  print(w)
  fun string-image(s): I.text(s, 16, "black") end
  fun stack-num(n, rest):
    I.above(rest, string-image(num-tostring(n)))
  end
  stack = w.stack.foldl(stack-num, I.rectangle(10, 10, "solid", "white"))
  I.above(stack, string-image(w.current))
end

fun go():
  W.big-bang(INIT, [list:
      W.on-key(key-handler),
      W.to-draw(drawer)
    ])
end
````

**Comment by blerner** [comment]
The error location is now reported as `link(string-tonumber(w.current), w.stack.append)` on line 35, called from `push-current-to-stack(w)` on line 63.  That's better, but still misleading (because `link` self-evidently should produce a List!).  The root of the problem now is, annotation checking of arguments is done by the callee, and there's no practical way to thread the source-locations of the caller's arguments to the callee so that the error message can refer to them. We might be able to tweak checking of annotations to include something like "The *nth* argument was expected to have type ...", which could help narrow things down a bit.  OR, we have to rejigger how we throw errors such that thrown errors can signal to their callers that they need some info filled in, and then have the stack-unwinding mechanism understand this extra signaling protocol.  I don't much like that approach, but it might solve this particular scenario.

**Comment by shriram** [comment]
Sufficiently old that it's not worth investigating.
