### ISSUE TITLE
confusing printing of objects

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#207]
A series of print statements resulted in:
````
{stack: [list: ], current: 0, _match: <method>, _torepr: <method>}
{stack: [list: ], current: 0, _match: <method>, _torepr: <method>}
{stack: [list: ], current: 0, _match: <method>, _torepr: <method>}
{current: 0, stack: [list: ], _match: <method>, _torepr: <method>}
{current: 0, stack: [list: ], _match: <method>, _torepr: <method>}
````

This was really confusing because I had already been dealing with programs where I accidentally swapped arguments resulting in safety errors, so I thought "oh gosh, here we go again". But then my program _didn't_ error, so I got even more confused. Then I realized it was printing the fields in a different order...

**Comment by blerner** [comment]
Does this issue still matter?  We have much better stringy printing and rich-repr rendering in the repl, and for things that were data values, you won't get this printing at all.  Do you still want to canonicalize the ordering of field-names when printing objects?  It's not hard to do, but perhaps now that (a) objects like these will never be confused in printing with data values, and (b) we're going to add tuples for truly ordered data, this issue is moot?
