### ISSUE TITLE
Revised Image API

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#417]
This program:

https://code.pyret.org/editor#share=0B32bNEogmncOMkR0UElmUDJEUDA&v=v0.5r781

Should display a white circle in the center of the image, not a white square.

**Comment by blerner** [comment]
FWIW: From a little bit of experimenting, it appears that `place-image` always places its images onto a white-background bounding-box.  So the white circle *is* being drawn properly...but then effectively vanishes into the background.  (Try making all uses of `"white"` be some other color and you'll see what I mean.)

**Comment by jpolitz** [comment]
Thanks.  I see that part of the issue is that all the images are wrapped in SceneImages, which shouldn't happen.  SceneImages clear out the background before a render, which is correct and useful in big-bang and at the toplevel wrapper around the image, but shouldn't happen for each composed form.

If the `clearRect` call at https://github.com/brownplt/pyret-lang/blob/master/src/js/trove/image-lib.js#L379 is omitted, the attached program runs fine, but big-bangs don't clear the image before rerendering, so you get the Solitaire effect, which is obviously wrong.

I think the way to fix it is to find out why all these images are wrapped in SceneImages rather than just being circles, etc, which is the next thing I'm looking into.

**Comment by blerner** [comment]
I'm confused -- according to your comment above, you said you thought the way to fix it was to figure out why things were being wrapped in SceneImages, but this fix doesn't do that.  As far as I can tell, `SceneImage`s are now almost totally pointless: they appear to be isomorphic (in appearance, not (yet?) in image-equality) to a `FrameImage` of a `ClipImage` of a sequence of `OverlayImage`s.  And since we have a type distinction between `Scene`s and `Image`s, I'm not sure why we want this...

Should this really be closed and considered fixed yet?

**Comment by jpolitz** [comment]
Sorry, I should have commented more in the commit message or here.  I consider this issue fixed, with still underlying yuckiness about what scenes are doing that will be more effort to iron out.  Re-implementing some chunks of the image model might be necessary.

It turns out that `place-image` and some similar synonyms return Scenes.  I think that they do so because the xy positioning works out better (maybe compared to pinholing?  perhaps @schanzer knows some history here).  If you look at, say https://github.com/bootstrapworld/wescheme-compiler2012/blob/7d3bae74700a5cb1ced40aa6ade3ad491f742dab/js-runtime/lib/primitive.js#L4651, WeScheme's image library is using SceneImage's `add` method.

I tried replacing the return of `place-image`, which is used in this example, with an OverlayImage (in both directions), and it seemed like it was doing some pinhole placement that wasn't what the place-image program does.  That leads me to disagree that a SceneImage is the same as the Frame->Clip->Overlay composition.

So, after fixing this, my current belief is that SceneImages are being used as a hack to get around pinhole placement.  The fixing commit above is consistent with using them for that hack, so while there should maybe be a new issue, the current one is as resolved as it can be for now.  However, I've also been pretty wrong in understanding some of this library before, so I'd be happy to be corrected if I'm wrong.

**Comment by schanzer** [comment]
Joe's right - SceneImages are only being used as a hack. When I retargeted the image library to match 2htdp/image, that meant ripping out all the old pinhole code. The sceneImage stuff is there for backwards compatibility.

**Comment by jpolitz** [comment]
Play with `overlay-xy`.  It doesn't use the word "pinhole", but that's definitely the sematics.  For example, compare (using the definitions from the program I originally shared):

> I.overlay-xy(DISC, 60, 40, BACKGROUND)
![image](https://cloud.githubusercontent.com/assets/119891/5629592/59aa42ec-9583-11e4-9bfc-5f46f9f0601b.png)

> I.place-image(DISC,
  60, 40,
  BACKGROUND)
![image](https://cloud.githubusercontent.com/assets/119891/5629596/616c739c-9583-11e4-83c5-af917128d82d.png)

**Comment by jpolitz** [comment]
Also, changing the argument order just makes the disc appear off-center (changed to outline rendering because they stacked backwards):

`> I.overlay-xy(BACKGROUND, 60, 40, DISC)`
![image](https://cloud.githubusercontent.com/assets/119891/5629626/a4235552-9583-11e4-8323-c882ebb8d137.png)

**Comment by blerner** [comment]
`I.overlay-xy(DISC, (I.image-width(DISC) / 2) - 60, (I.image-height(DISC) / 2) - 40, BACKGROUND)` produces the same result as `I.place-image(DISC, 60, 40, BACKGROUND)` except for the background nonsense.  According to the [docs](http://docs.racket-lang.org/teachpack/2htdpimage.html?q=overlay-xy#%28def._%28%28lib._2htdp%2Fimage..rkt%29._overlay%2Fxy%29%29) `overlay/xy` aligns on top-left corners, while `place-image` places the center of the placed image at the given coordinates relative to the top-left corner of the scene.  So I'd say that `place-image` really can be expressed as a combinator over `overlay-xy`, and doesn't constitute a need for the fix above...

**Comment by shriram** [comment]
I've been vexed by overlay-xy a lot. I realize that what I actually need is
overlay/offset, which is neither overlay/xy nor place-image...

Maybe we should just cleanup and rationalize this entire set of names.

**Comment by jpolitz** [comment]
Thanks @blerner, that clears it up for me.  I was pretty wrong -- `place-image` actually has closer to pinhole semantics than `overlay-xy`, depending on how it chooses the "center" of the image!

With that cleared up, I agree with Ben and I'm back to thinking that removing just about all instances of Scenes moves things in a cleaner and more unified.  Is there any reason not to do that, @schanzer?

**Comment by blerner** [comment]
Correct me if I'm wrong, but I think this is the description:

* `overlay` composes on image on another such that their centers are aligned
* `overlay/align` overlays one image on another, such that the given location (e.g. left-middle) of both images are aligned.  So `overlay` is `overlay/align` at "center-middle".
* `overlay/offset` overlays one image on another, such that their centers differ by the given (x,y) delta
* `overlay/align/offset` overlays one image on another, such that the given location (e.g. left-middle) of both images differ by the given (x,y) delta.
* `overlay/xy` overlays one image on another, such that their top left corners differ by the given (x,y) delta.  I *think* `overlay/xy` is the same as `overlay/align/offset` with location "top-left".
* `place-image` places the center of one image at the given coordinates on the given scene
* `place-image/align` places the given location of one image at the given coordinates on the given scene.  So, `place-image` is `place-image/align` at "center-middle".

Seems to me we very much want the `/align` variants.  And there's one more, for full generality: `(overlay/align/align/offset img1 xplace1 yplace1 dx dy img2 xplace2 yplace2)`, which overlays the first image onto the second, such that the given location of the first image and the given location of the second image have the given delta.  (E.g, put the top-middle of the first image (dx,dy) away from the bottom-right corner of the second.)  At the moment, I don't think we can even express that last one in Pyret without resorting to pixel-munging numeric computations.

My suggestion for cleaning up these names:

* `overlay/align/offset` ==> `overlay-at-shifted` (mnemonic: "overlay img1 and img2 at their given points, shifted by delta")
* `overlay/offset` ==> `overlay-shifted`(mnemonic: just have to remember that the default is centered somehow...)
* `overlay/xy` ==> `overlay-top-left-shifted` (mnemonic: built into the name.)
* My hypothetical `overlay/align/align/offset` ==> `overlay-onto-shifted` (mnemonic: "overlay img1's given point onto img2's given point, shifted by delta"; also "onto" is longer than "at", and the argument list here is longer than for `overlay-at-shifted`.)  I'm not wedded to this function, but I do think it might be useful.

Also, once we get translation of images working well, can we figure out a good API for rotation of images about points other than their centers?  Pretty please?  ;-)

**Comment by shriram** [comment]
@blerner's proposed API is pretty good. I think it'd be a lot less confusing than the ill-chosen, poorly-thought-out names in Racket which we've just inherited. @schanzer can you take a moment and think about how this will play out in BS settings?

**Comment by schanzer** [comment]
(@blerner , I owe you an apology for not weighing in sooner.)

Note: using descriptive terms rather than primitive names
In BS:1 and BS:2, we pretty much _only_ care about `align centers of a list of images` and `put this image on top of another, with centers offset by x/y`. Very, very infrequently do we use `beside` or `above` semantics. If we could keep all four (using Racket names in Spyr^H^H^H^HPatch), that covers our most-common use-case.
@blerner , I _think_ I like your proposal, but it would helpful to see the full contracts for those functions to make sure my understanding is correct.

**Comment by blerner** [comment]
`overlay-onto-offset: Image, XPlace, YPlace, Num, Num, Image, XPlace, YPlace -> Image`  Every other function we've discussed can be implemented in terms of this one.  (I don't care in detail what names are used for Patch, though I do think the names can be better than the ones inherited from Racket.)

```
overlay img1 img2 = overlay-onto-offset img1 "center" "middle" 0 0 img2 "center" "middle"
overlay/xy img1 dx dy img2 = overlay-onto-offset img1 "top" "left" dx dy img2 "top" "left"
overlay/offset img1 dx dy img2 = overlay-onto-offset img1 "center" "middle" dx dy img2 "center" "middle"
overlay/align img1 xplace yplace img2 = overlay-onto-offset img1 xplace yplace 0 0 img2 xplace yplace
overlay/align/offset img1 xplace yplace dx dy img2 = overlay-onto-offset img1 xplace yplace dx dy img2 xplace yplace
place-image img1 x y img2 = overlay-onto-offset img1 "center" "middle" x y img2 "top" "left"
place-image/align img1 x y xplace yplace img2 = overlay-onto-offset img1 xplace yplace x y img2 "top" "left"
```

Consider the following drawing that I just tried to make the other day: a tall rectangle, with a horizontal arrow pointing at the top-left corner of the rectangle.  Can't be done with existing operations (unless you resort to assigning pinholes and manually doing all the math).  But it can be expressed as
```
overlay-onto-align img-arrow "center" "right" 0 0 img-rect 0 0 "top" "left"
```
(Actually, my problem was harder, and I needed a bunch of arrows pointing along the left side of the rectangle.  That still can't be done with overlay-onto-align, since after overlaying the first arrow, the top-left corner has changed... :(  But I'm not proposing an even-more-complicated API just yet...!)

**Comment by schanzer** [comment]
I'm definitely happy with this.

**Comment by schanzer** [comment]
While we're on the image API, I'd like to make two requests:
* `flip-horizontal` should be replaced or aliased with `reflect-y` (ditto for vertical/y)
* `place-image` should be aliased with `translate`

These terms have come up in a lot of math teacher workshops, and it would be nice to support them.

**Comment by schanzer** [comment]
One more request: in the new API, can we use the first quadrant as the basis for all our offset measurements? Switching from `place-image` (inverted y-axis) to `put-image`won us a lot of praise from teachers, and I'd like to carry that forward into all our other functions.

**Comment by jpolitz** [comment]
Another request, which can be added now. The only way to do a non-cropping overlay is to use `overlay-xy`, which sucks as noted above.

What about a function `put-image-extend`, which is just like `put-image` but doesn't crop?

I have a direct request from a teacher for this, who has students frustrated with `overlay-xy`, but needs non-cropping overlaying.

**Comment by blerner** [comment]
Ok.  I've implemented the new primitive `overlay-onto-offset`.  While I'm at it, I've also modified the API for everything to no longer be stringly-typed: everything uses `Color`s, and new `XPlace`, `YPlace` and `OutlineMode` enums.  (I haven't changed the font descriptors yet.)  **This is a deliberately breaking change**, and I think we need to consider a separate `simple-images` library for use with Bootstrap, that isn't strongly-typeable and can have whatever convenient helper functions we want.  (I can alias flip-horiz/vert with reflect-y/x, and place-image with translate; that's no big deal.  But it seems to me this might be better off in a simplified wrapper library, rather than the main one.)

I don't understand the remaining requests:
* Do we want to *change* the behavior of the offset functions to be the opposite of what they currently are?  We have three options here: (1) leave them alone, so e.g. `overlay-xy` with positive dx and dy will move the second (bottom) image right and down.  (2) invert the y-axis only, so `overlay-xy` with positive dx and dy will move the second (bottom) image right and up.  (3) invert the sense of the movement, so `overlay-xy` with positive dx and dy will move the first (top) image right and up.  (This third one feels most natural to me in the context of the `overlay-onto-offset` primitive, which seems to me to be best read as "overlay the Place1 of Image1, shifted by Offset, onto the Place2 of Image2".)
* I don't quite understand `put-image-extend`, and I'd like to understand it in terms of `overlay-onto-offset` rather than as a new scene-manipulating primitive.  @jpolitz, are you saying that it's like overlay-xy, but using centers rather than top-lefts?  Or that it's like overlay-xy, but with the y-upward coordinate system?  Or something else?
* There appears to be a bug in how Pyret handles `baseline` alignment, which doesn't seem to be introduced by my code, but I'm also not sure how to fix it yet (@schanzer it looks like you have a TODO comment about this?)

My initial commit is [here](https://github.com/brownplt/code.pyret.org/commit/a5a19bfb9159ac00dc497a9376ffe749a20891db); please take a look, comments welcome (especially for naming, which I haven't optimized at all yet).  One fun demo:
```
include image
include image-structs

bkg = above(
  beside(square(30, mode-solid, blue), square(30, mode-solid, red)),
  beside(square(30, mode-solid, green), square(30, mode-solid, gray)))
test = overlay(square(10, mode-outline, black), square(10, mode-solid, yellow))

acc = table: xp1, yp1, xp2, yp2, img end
for fold(shadow acc from acc, xp1 from [list: x-left, x-middle, x-right]):
  for fold(shadow acc from acc, yp1 from [list: y-top, y-center, y-baseline, y-bottom]):
    for fold(shadow acc from acc, xp2 from [list: x-left, x-middle, x-right]):
      for fold(shadow acc from acc, yp2 from [list: y-top, y-center, y-baseline, y-bottom]):
        acc.stack(table: xp1, yp1, xp2, yp2, img
            # Note: change 0, 0 to dx, dy in the same sense as overlay-xy currently means them:
            # it will shift the bkg image down and right
            row: xp1, yp1, xp2, yp2, overlay-onto-offset(test, xp1, yp1, 0, 0, bkg, xp2, yp2)
          end)
      end
    end
  end
end
```

**Comment by schanzer** [comment]
1) Awesome to see this moving forward! Ben, thanks for making it happen.
2) I'm all for a compatibility library of some sort. How about `wescheme-images`, since the express goal of the lib is to provide backwards-compatibility with WeScheme?
3) Can we use a custom error message to expressly point users to the compatibility library, at least for one year?

As for the bug in `baseline` -- what bug do you see? I intentionally set the `alphaBaseline` measurement to 0, because WeScheme did not support any of the other baseline variants. I left the field (and the codepath in `overlayImage`) in there in case that changed in the future, but it shouldn't be causing any problems unless Pyret is allowing for different variants than WeScheme.

**Comment by blerner** [comment]
2. Sure, sounds fine.  Now...what APIs would you like in there?  ;-)  Specifically, do you want y-downward APIs or backwards-incompatible y-upward APIs?  If you can give me a specific set of APIs that the various BS:* need, I'll make sure they're available.
3. I don't know how to build that.  Custom error message...for what problem?

For baseline: what is the coordinate system you're using, such that `baseline = 0` is meaningful?  Regardless, it doesn't match the baseline of text: if you try to `(overlay/align 'middle 'baseline (text "fjord" 20 'black) (rectangle 80 30 'solid 'lightgray))`, in DrRacket, you get just the tail of the `j` below the gray box.  If you try it in WeScheme, you get the entire text below the box (the top of the `f` touches the box).  If you try it in current CPO, you get the same as CPO (but with a different font).  And if you try it with my code right now...it's broken, you get the text above the box (the tip of the `j` touches the box).  I'd like it to be at least the case that the entire text is bottom-aligned with the box, which is closer to the idea of "baseline", I think...

**Comment by schanzer** [comment]
2. Bootstrap uses ONLY y-upward APIs, but I see no reason to _remove_ the other ones that we inherited from WeScheme. Since this is going to be a compatibility library anyway, let's keep that cruft in and keep the new library as clean as we can.
3. Statement of problem: someone tries using a string as a color with the new API. I'd love to have the error say some like "did you mean to use the `compat-images` library?"

My reading of the [MeasureText documentation](https://galactic.ink/journal/2011/01/html5-typographic-metrics/#baselineCanvas) is that the only baseline that's universally supported is the alphabetic one, which puts the baseline at the bottom of the DOM element (thus, height = 0). However, I wrote this code back in 2013 and I'm totally willing to believe that both my code _and_ my reading is faulty! The behavior you describe in the last sentence is what I want as well - feel free to break compatibility with the old library here...

...in fact, could you backport your new code to that library as well? Bootstrap doesn't do anything that depends on baseline alignment, but if it (someday) does I'd like it to work properly.

**Comment by jpolitz** [comment]
I want to cast my vote for _not_ changing the meaning of existing import statements, and coming up with a new name for this library. We should start using it in new materials, and encouraging folks to switch by showing them the new functionality we can get out of it. I think it's fine to tie these things together (after all, this new ability is a great selling point for it).

I'm not at all convinced that our users will know how to respond to an error message telling them to change import lines, I don't know all the places where `import image` appears in a public shared file, and I'm not sure how to track them down. The loss of confidence in this breaking will be huge, and I think is best avoided.

If we want to deprecate the current meaning of `import image` someday, we should print a deprecation warning with a clear date and instructions for contacting us and getting help, and we should make sure we get notified via logging of folks using `image` so we can know how many instances are out there.

**Comment by blerner** [comment]
I was deeply afraid this would be your response :(

I'm very saddened that we're going to get stuck with the same "htdp/image" and "2htdp/image" split that Racket has, with some other "image", "fancy-image" library name pair.  This sux, and it's our own fault for letting this languish for three years...

**Comment by jpolitz** [comment]
I think we can force the upgrade eventually. I don't think we can do it without a lengthy deprecation period.

**Comment by blerner** [comment]
I suspect that's tantamount to never changing the name, though.  Because we'll have yet more files and projects and students and teachers who've used the existing names...

The only way I see this working well is if we get everybody on board with `include $bootstrap-course-$year` as their standard prologue, and then we can keep that as the compatibility shim.  And we need to do that *soon*...

**Comment by jpolitz** [comment]
I think we can engineer the warning to work sufficiently well. Let's not give up on it.

```
This program is using an out-of-date library! This message will appear every time you run until this is fixed.

This program uses the `image` library, which is going to CHANGE on July XX, 2019, and work differently. You have two options:

- Change any uses of `import image` or `include image` to use `untyped-images` (easiest)
- Follow <link>this guide</link> to change your program to work with the new library
```

**Comment by blerner** [comment]
I've pushed a bunch of changes to the [new-image-lib branch](https://github.com/brownplt/code.pyret.org/tree/new-image-lib):
* Better handling of text baselines.  Images preserve baselines as long as they can (e.g. if you `beside-align` two text images at their baselines, the result still has a baseline, so you can fold with this to align more text).
* Reintroduction of pinholes, and using pinholes as possible alignment points
* Strong types for everything
* New selenium tests for the new features
* Split `name-to-color` into two functions, `name-to-color` that returns an `Option<Color>`, and `color-named` that throws errors for unknown color names.

**I'd like feedback on the following:**
* Name choices for `XPlace`s, `YPlace`s and `OutlineMode`s.  I tried to pick names that wouldn't immediately conflict with everything, should they be `include`d into a program
* Whether we want enums for `text-font`'s faces, families, styles, and weights
* A quick audit of the types I entered.  I think they're right, but they may have typos; also, I don't know if we have any static types corresponding to refined numeric types (like angles, or positive integers, etc.).

**I haven't made the following change yet; I'd like @jpolitz and @shriram to agree.**  I talked to Emanuel yesterday and he was ok with my changing the default behavior of `overlay` to overlay at pinholes rather than centers.  For almost all images, the default pinhole *is* the center; for polygons and stars, the pinhole is the barycenter (the average of all points) -- so, overlaying an equilateral triangle onto a flipped equilateral triangle will produce a symmetrical 6-point star, rather than a weird wedge shape, and overlaying a 5-point star onto a flipped 5-point star yields a 10-point star, rather than a weird thing.  This will make e.g. drawing the Captain America shield more accurate (`overlay-align(x-pinhole, y-pinhole, star(50, mode-solid, white), circle(50, mode-solid, blue))` gives a symmetrical image, rather than a slightly bottom-heavy one).  I think we want `overlay` to have this align-to-pinhole behavior by default.

I have not yet built the compatibility library, though it should be straightforward enough...

**Comment by blerner** [comment]
@jpolitz your suggestion seems to me to indicate that we add a field to our compiled module representations somehow (and possibly a surface-level marker for it too) that indicates that a module is deprecated.  I don't think we want to hard-code a special-purpose message, if we can avoid it, no?

**Comment by schanzer** [comment]
- `XPlace` and `YPlace` make sense to me. I don't like `OutlineMode`, since `solid` isn't really an "outline mode". How about `Mode`, `Fill` or `Style`? Or perhaps `FillMode` or `StyleMode`?
- Personally, I would be confused if an API took string values for one limited set of options but enums for another. I say go enum all the way.
- Types look right to me.

Also, why are we preserving `bitmap-url` in this new library? Didn't we discuss generalizing to `image-url` for CPO, along with (someday) things like `csv-url`?

**Comment by jpolitz** [comment]
@blerner yeah that sounds like a one reasonable implementation.

I'm not sure if that warning message itself goes in the compiled module's source or not, since it's probably markup that needs to be rendered in multiple places in general.

I could see putting the warning itself into the module loader, which just looks for a flag on compiled modules for if they are deprecated or not, and then figures out what error message to show based on the module name. Then it would have access to all the rich rendering stuff to show the warning.

**Comment by shriram** [comment]
>
> I was deeply afraid this would be your response :(
>
> I'm very saddened that we're going to get stuck with the same "htdp/image"
> and "2htdp/image" split that Racket has, with some other "image",
> "fancy-image" library name pair. This sux, and it's our own fault for
> letting this languish for three years...
>

I don't think we ever really had a choice about this. We've never really
talked about versioning, and anyway I don't know of any good answers to
that.

But I don't think we can risk destabilizing all prior code by making an
incompatible change.

Shriram

**Comment by shriram** [comment]
>
> *I haven't made the following change yet; I'd like @jpolitz
> <https://github.com/jpolitz> and @shriram <https://github.com/shriram> to
> agree.* I talked to Emanuel yesterday and he was ok with my changing the
> default behavior of overlay to overlay at pinholes rather than centers.
> For almost all images, the default pinhole *is* the center; for polygons
> and stars, the pinhole is the barycenter (the average of all points) -- so,
> overlaying an equilateral triangle onto a flipped equilateral triangle will
> produce a symmetrical 6-point star, rather than a weird wedge shape, and
> overlaying a 5-point star onto a flipped 5-point star yields a 10-point
> star, rather than a weird thing. This will make e.g. drawing the Captain
> America shield more accurate (overlay-align(x-pinhole, y-pinhole,
> star(50, mode-solid, white), circle(50, mode-solid, blue)) gives a
> symmetrical image, rather than a slightly bottom-heavy one). I think we
> want overlay to have this align-to-pinhole behavior by default.
>
> Yes! I have noticed this too, but didn't bring it up.

But does this expose the pinhole concept at the library level?

Shriram

**Comment by jpolitz** [comment]
Yes, and `&v=` almost immediately broke because the UI code and language code were difficult to keep in sync. I'm pretty sure giving up on that was the right call so we didn't litter the system with old, unmaintainable expectations.

**Comment by blerner** [comment]
Is there any reason to keep both `color-list-to-image` and `color-list-to-bitmap`?  The former is just `place-pinhole(color-list-to-bitmap(...), pin-x, pin-y)`, and the latter ought to set its pinhole to the center of the image, not the top-left corner...

**Comment by schanzer** [comment]
I can’t think of a reason to keep both

**Comment by jpolitz** [comment]
Had some discussion about this today. The conclusion was that the right approach is going to be to keep the existing image library in place (of course, adding any new cool alignment/offset functions), but not changing the stringly-typed nature of it.

If a user wants to _upgrade_ to using the typed version which may enable richer combinators, etc, we will show them how to do so. They write

```
import image-extras as IE
```

Then, if they want to make a fancy image only creatable with `image-extras`, they just change the one expression that they need to update.

This is a bit of a gradual typing story. I think there's some beautifully simple design in how the untyped version works for lowering the floor, and some cool design in finding our way up. But we should be hesitant to make changes that raise the floor. Are folks into getting behind this argument?

**Comment by shriram** [comment]
Joe and I agree on this. It’s not Ben’s ideal answer, but this is still
what makes most sense, I think. This does go down the “2htdp” road, but I
have not seen a good alternative to that.

**Comment by blerner** [comment]
Yeah :-\  Backcompat is a pain...I'm impressed we have enough users that it's worth forcing that issue right now, though!

Two related questions, then: don't we want the two libraries to stay at parity (or do we really want to let image-extras race ahead and contain new features that we don't backport to the stringly typed image library)?  I don't like the name "image-extras" since that's misleading: you can only use one of these libraries at a time (and it's even more misleading if we keep the libraries feature-equivalent), so what should we call it that encourages people to switch but doesn't sound like you can use both at once?

**Comment by shriram** [comment]
We do want them to stay in sync as much as possible. It would be a pain to
have to choose typed interfaces based on features. Maybe one can call out
to the other?

I don’t think “image-extras” was proposed as a serious naming idea.

**Comment by jpolitz** [comment]
> you can only use one of these libraries at a time

I don't think that's true. I think there's a gradual path where you write:

```
include image # this was in your Bootstrap starter file
import images-fancy-name as I # this you add

# down here, all of the Bootstrap images work just the same,
# but you can also use color combinators, opacity, etc.
# You could move one function at a time to move towards typability
```

**Comment by blerner** [comment]
As a technical point, yes, that's correct.  As a practical point, though, my gut reaction is "no novice student is ever going to do that!" -- the raw fact that colors are strings in one and `Color`s in the other means that it's impossible to freely mix and match between image-forming functions without considering all the caller contexts, and that's kinda too onerous to make this worthwhile.

**Comment by schanzer** [comment]
I totally agree that nobody would ever use both libraries. Certainly no Bootstrap teacher will! But I think the important word in @jpolitz 's comment is _gradual_.

I can totally see a teacher loading both libraries, then gradually walking students through the code, pausing at each image function application, and asking "what needs to change here?" They can click Run as often as they like, to ensure that nothing has changed while they're porting things over to the new library.

To me, this is an insanely powerful teaching activity. Also, I don't care if the `typed-images` (or whatever we call it) becomes a superset of the existing library. Frankly, putting new primitives in the new library just makes it that much more worthwhile for teachers to make the switch.

**Comment by schanzer** [comment]
@blerner this is now on CPO, right? OK to close?
