### ISSUE TITLE
Notification area hidden behind run/stop buttons on narrow screens

### ISSUE THREAD

**Issue by awan1** [brownplt/pyret-lang#426]
Minor cosmetic issue. 

The toolbar buttons jump down if there isn't enough space for them. In particular, this happens with smaller browser windows, and when text such as "saved file as..." appears.

Observed in chrome. 

![image](https://cloud.githubusercontent.com/assets/6291092/5838564/488655a8-a156-11e4-8610-f8eb16f5004f.png)
![image](https://cloud.githubusercontent.com/assets/6291092/5838619/b3da1632-a156-11e4-99e1-5d4a1539352b.png)

**Comment by jpolitz** [comment]
For now, I've changed the positions of the run/stop buttons to be `fixed`, so you get this:

![image](https://cloud.githubusercontent.com/assets/119891/5842242/3662e312-a171-11e4-9ce4-b97fbbaaad15.png)

This fixes 90% of the problem for, say, live-coding on a projector because no jumping buttons, but really we need to think about a more responsive design for the toolbar to get this right.

Another option is to find a different place for the notifications.  @schanzer had a good suggestion a while ago of having them scroll up from the bottom of the screen, and then disappear after a delay.

**Comment by schanzer** [comment]
The notification area is no longer at the top to begin with, and this is a CPO issue anyway. @jpolitz  Recommend closing.

**Comment by schanzer** [comment]
@jpolitz OK to close? If it bothers anyone enough, we could open an issue on CPO where it belongs.

(IMHO - the solution is just to set `min-width` on the editor body. `600px` would eliminate this issue entirely, but if we want to be really gutsy we could make the Run/Stop buttons shrinkable and probably get down to 400px.)
