### ISSUE TITLE
Unclosed comment is parsed as line comment

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#429]
This program parses the `#|` as a line comment since there is no matching close comment glyph:

```
#|
print("you wouldn't expect this to print, would you?")
```

**Comment by blerner** [comment]
Derp.  The lexer for line comments should check for # not followed
    by a |.  
    
    BTW -- how do you want the syntax highlighter(s) to handle this? 
    Should we detect this as an UNTERMINATED_BLOCK_COMMENT, much as we
    do with UNTERMINATED_STRING?
    
    On 1/27/2015 2:28 PM, Joe Politz wrote:
    
    
      This program parses the #| as a line comment
        since there is no matching close comment glyph:
      #|
print("you wouldn't expect this to print, would you?")

      —
        Reply to this email directly or view
          it on GitHub.

**Comment by jpolitz** [comment]
UNTERMINATED_BLOCK_COMMENT sounds useful; it probably shouldn't change colors until the comment is closed; misleading otherwise.  Good idea, I didn't think of that when I was adding this at all.

**Comment by blerner** [comment]
Yeah, well, it's not as easy as I remembered ;-)  We detect unterminated strings in the CM highlighter, but that only works because we require that strings are one line long.  I don't think we detect unterminated multi-line strings.  UNTERMINATED_BLOCK_COMMENT would definitely be useful for the actual lexer, and the lexer is definitely currently broken for unterminated block comments --- if it runs out of string to lex, it'll just happily say "it's a comment", rather than say "you forgot to close your comment!"

**Comment by jpolitz** [comment]
Also fixed and out.
