### ISSUE TITLE
Ctrl-a and then "tab" dedents all content in block comments

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#430]
@blerner, do you know if there's a good way to just turn off indent mode altogether (EDIT: when inside a block comment), and leave it up to whatever the user had?

**Comment by blerner** [comment]
I assume you mean turn off indent mode only within block comments, right?  (We don't want to turn off smart indentation of regular pyret code...)  If so, that's the wrong way to think about it.  What has to happen is that the indentation structure I maintain per line (with all of its dozen reasons about what the indentation should be) now needs another field, `blockCommentDepth`, that keeps count of how deep the comment nesting depth is.  Then, the code that figures out how to indent each line should say, if the block-comment depth is greater than zero, return `CodeMirror.Pass` as the new indent.  Apparently this magic value tells CM to abandon its attempt to indent the current line.

I've almost gotten this worked out for emacs.  It turns out everything about indentation for block comments is easier with support for nesting block comments (because then the nesting depth is an int, just like all the other nestings I track), and I've just about gotten that worked out too.  I'll try to figure this out for CM soon.

**Comment by jpolitz** [comment]
What you described with `CodeMirror.Pass` is exactly what I had in mind.  Edited the above comment.

**Comment by jpolitz** [comment]
This has been fixed and pushed, thanks @blerner
