### ISSUE TITLE
Object Expressions - string fields

### ISSUE THREAD

**Issue by justinpombrio** [brownplt/pyret-lang#434]
According to the documentation (2.1.6.6) the fields in an object expression should be names. But for some reason string literals are currently allowed, so that the following does not raise a syntax error:
    `{"x x": 3}`
I don't know of any way to *access* this field, making this a rather funny object.

**Comment by blerner** [comment]
Check the tests for the command line library: I think this will break some
of the tests, but I don't have the code in front of me right now...

**Comment by jpolitz** [comment]
It breaks the parse of the command line library, whose tests are evidently never run by anything automated.

The tests are way out of date; the implementation of the CLL was changed to string-dicts, but the tests didn't get updated, so they don't run, because there's no object->dictionary conversion.

Frustrating.

**Comment by jpolitz** [comment]
Frustration fixed over in https://github.com/brownplt/pyret-lang/pull/436
