### ISSUE TITLE
Incorrect scoping for assignments, methods, and method-fields

### ISSUE THREAD

**Issue by justinpombrio** [brownplt/pyret-lang#441]
There are a few scoping problems in `resolve-names`.

In assignments, if the identifier being assigned to is not found in the environment, an exception should be raised. Instead it is caught internally later, giving a bad error message:

    list := 3
    # raises "bad-assignment(list, [...])"

In methods and method fields, the arguments are in scope both in the annotation and in their `where` block, but should not be. This isn't observable for the `where` block because it's a well-formedness error for them to have one, but it is observable for their annotations:

    data Foo: sharing: f(self, arg) -> Any%(arg): self; end
    method(self, arg) -> Any%(arg): "no-good" end
    # both raise: "No cases matched in the cases expression at src/arr/compiler/anf-loop-compiler.arr: [...]"

Looking at the source cod in resolve-scope.arr, I would expect a similar problem for `for` and `cases`: it *appears* that cases arguments are in scope in its annotation, as are previous for-loop values in a for-loop value annotation. But in testing they behave correctly:

    for fold(sum from 0, elem :: Any%(sum) from empty):
      sum + elem
    end
    # Gives the correct error message (sum is unbound)

**Comment by blerner** [comment]
The `list` case isn't quite that simple: `list` is indeed defined as that's what makes `[list: ...]` work.  (Try your example again as `link := 3`, and you'll get the same error.)  The actual problem here is that `bad-assignment` exceptions aren't rendered properly.  (For example, `x = 5    x := 3` will generate the same poorly-rendered error.)

The "no cases matched" is definitely a problem...

**Comment by jpolitz** [comment]
Thanks, fixed by 9bc4fd68094eed23c65e3d93aa6661b1844f8885.  The for loop case might look wrong because it's using a fold.  However, the thing that matters is which visitor is passed to each term's visit method, which isn't always the currently-accumulated environment.  Since for loops don't have type parameters (though given what we know about Typed Racket, they may some day), they just use an unaltered visitor for the annotations (e.g. `ann.visit(self)`).

methods needed to mirror functions, and use an environment with just the type parameters, but not the arguments, which is in scope as `with-params` in that code; it was just wrong to pass in a visitor with a further-accumulated environment.

**Comment by justinpombrio** [comment]
I'm confused. It sounds like you're saying the `for` loop annotation visit
should read:

    ann.visit(self)

which is what I would *expect* too. But instead it says:

    bind.ann.visit(self.{env: acc.env})
<https://github.com/brownplt/pyret-lang/blob/9bc4fd68094eed23c65e3d93aa6661b1844f8885/src/arr/compiler/resolve-scope.arr#L661>

which seems to pass in the partially accumulated environment. Am I missing
something?

Justin
