### ISSUE TITLE
Pasting text with curly quotes into the editor

### ISSUE THREAD

**Issue by schanzer** [brownplt/pyret-lang#443]
Common use-case:
1) A teacher uses Word or some other godforsaken thing to write code in front of their students, taking advantage of color, italic and bold formatting to highlight various parts of the code.
2) Word dutifully converts quotes into curly ones
3) They then copy the code into an editor, and click run

We should handle this gracefully.

**Comment by jpolitz** [comment]
Thanks for reminding us of this!  Options I see:

1. Just turn curlies into regular quotes on each paste event (breaks long string literal pasting, but probably most straightforward)
2. Actually parse curly quotes as legal string-literal delimiters
3. Try to detect if the paste is inside ``` .... ``` and don't convert if it is

I think, in the spirit of simplicity, we should go with #1.  #2 is actually kind of cute, but I have a feeling it won't end well for some reason.

**Comment by blerner** [comment]
*Please* let's never do number 2: then you'll wind up with stupid pasting problems where we have to recognize the actual quote characters, and then &rdquo; and &rsquo; that get extra-HTML-escaped for some stupid reason, and ... 

Option 1 seems sane enough.  Option 3 is hard because of parity of quotes (you'd have to actually lex the file to see whether it's considered inside a string or not).  

On the other hand, doing this implies there's no way to input a curly-quote into a Pyret file from CPO.  That may be a problem in its own right.  

How inconvenient would it be to have the teacher paste text and *not* automagically convert quotes, and then, when pressing run results in a lexing error, we pop up a dialog offering to auto-correct all quotes in the document?  (Even suggesting this, I feel like it's a bit clunky, but I also don't see a way around being able to manipulate curly-quotes in Pyret files otherwise.)

**Comment by jpolitz** [comment]
Other ideas:

- Pop up a notification that it happened, like we do when saving, that says "Pyret converted curly quotes to straight quotes, Ok/Undo"
- Never let them get inserted by paste, and have a menu option under More... for inserting curly quotes (potentially with a shortcut like Ctrl-" and Ctrl-')

**Comment by schanzer** [comment]
I really like the "Pyret converted curly quotes to straight quotes, Ok/Undo" option!

**Comment by justinpombrio** [comment]
While I generally dislike pop-ups, I think this is the perfect place for
one. It's best to notify someone when you've secretly mucked with their
input, and the circumstance under which it occurs is both rare and
avoidable.

**Comment by jpolitz** [comment]
And like magic, @elibwhite delivers.  I pushed this out to /neweditor today, try going to

code.pyret.org/neweditor

and pasting curly quotes.

**Comment by schanzer** [comment]
This. Is. Awesome.
