### ISSUE TITLE
provide-types doesn't have "end"?

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#449]
The syntax for provide is

    provide {
        ...
    } end

but for provide-types, it is

    provide-types {
        ...
    }

Why doesn't it have "end"? (Or, the other way is that, why provide needs an end?)

**Comment by jpolitz** [comment]
Provide actually allows (though this will go away) any expression to be provided, not just a statically-known dictionary of values.  The `end` was necessary with that design to make it unambiguous.

Since provide-types has to be a record annotation literal, there's no such constraint.

The syntax of provide will change at some point to be less expression-based, which is part of some ongoing modules work.
