### ISSUE TITLE
indentation for "data" on neweditor is wrong

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#453]
data Test:
        | test(a) # this is incorrect
    end
    
    fun testfun():
      nothing # this is correct
    end

It is supposed to have only 2 spaces, not 4.

**Comment by sorawee** [comment]
Oh wait, this happens with normal editor on CPO as well...

**Comment by blerner** [comment]
It shouldn't, and I don't think it used to.  I'll fix it.

**Comment by blerner** [comment]
Ok, this was an easy fix.  I'd refactored the regex that looked for leading pipes, but when I rewrote it, I used emacs-lisp syntax, rather than JS.  Unsurprisingly, that won't work...

This has been fixed by https://github.com/jpolitz/CodeMirror/commit/3ea78853ce638a29f5dfbdcc47b2167cf9617dc9; once that's live, this issue can be closed.
