### ISSUE TITLE
Roughnums: 125^1/3

### ISSUE THREAD

**Issue by schanzer** [brownplt/pyret-lang#454]
125 to the power of 1/3 is 5. Pyret (with roughnums) does not match this behavior:
> num-expt(125, 1/3)
~4.999999999999999

**Comment by ds26gte** [comment]
Pyret special-cases num-sqrt to return an exact if it can verify that the argument is an exact square. The verification is done using a Newton-Raphson iteration. 

I've extended this verification for rational num-expt when the denominator of the power is <= 8. (Roughnum branch 0c2cd22.)

I fear that making it completely general will be expensive. The N-R verification process gets (exponentially) more expensive with the size of the denominator.  However, if it can be assumed that num-expt with rational arguments is typically called deliberately with full foreknowledge of what it entails, a general solution may be the way to go.

**Comment by schanzer** [comment]
The use-cases I'm concerned about are only those we're likely to see in a high school math class. Cubed roots are pretty much it, so going up to the 8th root is more than sufficient. Thanks for snagging this so quickly!

**Comment by ds26gte** [comment]
BTW, this opens up a strange boundary case: Raising a negative number to a rational power with an *odd* denominator less than 8 will produce a negative real result in my check-in. However, raising the same negative number to a rational power with an odd denominator *greater* than 8 will produce "roughnum overflow" (not a great error message here). This is because we're handing off to JavaScript's Math.pow, and the latter always fails on negative bases and nonintegral powers, even when there is a real root possible. Try num-expt(-125, 1/7) and num-expt(-125, 1/9) on https://rough-pyret.herokuapp.com/editor.

It is possible to correct for this by doing a check for the oddness of a rational power's denominator, but maybe this is too subtle to care about.  It might indeed seem strange to have num-expt(-1, 65536/65537) succeed while num-expt(-1, 65536/65538) fails.

BTW, in this situation, most other languages either flat-out error (JavaScript, Julia) or return the *first complex root* in preference to the real root (Racket, SBCL).

**Comment by schanzer** [comment]
For the Bootstrap use-case this is pretty minor, so I'm comfortable punting. However, that error message should definitely be improved.

**Comment by ds26gte** [comment]
Error message improved. E.g., for num-expt(-1, 1/9)

Error: expt: raising negative number -1 to nonintegral power 1/9

**Comment by schanzer** [comment]
Works for me.
