### ISSUE TITLE
Within incorrect for very small Roughnums

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#457]
Both kinds of within are incorrect for very small numbers.  Is there an easy way to make these correct, turn them into errors, or otherwise handle them?  Is there a precise definition of in what ranges `within` starts to lie that we could document?  I suspect because floating-point, the best solution is to document it, but I'm not sure how to do that accurately.

```
within-abs(~5e-324)(~12e-324, ~5e-324) is true
# (should be false)

within-abs(~5e-324)(~12e-324, ~5e-324) is true
# (should be false)
```

**Comment by ds26gte** [comment]
~12e-324 is read as ~1e-323, which is indeed within 5e-324 of 5e-324. But I see your point. I have added some checks to throw an exception when numbers are too small to compare.

(It is not possible to get false without violence to our conception of roughnum, because ~12e-324 is beyond our roughnum range.)

**Comment by jpolitz** [comment]
The same issue shows up for larger numbers, though, too (I think documentation is going to be our only hope here, I just want to know what to say):

```
within-abs(~10e-324)(~30e-324, ~10e-324) # reports true, should be false
within-abs(~1e-322)(~2.5e-322, ~1e-322) # reports true, should be false
```

**Comment by blerner** [comment]
Could we have a well-formedness error for roughnum literals that we know 
for certain we can't express without under/overflow?  Or are all the 
literals below legitimately expressible?

**Comment by jpolitz** [comment]
I don't think so, because floating point arithmetic will end up giving results like `-5e-234` (which I picked because it's `Number.MIN_VALUE`) anyway, and we want to be able to print and use those numbers.

The last case I just added is troubling, because `e-10` isn't exactly a "very small" range.

**Comment by blerner** [comment]
That's weird, because in both Fx and Chrome, `2.5e-10 - 1e-10 < 1e-10` returns false...  Seems to me there's a bug here for that, not an intrinsic problem (yet) with roughnums...

**Comment by ds26gte** [comment]
Last three were indeed my error, not JavaScript's. I had rewritten a subroutine for converting non-rough literals to rationals and then unaccountably neglected to actually use it for Roughnum's toRational. Fixed in rough-pyret.herokuapp.com now.

**Comment by ds26gte** [comment]
The first is fixed too, and has to do with JavaScript's acceptance of nonzero numerals of magnitude *somewhat* less than Number.MIN_VALUE and automatically coercing them to MIN_VALUE rather than 0.

Although the within's act better now in the presence of these numbers, the literals themselves are read in ways that can be confusing to the innocent. For instance, num-print(~24704e-328) prints ~5e-324, whereas num-print(~24703e-328) prints ~0 (underflow). Do we want the former to print as ~0 too? -- it will add inefficiency to the reading of *every* roughnum literal.

**Comment by jpolitz** [comment]
It seems reasonable to disallow really small roughnum numerals that flat out can't be represented.  Since ~24704e-328 will never be printed, we don't need to be able to parse it.  That gets at Ben's suggestion, which for truly unrepresentable things seems like a good option.

**Comment by ds26gte** [comment]
~24704e-328 is also ~2.4704e-324, so it's pretty close to the magnitude of roughnums we do want to parse.  One could do some regexp inspection of the roughnum (number of digits before decimal point + exponent) to disallow truly unprintable roughnums. But the edge cases will get us every time.

One approach is to disallow Number.MIN_VALUE as a Pyret roughnum. When parsing a roughnum literal, if it's found to be MIN_VALUE, we know it must be either actually MIN_VALUE or something slightly smaller that JS coerced to MIN_VALUE. We could throw it out completely (either equate it to 0 or throw an underflow exception). This avoids having to do ad-hoc checking of the literal string. Of course, this means that the Pyret roughnum range is a very small ε smaller than JS's double range. We can live with that, can't we?

**Comment by jpolitz** [comment]
Actually, there's a good question of why we aren't keeping around more information about the representation of the number as-parsed in the AST.

If this issue really is only at the very boundary, it's less of a problem, because we can just defer to to the floating point spec.  If a student is intrepid enough to get bit by this, they're plumbing the edges of the system, and maybe we can just say that.

Here's a different question:  Are there a pair of expressions that within-abs and within-rel are equivalent to?  Put another way, can they be implemented in Pyret?  Because then describing them is very easy, we just say:

```
within-abs(tol)(l, r)
```

is equivalent to

```
num-abs(num-exact(l) - num-exact(r)) <= num-exact(tol)
```

(I think that's true, and I think it's a fine definition).  Then anything that happens can be explained in terms of literals and more explicable operations.

**Comment by ds26gte** [comment]
That equivalence is fine except that it never raises an exception.  

The exception should occur (*in my opinion*, but I'm open to correction by those whose number insights are deeper) when

tol is ~MIN_VALUE, and 
l or r is rough, and
num-abs(l - r) is MIN_VALUE

because in such cases, num-abs(l - r) could really be almost twice MIN_VALUE. (To put it colloquially, for large values of 3 (e.g., 3.49) and small values of 2 (e.g., 1.51), their difference is close to 2 rather than 1.)

(Why raise an exception at all? Because we represent roughnums in Pyret not as the integral multiples of MIN_VALUE that they are, but as precise-looking rational numbers prefixed with the sigil ~.  This means that for small roughnums, the notation tricks us into believing there is a precision that is not actually there (e.g., there are tons of wildly different — and quite short! — literals representing the same roughnum at this magnitude). In order not to shatter this illusion, we'll just throw an exception instead of stating an answer that seems visually wrong.)
