### ISSUE TITLE
New editor has no link to "My Programs" in header

### ISSUE THREAD

**Issue by rrshaban** [brownplt/pyret-lang#459]
There's a "View Files in Drive," but no link to https://code.pyret.org/my-programs

**Comment by rrshaban** [comment]
It seems that this was [intentional](https://groups.google.com/forum/#!msg/pyret-discuss/hbKWv9gSs8M/IttdqrCP6C8J), but for me this implementation is still broken. 

tl;dr: navigating the Google Drive interface to actually open a file in Pyret takes many clicks

The View Files in Drive link points to https://drive.google.com/folderview?id=[ID]&usp=drivesdk&ddrp=1#, which does not actually give me any way to actually open the files in code.pyret (on Chrome, OSX). 

![screen shot 2015-03-20 at 12 08 28 am](https://cloud.githubusercontent.com/assets/9829375/6745898/5596897c-ce95-11e4-807d-6d2c09b6ac26.png)

![screen shot 2015-03-20 at 12 09 30 am](https://cloud.githubusercontent.com/assets/9829375/6745909/712fde40-ce95-11e4-8ed9-28b60fde7c97.png)

If I click on any file, it gives me a preview and I then have to click pop-out, which leads me to a gDrive interface of the file, from which I can then click Open With > Pyret. 

Alternatively, I can click "Open in Drive" at the top right of the folder interface to get to my gDrive code.pyret.org directory (https://drive.google.com/drive/u/0/#folders/[hash]). From there, I can right-click > Open With > Pyret. 

Either way, that's a lot of clicks, and far more of a hassle for the end-user than /my-programs. Maybe the issue is how gDrive is integrated (linked to) from Pyret -- I'm not familiar with the gDrive API or what it allows.

**Comment by jpolitz** [comment]
The extra click is are annoying, I'm not sure of a way around it just yet.

(Aside: Not sure if you know this, but in Drive -> Gear Menu (top right) -> Settings -> Manage Apps, you can make Pyret be the default for files it can open, and then you should be able to double-click files to open them.  You still have to click through to the Drive page.)

FWIW, I just keep the Drive folder for Pyret handy and open things from Drive all the time, rather than using CPO for it anymore.

It's not clear to me why the GDrive API reports the link

https://docs.google.com/folderview?id=0B32bNEogmncObHNhLU9qZFJ4M28&usp=drivesdk

Rather than

https://drive.google.com/drive/u/0/#folders/0B32bNEogmncObHNhLU9qZFJ4M28

CPO could construct the second link from the folder's ID, but it's likely not future-proof since it isn't part of the API.  It might also be a new drive/old drive difference.

**Comment by schanzer** [comment]
Is this still relevant, now that we have the picker UI?

**Comment by jpolitz** [comment]
Actually, we probably should put the picker UI "Open" option in place of "My Programs" on the home page, where selection of a file just takes you to the editor with that file open.

I think the same complains about "My Programs" leading to drive will persist here.

**Comment by schanzer** [comment]
@jpolitz , CPO now behaves in the way you proposed. OK to close?
