### ISSUE TITLE
unexpected error when defining error

### ISSUE THREAD

**Issue by fgoodman** [brownplt/pyret-lang#461]
The program `error = 1` gives the following error:

```
It looks like you defined the name error twice, at


definitions: line 1, column 0
definitions: line 1, column 0
You need to pick a new name for one of them
```

**Comment by blerner** [comment]
Fun times :)  This is because "error" is the name of a builtin module.  So is "lists", "option", "sets", and "arrays" -- if you try any of those, you'll get an analogous error.

The error message is lousy, but in hindsight is understandable.  @jpolitz, do we want and/or need to expose these module names as identifiers anywhere?  Or could we just import their fields, and make the modules be somewhat more anonymous?

**Comment by Emmay** [comment]
The error message for the code above now reads: "The declaration of the identifier named error shadows a previous declaration of an identifier also named error". Is this sufficient to close the issue?

**Comment by blerner** [comment]
Not really, because this behavior is still weird.  It's also inconsistent between the REPL and the definitions area: if you try `error = 1` as a program, you get the error-feedback above, but if you try it in the REPL, it works.  Moreover, if you try `error` as a program, you get a gigantic object with a bunch of methods, but if you then try `error` in the REPL, you get unbound-identifier feedback.

**Comment by blerner** [comment]
This seems to be fixed on the modules branch

**Comment by schanzer** [comment]
@blerner now that modules has landed, can we close?

**Comment by schanzer** [comment]
@blerner ping?
