### ISSUE TITLE
saving file feedback

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#465]
I clicked on Save, and nothing seemed to happen. Then I clicked on run (Ctrl + Enter) and I got a "saved file..." message in the REPL. Every time I ran I got that message. But just clicking on Save did nothing.
1. Make clicking on Save print something, and maybe also change the look of the Save button until the next edit.
2. Perhaps remove the message on every run, or make clearer that it's a backup save. Personally, I find it a bit annoying to be printed at all.

**Comment by elibwhite** [comment]
I get the save message both by clicking on Save and by running. I'm not sure why that wouldn't happen for you. What browser?

Since save on run and save on clicking save do the same thing, I think calling it a backup save would be confusing. I also think it is helpful to see the message in both cases. Users may not know about the save on run otherwise, and even if they do, it is always helpful to have visual confirmation that it saved.

I do see how it could be annoying. Perhaps just changing the animation would help? Right now it has a slow fade out, which is a bit distracting and not very pleasing.

**Comment by schanzer** [comment]
"Save" behavior is now consistent. OK to close?

**Comment by Emmay** [comment]
Echoing that the save behavior is consistent when clicking save and running the program. Can this be closed?

**Comment by schanzer** [comment]
@shriram ping?
