### ISSUE TITLE
Different color literals in output syntax

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#476]
Some notes from Emu:

String and Number literals are both styled with "color: #164". They should be colored differently. Booleans are given "cm-variable", and are colored #111.

In WeScheme, we color literals as follows: Number - blue
String - green
Boolean - darkred
Comment - orange

(I'm not suggesting we copy those colors, just giving you an example of how different the colors are. Obviously, though, if you like any of these, it certainly makes the WeScheme transition easier).

Think whiteboard colors: red, blue, green, purple, black are common

**Comment by schanzer** [comment]
Don't forget that these should (try to) be visually distinct even on a washed out projector screen. ;)

**Comment by blerner** [comment]
So you're saying you want grey, beige, ecru and tan, right?  All on a sand background color?

**Comment by blerner** [comment]
I think we can use CSS to blur the text, too, just for that *extra* bit of legibility...

**Comment by schanzer** [comment]
* {font-family: "Apple Chancery";}

**Comment by blerner** [comment]
Less whimsically: I commented also on the Trello card, that we no longer are styling strings and numbers as "cm-literal", and true/false as "cm-variable".  Instead, we have `cm-number`, `cm-string`, and `cm-constant` (the last one is there in case we have other word-like constants one day, but it's easy to change if needed), which can all be styled independently now.  We also have `cm-comment` for comments, and `cm-unterminated-string` for strings that are missing a closing quote.

If we're allowing ourselves the luxury of choosing *fonts*, now...well I'd have to say that unterminated strings should be in Comic Sans, since the programmer ought to know better...  Numbers in Chancery, sure; strings in a tasteful and elegant Brioso, and comments in Zapfino --- because you definitely want people to look at your code, not read it.  ;-)

**Comment by schanzer** [comment]
Ooooh....your parser can style unterminated strings? You just made my freaking day!
As for colors -- right now the green you use for strings and numbers is very similar, and is also dark enough that it looks like cm-variable on a crappy screen. These should definitely have more colorspace between them.

Why not use a lighter green? Why not make use of purple and orange?

**Comment by blerner** [comment]
Updated: "cm-constant" is now "cm-boolean".

**Comment by schanzer** [comment]
Update: I opened a new issue in CPO, since now I realize where editor decisions should be logged.

**Comment by blerner** [comment]
This is now https://github.com/brownplt/code.pyret.org/issues/31, so closing here.
