### ISSUE TITLE
bad error message

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#477]
```
data Auto:
    Auto(x)
end
```
1. This prints two errors.
2. The real problem is that `Auto` is defined twice. However, this is the _second_ error. The first error is about `is-Auto`, which is the thing students are least likely to encounter.
3. Can we have a better error that just says "you've got the same name for a type and its constructor"?

**Comment by blerner** [comment]
I thought we had that, actually...  If not, it should certainly be easy 
to add as a well-formedness check.  @jpolitz, looks like it's a 1-line 
fix to well-formed.arr, line 517, to add the datatype name to the list 
being checked.  But we'll also need to check for the "is-" prefixed 
predicate forms, and we'll also need to plumb location info into the 
s-data constructor so that we can report an error location for the name 
of the data type.
