### ISSUE TITLE
"Tried to look up field make on a non-object in the lookup expression"

### ISSUE THREAD

**Issue by rrshaban** [brownplt/pyret-lang#478]
I'm getting a pretty unhelpful error:

![screen shot 2015-03-28 at 9 10 26 pm](https://cloud.githubusercontent.com/assets/9829375/6883673/f9dbea22-d58e-11e4-9d11-5ab2e50bc46a.png)

The code at the top of the stack trace is as follows:
```
new-subst = subst-help(left, right, subst + [link: first])
```
where first is previously defined as:
```
cases(List<Constraint>) cons:
    | empty => subst
    | link(first, rest) =>
```

I thought it might be an issue with using the name first in the list, so I tried subbing `cons.first` but that didn't work either, nor is manually building that item in the list. Basically, I have no idea what the error message is trying to tell me.

**Comment by blerner** [comment]
In this case, you have a typo in your code: `[link: ...]` should be `[list: ...]`.  Internally to Pyret, the translation of constructor syntax (the `[<constructor name>: args...]` pattern) assumes that the constructor is an object, and tries to find a field named `make` on it to invoke the constructor.  That's why you're seeing "Tried to look up field `make` on a non-object ...", and the non-object that you got was the `link` function.

This is indeed a rather unhelpful message :-\

**Comment by rrshaban** [comment]
That makes sense -- I ended up fixing it by switching to the more elegant `link(first, subst)`, but changing the brackets to `list` does fix the error.

**Comment by blerner** [comment]
That changes your semantics -- `subst + [list: first]` puts `first` at the end; `link(first, subst)` puts it at the front.  Dunno if that matters for your application, but just something to notice...

**Comment by rrshaban** [comment]
In this particular case it doesn't matter, but thanks for pointing it out!

**Comment by jpolitz** [comment]
It's also problematic that this lists a builtin location as the source of the error.  I would expect the generated `link.make` expression to have the same source location as `link` itself, and highlight `link`, but somehow that isn't happening.  It looks like the right location is attached in desugar, though, (https://github.com/brownplt/pyret-lang/blob/ad3bd2ef6d92eca882366c122c3bd7a89ce610ed/src/arr/compiler/desugar.arr#L504), so I'm not sure what's up.

**Comment by blerner** [comment]
It appears to be because `[foo: ...]` gets desugared to `foo.make([raw-array: ...])`, and the `foo.make` gets turned into a call to `runtime.getColonField(foo, "make")`, and `getColonField` hallucinates a source location of `[runtime]`.  This is an interesting regression: at some point, @jpolitz optimized a better calling sequence for `obj.meth(args)`, so using `getColonField` makes sense so we avoid currying the methods over their receivers.  But the desugaring of constructors also triggers this pattern, so we have `getColonField` used even for constructors, which are lambdas and not methods.

I think this solution here is to create a `getColonFieldLoc` primitive, so that we don't hallucinate the wrong locations.  @jpolitz, agreed?  (Note that this fix is orthogonal to changing `l` to `constructor.l` in the desugarer; I think that's probably a fine suggestion too.)

**Comment by blerner** [comment]
Or, really, just add a location parameter to `getColonField`, since there really should always be one...
