### ISSUE TITLE
sceneImages should take an optional color argument

### ISSUE THREAD

**Issue by schanzer** [brownplt/pyret-lang#488]
If we're still trying to (loosely) conform to the Racket images API, then the following code should generate a blue scene: 

import image as I
I.empty-scene(200,300,"blue")

This is only going to become relevant for the BSL compiler, which is expecting this behavior to be supported.

**Comment by blerner** [comment]
Since Pyret doesn't (and isn't likely to ever) support optional arguments, we could do this with a second API, `empty-scene-colored` or something.  Or, if this is just a compiled-BSL issue, could you translate the BSL `(empty-scene width height color)` to the Pyret `I.place-image(I.rectangle(width, height, "solid", color), width / 2, height / 2, I.empty-scene(width, height))`?

**Comment by schanzer** [comment]
ACK. I'll translate this on my end.
