### ISSUE TITLE
Some questions on language style

### ISSUE THREAD

**Issue by Heimdell** [brownplt/pyret-lang#498]
Pardon me, I weren't able to find a developers blog of the language to write there. However, the problems described are threating me.

Lets take this code as starting point:
https://code.pyret.org/editor#program=0B5uFMkgqVKUOWjhYSzhPRThGdzg

it declares a "fixpoint type" and a destructor `cata` which uses existing mapping traversal and "one-level fold" to fold the whole fixpointed structure onto a target type. (Just like this haskell package does: https://hackage.haskell.org/package/data-fix-0.0.1/docs/Data-Fix.html).

1) Those `lam(f): lam(l): ...` are making a huge mess. Does pyret have any means to express curried lambdas nicely? Even `lam(f)(l): ...` is rejected.
2) `lam(l): cases(AList) l:` - the `l` is bound once in a case-splitter. Is there any `lambda-case` (like OCaml `function A of ... -> ... | B of ...` or haskell's LambdaCase `\case A x -> ... | B x -> ...` ?
3) The compiler starts yelling when I put a space after a `lam`, `fun` or even between bracets in curried application (`f(x) (y)`). Seems like the space there wouldn't make compiler being confused. What is the reason behind this?
4) The `Fix` type expects its argument to have kind `Type -> Type`, but there is no way to produce a `Cons`-chain, polymorphic on its `h`ead part, of that kind - the only way is make its kind `(Type, Type) -> Type`. I can (and did) disable typechecking, but its not a solution. Will the language support curried type functions? Like, `AList<A><Self>`.
5) Seems like there is no way to make a type synonym w/o making a new type wrapper, which leads to a `unFoo.unBar.unQuix` mess in the code (where those "synonymized objects are unpacked". Do you plan adding such a capability?

**Comment by jpolitz** [comment]
Thanks for your questions!

Can you provide a "Share..." link?  The link you provided is owned and visible only by you.

1.  Happy to hear suggestions for this, though I don't see it as a major priority and might not happen.  Curried functions aren't a critical use case for Pyret, so we haven't spent a lot of time trying to get a clean syntax for them, and we're inclined to save our syntactic complexity budget for other things.

2.  Ditto (1)

3.  In the function application you show, this has a reason.  Since Pyret doesn't use newlines, only whitespace, to break up expressions in a block, these two blocks both parse as two sequential expressions:

```
f(x) (y)
```

```
f(x)
(y)
```

We want to discourage the first case because it's a common typo of function application in the whitespace-separated exception world, and also stylistically we prefer expressions to each have their own line, the compiler complains that there are two expressions on the same line.  Along with this, function applications require that the function expression be immediately followed by the open parentheses.  It's a style choice with enforcement, to avoid significant newlines in the grammar.

I think I need to see the code to understand (4) and (5) better.

**Comment by Heimdell** [comment]
https://code.pyret.org/editor#share=0B5uFMkgqVKUOVHJBb3ByQTU1ZnM&v=v0.5r852
Here you are.

**Comment by Heimdell** [comment]
Also, does the language support some kind of typecase? It could be useful to implement some `curry` function without need of passing number of arguments.

**Comment by Heimdell** [comment]
And also, 
6) The redefinition problem - if somewhere in dependencies the name `foo` is used I cannot declare a _local_ name `foo` to hide the global one. I understand that this mechanism is for protecting from redeclaration, but _local_ name shouldn't hurt, especially if the recommendation "one function fits one screen" is fulfilled. In the code, I had to rename `map` -> `mapper` and `fold` -> `folder` to circumvent this limitation.

Maybe, reduce this limitation to warning for the local names? In haskell, for instance, declaring same name in two different places is not an error, but will cause ambiguility error on use site. However, the compiler itself tells you a solution - prefix the name with the namespace.

The `map` in haskell is implicitly imported from `Prelude` module and is accessible in `Prelude.map` form in case of redeclaration. However, here in pyret we can't syntaxically distinguish qualification and field access: `a.b` maybe the field `b` of object `a` or object `b` from namespace `a`.

7) Reflection. What about adding a way (some console?) to browse the contents (type/kind signatures, I mean) of the namespace? It shouldn't hurt. When I 'm working in haskell or ruby interpreter, I often use "`:bro`wse module" capabilities of first one and "`object.methods.sort`" of latter one.

**Comment by jpolitz** [comment]
I've moved the discussion to pyret-discuss (https://groups.google.com/forum/#!topic/pyret-discuss/n4X5xcK3kWc).  I think these would be interesting conversations to have on the list, and aren't necessarily issues yet, and if we decide they are, they should be moved to separable tasks.
