### ISSUE TITLE
Functions defined below code that uses them are not recognized

### ISSUE THREAD

**Issue by Emmay** [brownplt/pyret-lang#518]
See this file: https://code.pyret.org/editor#share=0B9rKDmABYlJVUzBXcUFPUFhUOHM&v=v0.5r1195

This worked a few weeks ago, but now produces errors. I was able to run the game by moving the is-off- functions above the functions that use them (update-world), but our curriculum has kids defining their helper functions towards the bottom of the file, then used in the main functions towards the top.

Is this a permanent/intentional change? It would require a large re-organization of our code to always make sure functions are defined before functions that use them.

**Comment by jpolitz** [comment]
I expect that file to work.  I'll see what's up.

**Comment by jpolitz** [comment]
I'll push out the fix for this shortly.  I still need to investigate what changed here; I think that check blocks were kept around longer in the compiler because of some of the type checking merges, and this caused their interaction with scope to change.  The commit above fixes the issue for now, though.

Thanks for reporting!

**Comment by jpolitz** [comment]
This works now, if you want to verify the version is bumped so it's at: 

https://code.pyret.org/editor#share=0B9rKDmABYlJVUzBXcUFPUFhUOHM&v=v0.5r1198
