### ISSUE TITLE
printing UNKNOWN VALUE! leads to infinite loop

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#521]
In standalone, printing the following JS values leads to an infinite loop:
- `undefined`
- any JS object (`{x: 1}`)
- any JS function (`function(){}`)

I do not expect these value to be printed correctly, but I also do not expect an infinite loop to happen.

__Output example__

    [Function]
    UNKNOWN VALUE!
    [Function]
    UNKNOWN VALUE!
    [Function]
    UNKNOWN VALUE!
    [Function]
    UNKNOWN VALUE!
    ...

or

    { x: 1, y: 2 }
    UNKNOWN VALUE!
    { x: 1, y: 2 }
    UNKNOWN VALUE!
    { x: 1, y: 2 }
    UNKNOWN VALUE!
    { x: 1, y: 2 }
    UNKNOWN VALUE!
    ...

**Comment by blerner** [comment]
This is a leftover of a deliberate choice when I revised the printing algorithm so we could have rich output renderings: printing values is only guaranteed to work for *Pyret* values, and the values you've described above are not Pyret values, so the infinite loop was there to ensure that I noticed if I'd screwed up the refactoring to the point that I leaked a raw JS value in where only Pyret values belonged.

It's an easy fix to eliminate this loop...but the bigger question is, how did you manage to trigger this behavior?  Was there a Pyret program that you wrote that leaked these values through?  Or were you directly calling the printing algorithm?

**Comment by jpolitz** [comment]
This seems like a weird method of noticing this -- if there's an infinite loop in the browser, the tab will crash with no chance to see the console output and answer this question...

**Comment by blerner** [comment]
You make the assumption that I was initially developing for the browser --- for something as core as the printing algorithm, cmdline had to happen first :)  And at the time, I needed something visually arresting that didn't look like our normal JS-error-spewed-to-stderr behavior, because I was trying to fix how we surfaced JS errors anyway!

In any case, it's a one-line fix: replace the two `console.log` commands with a call to `finishVal("UNKNOWN VALUE!")`.  But my other question remains: what valid Pyret program triggered this behavior?  That's a far more worrying problem to solve!

**Comment by jpolitz** [comment]
This was the keystone of the rich value rendering algorithm. How is that
not for the browser? I ran into this today, too, while testing something in
browser (my fault for returning a js and not a Pyret value somewhere) and
if this issue hadn't come up at the same time I probably would have been
stuck for a while finding the two-line fix, since I thought the loop was my
fault, not just the failure to wrap a return value.

I think infinite loops as error conditions shouldn't be something we
casually leave in.

**Comment by blerner** [comment]
I'm not disagreeing that it needs to be fixed; I just forgot that it was there.  This one's a very tricky error to report though: it's an Internal Compiler Error, and since printing values is part of the process of reporting all errors, it has to be avoidable enough that we could report the error...

Regardless -- this algorithm couldn't have been developed for the browser *first*; it had to be developed at the command line to ensure the compiler could still compile itself...

**Comment by blerner** [comment]
Was this meant to be fixed by https://github.com/brownplt/pyret-lang/blob/b0d31777cf3aa2e4725d5a3e74020eb3c4c5f9fc/src/js/base/runtime-anf.js#L1339?  Or do you want a different solution that returns "<error rendering value, details logged to console>" or some such?

**Comment by blerner** [comment]
Ok, I can fix this in two ways: by calling `finishVal("Unknown val!")` and logging the unknown value to the console, or by `ffi.throwInternalError("unknown val", [JSON.stringify(the value)])`.  I can't directly pass the unknown value into `throwInternalError` because rendering that error would try to print the unknown value, which was the problem in the first place...

I'm going to solve this with the first method (logging to console), and close this issue.  We can revisit it if we need more information later.
