### ISSUE TITLE
comma-separated includes

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#524]
What about allowing

```
include image, world
```

**Comment by blerner** [comment]
This is certainly convenient, and I'm not against this, but I do think that perhaps we ought to be rethinking our whole import/export syntax, since it seems to me like we're approaching Racket's level of control while trying to avoid the complexity of Racket's level of control...  Certainly [TM013](https://github.com/brownplt/pyret-lang/wiki/TM013---Exporting-types-from-modules) is getting very close from the providing side...

**Comment by schanzer** [comment]
@jpolitz @belph FWIW, this would be mildly nicer for Bootstrap, but it's not earth-changingly better. Is this something that you still want to do, and if so does the modules code make it more achievable?

**Comment by blerner** [comment]
No.  Actually doing this would probably make the grammar ambiguous (or at least nearly impossible to syntax-highlight well), so close this.
