### ISSUE TITLE
include confused?

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#541]
````
include image-structs
````
followed by
````
> red
````
gives an error, whereas
````
import image-structs as IS
````
followed by
````
>  IS.red
````
works. For other libraries (e.g., `world`), `include` does indeed splat names at the top-level…

**Comment by jpolitz** [comment]
Yeah this just doesn't work yet.  Pyret-implemented built-in modules need to have their types handwritten right now, and I didn't do it for image-structs (and a few others) yet.  I was hoping to get it working from information in the Pyret source rather than writing them out, as is done with, for example, list, but that might not happen for a bit.

**Comment by sorawee** [comment]
Similar issue:

    > import image-structs as I
    > I.red
    color(25500255)
    > import red from image-structs
    Key red not found

**Comment by schanzer** [comment]
Both @shriram and @sorawee 's examples now work on CPO. Close?
