### ISSUE TITLE
double arrow seems to require a space

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#554]
```
cases (Something) something:
  | abc =>"123"
end
```

results in an error.

Since we are okay with the below code (#372), I expect the above to work as well.

```
ask:
  |true then:1
end
```

**Comment by blerner** [comment]
We agreed a long time ago that we were going to insist on whitespace around operator-looking tokens, because the whitespace is usually needed to ensure unambiguous parsing, and it was really weird when some operators required whitespace and some didn't.  Honestly I'd rather the second example require whitespace, but we also agreed not to mandate whitespace except when it's really needed for unambiguous parsing.
