### ISSUE TITLE
shadowing function makes where/check block failed

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#562]
I guess it makes sense, except that it could cause a confusion that why shadowing could affect code above it.

```
fun test(a, b):
  a + b
where:
  test(1, 2) is 3
end

print(test(1, 2)) #=> 3

shadow test = test(_, 0)
```

results in:

```
3

Expected to get 1 argument at ...
but got these 2 arguments:
```

**Comment by jpolitz** [comment]
Thanks.  This may be an annoying fix – I don't see a way to do this without moving scope resolution to before check block desugaring.  I'm not sure what that affects.

Interesting overall that scope resolution clearly needs to be pushed as close to the beginning of desugaring as possible.  Obvious in retrospect (since we have all of @justinpombrio's research to tell us we'll make mistakes otherwise), but still interesting.

**Comment by schanzer** [comment]
@sorawee , this no longer results in an error. Not sure if that means the issue is fixed, but worth a ping.

**Comment by sorawee** [comment]
@schanzer when I posted this, I meant it results in an error in testing. This still happens, and I think having an error here makes sense. What I worried is just that it looks confusing.

**Comment by sorawee** [comment]
Dup of #1502
