### ISSUE TITLE
expressions in provide statement should be evaluated

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#563]
```
provide {
  foo: bar
} end
```

runs fine, although `bar` is not defined anywhere at all

**Comment by blerner** [comment]
I don't think you mean evaluated here; I think you mean scope resolution.  I suspect that running this works just fine, and winds up providing JS' `undefined` as the value of `foo`...

**Comment by jpolitz** [comment]
Sigh.  This is a repl-based error, and only happens in CPO when in the definitions window.

The issue is that CPO rewrites the provide block (effectively ignoring a block that's there) to provide all of the declared names in the file.  It does this _before_ scope checking happens, so the compiler never sees the unbound identifier, as the provide block has been replaced.

**Comment by jpolitz** [comment]
Noting that I _just_ ran into this again when testing some new module syntax and I almost reported it as a new issue.

**Comment by schanzer** [comment]
@jpolitz is this fixed in the new module syntax branch that landed?

**Comment by sorawee** [comment]
Duplicate of #1517, which is also now fixed. Closing.
