### ISSUE TITLE
There is no way to print an interactive object from the code panel

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#564]
If we enter an expression to the interactive panel (REPL), we will get a clickable object (I really like this!) which could, for example, switch from decimal representation of a roughnum to rational number representation back and forth. It is, however, impossible to do so from the code panel. If we merely print something, the result appearing on the REPL will be just a string which is unclickable.

**Comment by blerner** [comment]
There are several arguments to be made here, for and against this idea.  I'm oddly neutral on it; I'm curious what other folks think.

* Anti: "printing is inherently string-y, so this proposal makes no sense."
* Pro: "printing is inherently debug-y, so this proposal is awesome."

I think the truth is somewhere between those two extremes :)  In terms of implementations,

* We could change `print`'s behavior so that it renders rich reprs instead of using the `tostring` renderer.  This has the disadvantage that we'd need to either hardcode the existence of the `"$cpo"` renderer in Pyret itself (which I don't like, from a software-engineering stance), or replace `print` with a distinct implementation in CPO (which is better, but still not ideal).  We could also try to factor out the renderer itself; it's a pretty easy parameter to abstract away.

* We could introduce a new runtime function into the language that only works in CPO.  (BTW -- in terms of names, do people remember that we still have `display` bound as an alias to `print`, for no particularly apparent reason any more?)  This is less attractive, since the CPO-only behavior wouldn't be neatly isolated to a library (like spreadsheets or big-bang), but could be forced to work.

**Comment by sorawee** [comment]
I personally think that `print(.)` should result in String, so I second having another function to do this job. This function should exists in both CPO and Pyret core, but on CPO it can show rich repr while in Pyret core it just falls back to normal print.

**Comment by schanzer** [comment]
Isn't this was Spies are/were for? If so, do we need to maintain this issue in addition to the Spy issues?

**Comment by blerner** [comment]
No, I think not.
