### ISSUE TITLE
read-s-expression too eager

### ISSUE THREAD

**Issue by jlmayfield** [brownplt/pyret-lang#569]
While using PAPL/Pyret for a PL course we discovered that read-s-expression evaluates some of the string input. More exactly, we got this: 

    check:
        read-s-exp("2/3") is s-num(2/3)
    end

when I might expected something like this:

    check:
        read-s-exp("2/3") is s-str("2/3")
    end

**Comment by justinpombrio** [comment]
That's the expected behavior. No evaluation is taking place: in both Pyret and the s-exp library, 2/3 is a numeric literal. If you want it to be treated as a string, you have to wrap it in quotes within the string that you're passing to read-s-exp:

check:
  read-s-exp(2/3) raises "" # read-s-exp parses a string argument, and 2/3 is not a string
  read-s-exp("2/3") is s-num(2/3)
  read-s-exp("\"2/3\"") is s-str("2/3")
end

**Comment by jlmayfield** [comment]
That makes sense. I was wrongly seeing 2/3 as an invocation of the division operator and forgetting that Pyret requires the white space surrounding operators. Thanks for the quick reply.

**Comment by justinpombrio** [comment]
It is a rare feature: most languages don't feature fractions, so I can see
how that would be surprising.
