### ISSUE TITLE
`data Foo` should not provide `Foo` as a function

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#571]
Right now if I write:

    data Foo:;

I will have both `is-Foo` and `Foo`. I think that their functionalities are the same (testing whether an object is a `Foo` or not). However, `Foo` actually is a type, so probably we should not overload its meaning (even though they are in different namespaces).

**Comment by belph** [comment]
This seems very related to #494.

**Comment by schanzer** [comment]
You can no longer write `data Foo:;`, or even `data Foo: end`, so this Issue is no longer valid. However, the resulting error message is bizarre, so I'll open a different issue.

**Comment by blerner** [comment]
Nonsequitur: unless we actually decided that no data definition can have zero variants, the problem in this bug still exists (just try `data Foo: foo end` instead -- the initial example was just too minimal).

**Comment by jpolitz** [comment]
This was resolved by https://github.com/brownplt/pyret-lang/commit/1c7965f97c984b50286e5a00e656a271ecd6da35.  I really feel like there was another, nearly-identical issue related to this that was closed, but I can't find it.  But the value binding of `Foo` is gone, leaving only a type binding.  So I think this issue is truly closed.

**Comment by blerner** [comment]
That commit definitely resolves the issue originally reported here :)
