### ISSUE TITLE
roughnum parsing not like number parsing

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#600]
` .1 + .2`

"Pyret thinks your program probably has a number at interactions1: line 1, column 2; number literals in Pyret require at least one digit before the decimal point."

`~.1 + ~.2`

"Pyret didn't understand your program around interactions5: line 1, column 0"

**Comment by blerner** [comment]
@ds26gte this should be an easy fix: tweak the `badNumber` regex in the tokenizer to recognize bad roughnums too, and we'll get the same error message for both, I think.

**Comment by ds26gte** [comment]
Fixed in pyret-lang#horizon.

(While I agree the error message should be fixed (and now is), that .2 or ~.2 is considered an error at all is too zealous IMO, given the practice is well established *even in the spoken language*.)

**Comment by blerner** [comment]
It's an old point of contention.  I've argued against supporting it for lexing and parsing reasons: we haven't given up on numbered field access to tuples (e.g. aTuple.1) or other dot-number accessors, and I don't want to relinquish the syntax yet.  Also, I'm not 100% confident that the badNumber lexing works completely reliably, so I don't want to let student programs rely on syntax that I don't fully trust.  Since supporting .2 as a number is something we can easily add in the future without breaking back-compat, I'm not worried about it being missing now.  (Making ~.2 be an error is solely for consistency with non-rough-nums; it's obviously unambiguously lexable as a roughnum.)

**Comment by shriram** [comment]
I agree. While I viscerally agree w/ Dorai, Ben's argument has held sway
for a long time, for good reason. We can always change it in Dorai's
direction, but we can't go back.
