### ISSUE TITLE
speeding up sets operations

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#606]
`.union`, `.intersect`, `.difference` can be perform in linear time. This is by converting AVL Trees to sorted lists (linear) and perform the operation (like merge step in merge sort -- linear). Then, we can convert the resulting list back to a complete binary tree (linear), which is an AVL tree.

**Comment by blerner** [comment]
Ugh, some other stupid algorithmic inefficiencies make it non-linear so far: `preorder`, `inorder` and `postorder` are not linear-time operations, because they create auxiliary lists and then use linear-time `append`.  

If nothing else depends on it, I suggest we:
* rename `AVLTree`'s `fold` operation to `fold-preorder`, and define `fold-inorder` and `fold-postorder` correspondingly, then
* rewrite `preorder`, `inorder` and `postorder` to be implemented by folding `link` over the tree, instead of using `+`
* and finally rewrite `union`, `intersect` and `difference` as suggested above.

The only question is if anyone we know is using `tree-fold` as currently exported by the Sets file.  Grepping through the source doesn't show any uses at all...

**Comment by blerner** [comment]
I've cleaned up these algorithms, and added a few more folds to AVL trees.  We can probably remove any ones that aren't referenced; I included them all for consistency.  Converting a resulting linked list to a complete tree in linear time is quite a bit of a pain, but converting it to a balanced one that obeys the AVL invariant is readily doable.

**Comment by blerner** [comment]
@jpolitz this is probably ready to merge; could you look it over?
