### ISSUE TITLE
misleading highlight

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#668]
```
data Foo:
    foo()
end

foo = 3
```
The error is that `foo` is defined twice. Unfortunately, the first highlight points to the entire `Foo` definition (the data definition) rather than just the clause, so it's easy to think the problem has something to do with case-insensitivity.

Note that this problem persists in Horizon. (Horizon also still has the error that the error message prints badly, with both highlights shown on the same line with no space between them.)

**Comment by blerner** [comment]
This is a 4-character fix, I think, that I'll commit once it's finished building.  It's possible that the fix will change other errors that report srclocs of data variant definitions, but since it'll be a strictly more precise error location, I don't think it'll be a problem for anyone.  I vaguely recall that we'd *chosen* the less-precise locations for variants, so that when reporting errors from data definitions that are predefined by Pyret, we'd report the location of the entire definition, but I don't quite recall why.
