### ISSUE TITLE
Syntax error in compiled JS code

### ISSUE THREAD

**Issue by justinpombrio** [brownplt/pyret-lang#697]
I got a _Javascript_ syntax error from compiled Pyret code while adding one line to arr/trove/repl.arr, off of my "tracer" branch (which is almost identical to Horizon). Here is the change:

```
pyret-lang> git diff
diff --git a/lib/CodeMirror b/lib/CodeMirror
index a30a46a..de75cf2 160000
--- a/lib/CodeMirror
+++ b/lib/CodeMirror
@@ -1 +1 @@
-Subproject commit a30a46a2e1407b8f91e0f3f86e7faee1f9ad1be8
+Subproject commit de75cf253641166067aed35b9b6620e1ae5e2802
diff --git a/src/arr/trove/repl.arr b/src/arr/trove/repl.arr
index 1dc3e38..61c8d45 100644
--- a/src/arr/trove/repl.arr
+++ b/src/arr/trove/repl.arr
@@ -46,6 +46,7 @@ fun make-repl<a>(
   var nspace = defs-locator.get-namespace(runtime)
   var globals = defs-locator.get-globals()
   var modules = SD.make-mutable-string-dict()
+  var falso = false
   var current-type-check = false
 
   fun update-env(result, loc):
```

Here is the resulting error:
```
pyret-lang> pyret

/gpfs/main/home/justinpombrio/git/pyret-lang/node_modules/requirejs/bin/r.js:381
        throw err;
              ^
Error: Evaluating /gpfs/main/home/justinpombrio/git/pyret-lang/build/phase1/./trove/repl.js as module "trove/repl" failed with error: SyntaxError: Unexpected token :
    at Function.req.load (/gpfs/main/home/justinpombrio/git/pyret-lang/node_modules/requirejs/bin/r.js:2505:23)
    at Object.context.load (/gpfs/main/home/justinpombrio/git/pyret-lang/node_modules/requirejs/bin/r.js:1887:21)
    at Object.Module.load (/gpfs/main/home/justinpombrio/git/pyret-lang/node_modules/requirejs/bin/r.js:1068:29)
    at Object.Module.fetch (/gpfs/main/home/justinpombrio/git/pyret-lang/node_modules/requirejs/bin/r.js:1058:66)
    at Object.Module.check (/gpfs/main/home/justinpombrio/git/pyret-lang/node_modules/requirejs/bin/r.js:1088:26)
    at Object.Module.enable (/gpfs/main/home/justinpombrio/git/pyret-lang/node_modules/requirejs/bin/r.js:1391:22)
    at Object.context.enable (/gpfs/main/home/justinpombrio/git/pyret-lang/node_modules/requirejs/bin/r.js:1759:39)
    at Object.<anonymous> (/gpfs/main/home/justinpombrio/git/pyret-lang/node_modules/requirejs/bin/r.js:1376:33)
    at /gpfs/main/home/justinpombrio/git/pyret-lang/node_modules/requirejs/bin/r.js:372:23
    at each (/gpfs/main/home/justinpombrio/git/pyret-lang/node_modules/requirejs/bin/r.js:297:31)
```

And here is the compiled JS code:
```
...
case 7: var var358 = $ans225;
var modules295 = {"$var":var358};
{"$var":(false)};
var current$type$check292 = {"$var":(false)};
var update$env286 = {"$var":D};
var restart$interactions318 = {"$var":D};
var run$interaction343 = {"$var":D};
...
```

On the other hand, if I *mention* the variable:

```
var falso = false
falso
```

it compiles fine.

**Comment by blerner** [comment]
OH, I know why this is happening.  It happened to Joe and me, too, and we weren't sure why.  It's because it's a dead variable.  So in js-dag-utils, the `elim-dead-vars-jstmts` function tries to delete any `j-var` statements whose right-hand-sides are `ignorable`.  I have a very conservative heuristic for what "ignorable" means (mainly a name, a chain of field-accesses off an ignorable expression, or a call to one or two pure runtime functions).  IF the expression is ignorable, it deletes the entire statement, but if it isn't, it deletes only the variable declaration and keeps the expression in case it has side effects. The right hand side expression here is a `j-obj`, so it eliminates the variable declaration, keeps the expression, and because JS syntax is weird, a `j-obj` in statement scope is parsed as a block rather than an object, hence the syntax error.

The solution is in two parts: 1) to make objects be ignorable too, if all their field values are ignorable, and 2) to wrap them in `j-paren`s if they wind up at statement level.

**Comment by blerner** [comment]
I think (#2) should be handled in the `print-ugly-source` and `tosource` methods of `j-expr`, which are precisely where we notice that an expression has made it up to statement context.
