### ISSUE TITLE
Runtime performance regression from WeScheme

### ISSUE THREAD

**Issue by schanzer** [brownplt/pyret-lang#703]
Filed at @shriram 's request.

[This bouncing balls simulator](http://www.wescheme.org/view?publicId=5ahTMmbh0A) runs pretty slowly on WeScheme when given lots of balls, but it's even slower under [Spyret](spyret.herokuapp.com/editor). Since Spyret is just a fixed-cost translation, this suggests actual bottlenecks in the runtime.

**Comment by jpolitz** [comment]
Good benchmark to improve on, thanks.

Note for anyone trying this out yourself that to translate and run this on Spyret, I had to change characters like #\p to single-character strings like "p".

**Comment by schanzer** [comment]
@ds26gte is working hard at allowing `(require...)` to work, which includes GDrive integration that will allow us to save from within Spyret. I'll edit the Issue and add a link to a working Spyret file once that's complete.

**Comment by schanzer** [comment]
[Here's another benchmark](http://www.wescheme.org/view?publicId=2AH8qYGw38). In this one, Pyret and WeScheme perform about the same.

**Comment by jpolitz** [comment]
Thanks for sharing these.

The boids one, on Pyret in Chromium or Safari on OSX, seems to get a ton smoother once the boids get close to one another, and I don't see this happening on WeScheme.

Initially, they behave nearly identically.

I have a few conjectures:

1.  Maybe the JIT kicks in better for Pyret generated code than for WeScheme generated code
2.  Maybe something about small numbers gets optimized better, or something about Pyret vs. WeScheme's number system is kicking in when the boids are closer
3.  Maybe it's something completely unrelated to the difference between systems and specific to my machine

But seriously, after about 10 seconds, the boids start running very smoothly, even at 50 rather than 30 boids.

I've also used boids as a profiling target for pure Pyret (rather than Spyret) before, so the relevant stuff under the hood has gotten some minor attention.  On horizon, 80 boids runs pretty smoothly on my laptop, things get slower in the 100s (note, you need to type `start()` in the REPL to kick things off):

https://pyret-horizon.herokuapp.com/editor#share=0B32bNEogmncOeTFiRHJPZ1hYZ2s

This suggests that there might be some overhead in coming from Spyret itself, though there's lots of reasons it could differ (the pure Pyret version has different code that may represent a slightly different algorithm, for one obvious difference).

**Comment by jpolitz** [comment]
@awstlaur what do you think would be involved in getting the profiling/benchmarking stuff to point at these programs (or programs like them)?

Of course, all the other stuff we measure is super useful, but I be there are subtleties to the heavy use of callbacks, and interaction with canvas and the DOM, that we may care about as well.

**Comment by schanzer** [comment]
Oh wow, yeah, after 10sec the difference is pretty stark. That's got to be Crankshaft/LLVM kicking in on the Pyret side.

WeScheme's JSON-walking-interpreter is basically un-JITable, which was the primary reason that the whole approach was abandoned for Whalesong. I'm not sure which is more shocking: that the post-JIT leap is that massive, or that the un-JITed performance is as bad as WeScheme. :)

Spyret shouldn't be adding much of a runtime penalty. @ds26gte , any reason to think otherwise?

**Comment by shriram** [comment]
Just as an aside, this is one of the features of PyPy. You write your
interpreter as a regular interpreter, then add an annotation saying “this
is my main interpreter loop”, and it can JIT it. The problem is I think you
have to write a it as a _loop_; the traditional recursive function I don't
think works.

Shriram

**Comment by awstlaur** [comment]
@jpolitz As far as automated testing of programs like this that require running in the browser, I think the biggest obstacle is simply putting in the person-hours to set it up. I'm sure there is a way to make Selenium targets to do this and to just log wall-clock time. Hit me up on Slack if you want to discuss further.

**Comment by blerner** [comment]
FWIW, when I run the balls demo in Firefox, performance is great...as long as none of the balls collide.  Then if I have even just two balls, performance instantly gets horrific (~1 fps or so).  I'm wondering if perhaps the numbers implementation is to blame?  When I looked at the output, I saw fractions in there with ~30 digits in numerator and denominator, which look suspiciously inefficient to me.

**Comment by shriram** [comment]
Natural guess is that it's doing everything as exact-precision, and the
fractions just grow bigger and bigger. Not sure what collision has to do
with it, unless it has something to do with the way equality is checked and
when LCD normalization takes place. Converting to roughnums ought to show a
significant improvement: maybe @ds26gte can give it a look.

**Comment by blerner** [comment]
Collisions change up-and-down motion into motion at an angle; it guarantees trig is involved (via dot products and unit normal vectors), and therefore messy numbers...

**Comment by schanzer** [comment]
Updated Pyret benchmark link, which has been updated to use the `block:` syntax.

**Comment by schanzer** [comment]
OK to close? Not only is the performance question answered, but the coming improvements from memo-jsast make the OP's subject factually inaccurate.
