### ISSUE TITLE
Wrong srcloc

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#726]
<img width="1235" alt="screenshot 2016-05-13 12 56 43" src="https://cloud.githubusercontent.com/assets/9099577/15255496/4e2e0410-190a-11e6-87e4-7796ee4d92f3.png">

The real problem is with `lists.all` which consumes two arguments. There's nothing wrong with `free-of-universal`.

**Comment by sorawee** [comment]
Smaller program:

```
fun f(lst):
  cases (List) lst: 
    | empty => lists.all(lst)
    | link(_, r) => f(r)
  end
end
```

produces:

```
The function application expression f(r)
expects the applicant to evaluate to a function that accepts exactly the same number of arguments as are given to it.

The applicant evaluated to a function accepting exactly 2 arguments:
```

which is wrong. `f(r)` should actually be `lists.all(lst)`

**Comment by blerner** [comment]
The problem appears to be with how the error message is rendered, rather than with anything in compilation, I think.  If I call `f(empty)`, it'll blame the call to `f(empty)`, if I call `f([list: 1, 2, 3, 4])`, it'll blame `f(r)` in the body of `f`...but the expanded stack trace is correct: the srcloc for `lists.all` (at builtin://lists), then the call to `lists.all` in `f` on line 3, then calls to `f(r)` as appropriate, and then finally the initial call to `f(whichever list I used)`. @jpolitz and @jswrenn should take a look at this, as it touches on the heuristic for which srcloc to report in errors.  FWIW, on the command line, I get 
```
The run ended in error:
Expected to get 2 arguments when calling the function at
builtin://lists:463:0-466:3
from
builtin://lists:463:0-466:3
 but got this1 argument:
[list: ]

Pyret stack:
  builtin://lists: line 463, column 0
  file://C:/Users/Ben/Documents/Brown/pyret-lang/test2.arr: line 3, column 15
  file://C:/Users/Ben/Documents/Brown/pyret-lang/test2.arr: line 4, column 20
  file://C:/Users/Ben/Documents/Brown/pyret-lang/test2.arr: line 4, column 20
  file://C:/Users/Ben/Documents/Brown/pyret-lang/test2.arr: line 4, column 20
  file://C:/Users/Ben/Documents/Brown/pyret-lang/test2.arr: line 4, column 20
  file://C:/Users/Ben/Documents/Brown/pyret-lang/test2.arr: line 4, column 20
  file://C:/Users/Ben/Documents/Brown/pyret-lang/test2.arr: line 8, column 0
```
which is wrong also, in the other direction...

**Comment by blerner** [comment]
This appears to be working now.  Good to close?
