### ISSUE TITLE
on-tick makes nested big bang blank

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#731]
```
import world as W

print(
  W.big-bang(
    0,
    [list:
      W.on-key(
        lam(x, k):
          when k == "a":
            W.big-bang(1, empty)
          end
          x
        end),
      W.on-tick(lam(x): x + 1 end)]))
```

The second big-bang will be blank, while it is expected to show "1".

**Comment by jpolitz** [comment]
This is a duplicate of #543, right?  Or is it a different root cause?

**Comment by sorawee** [comment]
Not duplicate. The cause of this is from a missing `changingWorld = false;` when pausing an old big-bang. #543 is about an incorrect design of states.

**Comment by jpolitz** [comment]
But in the first comment on #543, I said that the bug with `changingWorld` was the cause of that issue.  So if this issue is caused by that, isn't it the same thing?  I'm just trying to determine if this issue would be addressed by correcting nested big-bangs in general, or if there's something special about on-tick, as the issue title suggests.

**Comment by sorawee** [comment]
Ah. I just realized that there are two bugs. Yes, you are right. this is a dup of #543. I always thought that #543 is about another bug...
