### ISSUE TITLE
Loaded modules changed by definition window

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#739]
Consider the following scenario at pyret-horizon

1. Write `import either as E` in the definition window, and then run
2. In the REPL, write `E.left`, it should show `<function>`
3. Clear the definition window _without clicking run_
4. In the REPL, write `E.left`. An error: `An unexpected error occurred: Error: Module not found in depmap: builtin(either) while loading definitions://` appears
5. Write `import either as E` in the definition window _without clicking run_
6. In the REPL, write `E.left`, it shows `<function>` properly again!

**Comment by jpolitz** [comment]
Good catch, thanks!  The REPL stores the compiled form of the definitions window and caches its runtime values, but always gets its _dependencies_ from parsing the current contents.

The fix is straightforward: make `restart-interactions` take a new locator each time, with a fixed set of dependencies, rather than re-using a locator across runs, which causes these kind of stateful issues.
