### ISSUE TITLE
Identifiers defined in the REPL considered builtin

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#747]
```
> b = 1
> b = 1
The declaration of the identifier named b shadows the declaration of a built-in of the same name.
```

This is basically #678 in the other direction...

**Comment by sorawee** [comment]
This even happens across definition window / REPL.

Definition window:
```
a = 1
```

REPL:
```
> a = 1
```

produces the same error message.

**Comment by blerner** [comment]
This is fixed in the modules branch:
![image](https://user-images.githubusercontent.com/918464/61419931-30627900-a8ce-11e9-81a7-631afa347202.png)
(ignore the "6" prefix, and the fact that there's a third highlight color that you don't see anywhere; we're still working on the error rendering and the "6" is a debugging aid right now, while the third color is misleading.)

**Comment by schanzer** [comment]
Now that modules has landed and I've confirmed this as fixed, I'm going to close it. If I've missed something, feel free to re-open.
