### ISSUE TITLE
Odd error message around 3+4 

### ISSUE THREAD

**Issue by kfisler** [brownplt/pyret-lang#761]
When I type 3+4 at the interactions prompt, I get 

   Well-formedness: Found two expressions on the same line ...

Not sure how this is two expressions.

**Comment by jpolitz** [comment]
I may need @ds26gte or @blerner to remember the _reason_, but `+4` is a valid number expression.

**Comment by jpolitz** [comment]
(Agreed that the error message is annoying, especially for the obvious use case of introducing the idea of a whitespace error.)

**Comment by blerner** [comment]
We've hit this before, and it's quite tricky to address.  Numbers can have a leading sign qualifier: -3, or +4.  If there's no qualifier, then it's positive.  Since lexing happens before parsing, we can't decide to re-lex the second number as having no qualifier.

"So let's make +4 be redundant!"  That doesn't help, and makes `3-4` inconsistent with `3+4`

**Comment by jpolitz** [comment]
I wonder if we could make the error consistent without changing the grammar by looking for this case (and others like it) in `parse-pyret.js` on a token-by-token basis when converting blocks.

**Comment by jpolitz** [comment]
For all adjacent expressions in the block, if the second is a number that starts with `+` or `-` and is on the same line as the expression before it, then throw the error.  That would also catch

```
1     +2
1   -2
3 + 1-2
```

etc.

**Comment by blerner** [comment]
parse-pyret isn't allowed to throw well-formedness errors; that happens too late.  Do you want to change the layering there?

**Comment by jpolitz** [comment]
parse-pyret wouldn't throw a WF-error; the point is to not do that.  It would throw an "needs whitespace" error.

**Comment by jpolitz** [comment]
![screen shot 2016-07-14 at 2 17 54 pm](https://cloud.githubusercontent.com/assets/119891/16850584/d71f468c-49cd-11e6-9aaa-54ad3d915559.png)

This is the error with the new heuristic; the highlight is a little hard to get perfect because of the way this tokenizes, but it's definitely better to use in a tutorial style now.

**Comment by blerner** [comment]
@kfisler  @jpolitz is this done?  or is there more heuristically to do?

**Comment by kfisler** [comment]
Looks fine to me now.
