### ISSUE TITLE
Inconsistent errors when omitting whitespace around +

### ISSUE THREAD

**Issue by kfisler** [brownplt/pyret-lang#762]
I wrote an example that lacked whitespace around +

```
    new-ball(coord(100,100), vec(2, 3)) is coord(100+2, 100 + 3)
```

The error I got was that Pyret didn't understand my program, highlighting on "+2"

When I have omitted whitespace around + in function bodies, I've gotten a warning that whitespace is required.  My previous issue report was about a well-formedness error when omitting whitespace around + at the interactions prompt.

From a user perspective, odd to get three different errors for the same core mistake

**Comment by blerner** [comment]
This is a parsing error, and there's no good way around it that I know of.  Here the grammar says `app-exp: expr LPAREN expr [COMMA expr]* RPAREN`, basically.  And you've gone and written two `expr`s in a row.  At the REPL, we're looking for a `program`, which looks for a `block`, which looks for a bunch of `stmt`s, and a `stmt` can be an `expr`.  So there, the grammar is expecting multiple statements and you happened to oblige.

**Comment by blerner** [comment]
The whitespace rules are subtle but needed, because `a-3` is an identifier, `a -3` is an identifier followed by a number, and `a - 3` is a subtraction expression.  Since all of them are lexable and parsable, we can't eliminate any of them from the outset, which is why you're going to get some unfortunate parsing errors in some circumstances.  We _chose_ to carry over the awkwardness to `+` as well, so that you'd at least get a uniform experience with the odd textual behaviors of arithmetic operators.

**Comment by jpolitz** [comment]
Did you mean to respond on #761 761?

**Comment by blerner** [comment]
No, this is accurate here -- this error is about numbers when they don't appear in `stmt`-convertible positions.  And I'm saying we can't detect those.  Your workaround in #761 won't help, because we won't even get to parse-pyret, because this example code won't successfully parse in the first place.

**Comment by blerner** [comment]
Ah, a stronger counterargument here: from a grammar perspective, I don't know whether you intend to fix `foo(a+2)` as `foo(a + 2)` or as `foo(a, +2)`.  And in this parsing context, allowing for two expressions in a row (in case you forgot a comma, but maybe you meant well-spaced arithmetic), will lead to very very bad parsing times -- this leads back to ungrammar territory, and I tried this experiment once before; it didn't end well.

**Comment by jpolitz** [comment]
Yeah, that last argument is a food one, it's peeking into the rabbit hole.

**Comment by blerner** [comment]
@kfisler good to close?  there's not much that can be done here...

**Comment by kfisler** [comment]
If not much to do, close it
