### ISSUE TITLE
error messages need slimming

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#779]
When you use the wrong number of arguments, you get

The function application expression [...] expected the applicant to evaluate to a function that accepts exactly the same number of arguments as are given to it.

This is simply too verbose to expect anyone to read.

To qualify this claim, I tossed this sentence into Word and asked it to compute readability indices. The Flesch-Kincaid Grade Level is 12.0 — about four grade levels above whom we're trying to serve (not to mention those who didn't do all their schooling in English). The Flesch Reading Ease is 29.1 on a scale of 0 to 100, which is way at the wrong end of the spectrum: 100 is really easy and 0 is really hard.

We should fix this error, but also run these tests on _every_ error to make sure they are at least by some reasonable measure within the right range for our target audience.

**Comment by shriram** [comment]
Here, here's how bad this is. I tossed this sentence into Microsoft Word and had it compute the reading difficulty.

**Comment by shriram** [comment]
Here's how bad it is. I simply tossed this sentence into Word and asked it to compute readability indices (something the authors could have done). The Flesch-Kincaid Grade Level is 12.0 — i.e., it expects a US 12th grader, which is about four grade levels above what we're trying to serve, never mind people who didn't do all their schooling in an English-speaking country. The Flesch Reading Ease is 29.1 on a scale of 0 to 100, except the 100 is for really easy and 0 is for really hard.

Based on current form, I suspect what I will get in response is a long discussion of reading indices. I hope we can instead focus on fixing the problems.

**Comment by jswrenn** [comment]
All error messages, even short ones, fare very poorly on the Flesch-Kincaid tests because programming terminology is flagrantly multisyllabic; verbosity is only a minor factor. For example, replacing the vocabulary words in that sentence with single-syllable placeholders increases the Flesch-Kincaid reading level to 73.94 (i.e., a 7th grade reading level).

Running a syllable-based readability test on error messages seems like entirely the wrong metric. Moreover, I know of no readability test that claims to be suitable for evaluating single-sentence snippets. Flesch-Kincaid is not a reasonable measure, and I'm sceptical that there's any sort of automatic quality metric we could apply to the text of error messages.

**Comment by schanzer** [comment]
This is no longer the error message on CPO - I don't _love_ the one that's there now, but it's definitely more readable than the OP. OK to close?

**Comment by schanzer** [comment]
pinging @shriram

**Comment by shriram** [comment]
Yes!
