### ISSUE TITLE
need ternary roughnum comparison operator

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#780]
If you want to compare two roughnums for equality (outside a testing context), you need to write a double application:

```
within(0.1)(~1, ~1)
```

This is going to be pretty confusing syntactically to someone who doesn't understand what is going on. It looks almost like a typo.

There's a simple solution. We should add a ternary tester (@jpolitz suggests `is-roughly-equal`, which is a cute name at least) to take the two numbers and the tolerance. @jpolitz says he's not sure which argument should be tolerance; I think third is pretty natural. So I propose the above would be written

```
is-roughly-equal(~1, ~1, 0.1)
```

(Putting the tolerance first makes sense for people who are used to "currying-style" thinking, but such a person wouldn't need this operator in the first place: they have `within`. This way the equality operator more closely resembles the traditional binary equality operators.)

**Comment by ds26gte** [comment]
I've had this in pyret-lang under the name `_spyret_check_within` for a while now to support WeScheme's `check-within`. The only difference is that it uses absolute tolerance (which is the WeScheme spec). I expect you (and @blerner) want relative tolerance?

**Comment by shriram** [comment]
I'm happy to let you and @blerner argue this out. We absolutely should make the two harmonious, though, otherwise the transition would be painful.

**Comment by jpolitz** [comment]
I had another thought here.

We've previously argued for `is` and `==` to always be equivalent, and the current design reflects that as an axiom.  I think it's worth questioning that, since here I see an argument for _testing_ and _checking equality_ having different goals.

A program probably has a bug if its _control flow_ relies on equality of floats, since it indicates a lack of consideration for tolerance and rounding.  But I find it much more compelling that a _test_ might expect two expressions to evaluate to exactly the same floating point representation.  Indeed, it could be an issue if they didn't (because it might expose a non-associative use of floating point operators in the test expression vs. the implementation).

So what if we _define_ `is` to use `is%(within(~0.0))`?  All the common _testing_ cases will work out (like using the distance formula, or sine and cosine), while `==` will still fail for programmatic uses.

I think this could be a very nice solution that highlights a difference between testing and equality in programs.

It's worth noting that in [1], which provided some useful inspiration for testing and roughnums, the authors make this argument:

"Comparison of primitive values uses ==, while comparison
of object values (including arrays) uses a function added
to the runtime system. This operation deeply compares all
fields of the two values, regardless of access privilege. Floating
point fields are compared with a default tolerance of
0.0001.[15]
Using == to compare floating point numbers is problematic;
a minuscule rounding discrepancy can cause the
test value to differ from the expected value. The difference
between the two values may be acceptable for any
given test; however, the allowable difference varies by application.
Therefore, we require the programmer to specify
this range using within when comparing only floating point
values. The comparison of two floating point values uses
Math.abs(test-expected) < range. The range is capped
only by the numeric representation."

Here, I'm explicitly rejecting this second argument, and saying that it's useful for tests to allow for exact floating point comparison, and in cases where there is rounding error involved, the comparison will fail (with `false` rather than an error), and the programmer will have to introduce an explicit tolerance.

All of this would still require adding the ternary function, so that teachers don't have to use within, but it would also avoid some testing friction.

[1] http://www.cl.cam.ac.uk/~am21/grants/lingsuptesting.pdf

**Comment by shriram** [comment]
This is a _really interesting_ argument. Also very compelling. I have one objection and one quasi-objection. 

Quasi-objection: The current behavior, where the test fails with an error, gives an error message that helps the programmer know what else to do. Reporting `false` certainly tells them the values aren't equal, but if they want to allow this comparison to succeed, they don't have a clear and easy way to find out what they should have written instead. Maybe you could argue this is only for more advanced programmers (who can reason about floats, and that too know when their reasoning is sound, which it isn't by using standard algebraic axioms), but that doesn't help the teacher who has a student who wants to make this pass and neither might immediately think about capturing the values and comparing their difference to some very small number.

Objection: This would allow to pass two values that aren't really equal but happen to appear to be because of float representations (e.g., two different values that fall in an unrepresentable zone). The intellectual argument we made is that floats should never be considered equal. This proposal says “well, but let's look the other way if they happen to coincide”, which is the opposite kind of lying (and which also we wanted to avoid).

[As a side note, I'm still a bit unhappy about allowing operators like `<` to work directly on floats.]

**Comment by jpolitz** [comment]
> but that doesn't help the teacher who has a student who wants to make this pass and neither might immediately think about capturing the values and comparing their difference to some very small number.

Maybe a special case, for the case of comparing two roughnums with `is`, could report a specific error when the test fails.  It could check if they are within 0.1% of one another, and report:

```
These values were not equal, but they are close to one another.  Consider comparing them with is%(within(0.001)) instead of using `is`
```

The float-to-float comparison case is probably the first place folks will run into this, though I can imagine that not being a safe assumption.

> This proposal says “well, but let's look the other way if they happen to coincide”, which is the opposite kind of lying.

Another way to put it is that this proposal says "`is` doesn't check for equality, it checks for a particular weaker kind of equivalence that's useful for testing."  We still take the hard line on `==` and friends.  It's a tradeoff in ergonomics for needing to understand the testing infrastructure more on more float-error-sensitive programs.  A programmer can still test with `is-==` if they want the strict behavior to catch them if they accidentally compare floats.

Thinking about tests in my programs, the main thing an error on `is` for floats does for me is to let me know if I'd accidentally introduced inexactness.  That's a plausible argument for wanting `is` to be strict; if I had exact `4` as an answer and the function starts returning `~4`, I probably want to know about it and not get a silent success.

Then again, for someone writing a program that has to consider unrepresentable zones, Pyret is already setting a high bar for a friendly experience in preventing `==` mistakes by requiring a tolerance-based comparison.  Having to remember to use a slightly different operator in _tests_ is a reasonable burden for that programmer, in exchange for the lack of friction for beginners.



If the lie on `is` is too hard to bear, I would propose adding `is-roughly`, which means `is%within(~0.0)` or even `is%within(0.001)`, which is an easer thing to type, understand, and put in an error message than the written-out `%` version for early programmers.

**Comment by blerner** [comment]
I am happy to introduce `is-roughly`, and have it mean `is%within(0.001)` or some such small tolerance.  I genuinely don't know what `is%within(~0)` means, given that it's a relative tolerance; when you get close to unrepresentable floats, I'm not sure what it'd return.  (In fact, I'm pretty sure `within` complains if you give it a zero as its argument.)  I don't yet want to give up on the equivalence of equality operators with testing operators, either.

**Comment by jpolitz** [comment]
FWIW, there was a discussion about the behavior of `within(~0)` that led to explicitly calling it out in the docs:

```
It can be useful to check that two Roughnums are actually indistinguishable, even though they may be approximating different values. This can be expressed by checking that the numbers are within a tolerance of ~0:

check:
  ((~1 - ~0.9) + 0.00000000000000003) is%(within(~0)) (~0.2 - ~0.1)
end
Note that the same won’t work for a tolerance of 0, the exact zero, which will give an error if used to compare two Roughnums.
```

(https://www.pyret.org/docs/latest/equality.html#%28part._s~3aroughnum-equality%29)

**Comment by shriram** [comment]
`is-roughly` suggests the only special case we will have is roughnums. We have ruled out functions. As @jpolitz points out, images are also worth considering. However, I feel images are different from roughnums: it's reasonable to consider two images identical if their pixels are all the same, even if they got there through very different means. At least at our level of sophistication, I don't think they're analogous to roughnums. But if someone (esp. @blerner) disagrees, then we should probably not build in something just for roughnums.

**Comment by blerner** [comment]
Re `within(~0)`: When I was trying to build a physics simulation yesterday, I failed at writing tests that used `is-roughly`, because I _could not know_ the precise float that was being computed -- it was some nasty thing involving trig functions of awkward angles.  I'd much rather be able to have a small tolerance than a precisely-zero tolerance.

Re relative vs absolute: during this week's physics workshop, I've talked to several folks for whom scale invariance seemed to be a really good feature, which argues again for relative tolerance -- e.g. their experimental rigs are good to within 5% error or something, relative to the overall scale of the experiment.

**Comment by blerner** [comment]
Re images: I'm torn.  I kinda like using `is-roughly` for images, because it "justifies" the blurring/anti-aliasing compensations we make when trying to check for image equality.  I wouldn't mind having exact pixel equality on images via `is`, and blurred equality via `is-roughly`...

**Comment by jpolitz** [comment]
@shriram, @blerner: We compare images for equality pixel-by-pixel, or by exact scene graph equivalence (for fast `true` short-circuiting).  There is no intended imprecision in this metric.

Separately, there is a function that computes a difference between two images that's used for some testing.  But it's never been used for equality.

So I don't really understand how images became part of this discussion, unless we were trying to open back up questions about equality when pieces of an image are occluded., which seems like a road that's been traveled many times before, and not particularly useful to this discussion.

**Comment by schanzer** [comment]
I think images got looped in because we're thinking about the semantics of `is`. If they change to accommodate a degree of tolerance for roughnums, it's natural to ask whether they should change to accommodate a degree of tolerance for images, too.

(Not choosing sides, just pointing out that one path naturally leads us to images)

**Comment by blerner** [comment]
Right now we have the following equality signatures:
```
      'equal-now3': Any, Any -> Equality
      'equal-now': Any, Any -> Bool
      'equal-always3': Any, Any -> Equality
      'equal-always': Any, Any -> Bool

      'within-abs-now3' : Number -> Any, Any -> Equality
      'within-rel-now3' : Number -> Any, Any -> Equality
      'within-abs3' : Number -> Any, Any -> Equality
      'within-rel3' : Number -> Any, Any -> Equality
      'within-abs-now': Number -> Any, Any -> Bool
      'within-rel-now': Number -> Any, Any -> Bool
      'within-abs': Number -> Any, Any -> Bool
      'within-rel': Number -> Any, Any -> Bool

      'num-within': Number -> Number, Number -> Bool (this computes relative tolerances)
      'within-now3' : Number -> Any, Any -> Equality (same as within-rel-now3)
      'within3' : Number -> Any, Any -> Equality (same as within-rel3)
      'within-now': Number -> Any, Any -> Bool (same as within-rel-now)
      'within': Number -> Any, Any -> Bool (same as within-rel)
```
We're missing `num-within-{abs,rel}` for completeness, and this thread seems to be arguing for having `roughly-equal : Number, Any, Any -> Bool`.  Then it's a question of whether you want that to be relative or absolute, whether you want an Equality version, whether you want `-now` and `-always` variants, and whether you want `equal` to be a function to go with the `-now` and `-always` variants.

Additionally, we've loosened the semantics of `is-roughly` to be a test predicate that requires 10e-6 accuracy (i.e., `is%(within(~0.000001))` instead of `is%(within(~0.0))`).  So maybe `roughly-equal : Any, Any -> Bool` assumes that 10e-6 tolerance, and if you want to be more fine-tuned about it, you learn how to use one of these curried functions?

**Comment by shriram** [comment]
>assumes that 10e-6 tolerance, and if you want to be more fine-tuned about it, you learn how to use one of these curried functions?

I like this.

**Comment by blerner** [comment]
I'm implementing `roughly-equal`, `roughly-equal-{always,now}`, `roughly-equal-{always,now}3`, using relative tolerances for them all (just as `is-roughly` uses).  They're easy enough, though they're annoying around zero (see #1389).  I have not added a `equal` function, but I don't have a great argument for or against it.  (`==` has the same meaning as `equal-always`; we have `num-equal` which only works on numbers; we now have `roughly-equal :: Any, Any -> Boolean` and `roughly-equal-always`, but we don't have an operator for `roughly-equal` or a short-name function for `==`.)

It turns out `num-within-{abs,rel}` already existed, so those don't need adding.

Do we really need any other functions?
