### ISSUE TITLE
please switch errors to using a wider, non-proportional font

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#793]
Here's the kind of output you can end up with otherwise:

![image](https://cloud.githubusercontent.com/assets/75030/17233508/69edf50e-54fe-11e6-83e2-7219e1a23e0f.png)

**Comment by blerner** [comment]
Not sure I understand the problem here.  Are you annoyed that the narrow-letter `t` is too small a click target?  That's fixable by adding some padding around them, though it'll make other things look uglier.  But you're the one already agitated about how long the error messages are -- making them be in a wider font will only make the appearance far worse.  I think I disagree with this bug.

**Comment by shriram** [comment]
It's so thin it's (almost) not readable.

I want proportional for _code_ elements. Just like in the editor on the left. Having a consistent typography for code is important.

**Comment by blerner** [comment]
Typo?  You definitely do not wont proportional font for code; you want fixed-width font for that.  You want proportional font for long-form verbiage.

**Comment by shriram** [comment]
Yep. Fixed to say fixed.

**Comment by justinpombrio** [comment]
There's a simple general rule for this:

There is code, and there is text. Code should always be written in a
fixed-width (i.e. non-proportional) font, and text should always be written
in a variable-width (i.e. proportional) font. Mentions of code, like `t`
above, are themselves code, and should therefore be fixed-width.

Deviations from this rule are almost invariably bad typography.

**Comment by shriram** [comment]
Exactly what @justinpombrio said.

**Comment by sorawee** [comment]
Should this apply to the REPL in general as well, so that now we can do ascii art again? (I joked about this a while back but got no attention, now hopefully it will!)

<img width="135" alt="screen shot 2016-07-30 at 17 30 56" src="https://cloud.githubusercontent.com/assets/9099577/17273882/7325220e-567b-11e6-8ec8-faf854646e04.png">

**Comment by shriram** [comment]
What do you mean by REPL "as well"? This is about the REPL in the first place.

**Comment by sorawee** [comment]
If I understand correctly, @jswrenn's fix only applies to the error messages in the red box, not the whole REPL in general.

**Comment by jswrenn** [comment]
@sorawee That commit addresses the font-family issue in your screenshot (but not the character baseline issue).
> so that we can do ascii art again

That's unrelated to that commit. It's _definitely_ a bug that the rendering of value skeletons wasn't always in monospace. Whether the result of `print` calls should be rendered in monospace is less clear. If we follow @justinpombrio's rule, it probably shouldn't be.

**Comment by blerner** [comment]
I think this is fixed.  Close?
