### ISSUE TITLE
(parsing error) Tuple deconstruction doesn't go well with annotation

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#796]
```
> lam({a; b}): a end({1; 2})
1
> lam({a; b} :: {Number; Number}): a end({1; 2}) 
Pyret didn't understand your program around
lam({a; b} :: {Number; Number}): a end({1; 2}) 
           ^^
```

**Comment by blerner** [comment]
Nope, that's a syntax error.  Either write the annotations inline `{a :: Number; b :: Number}`, or use an `as` binding `{a; b} as my-tuple :: { Number; Number }`.  (That'll land soon if not already..)

**Comment by sorawee** [comment]
Cool! Close as wontfix

**Comment by shriram** [comment]
@jpolitz @blerner I am totally unclear on why that's a syntax error (and I've never spotted `as` in documentation…).

**Comment by blerner** [comment]
Of course you haven't; it only got implemented in the last 48 hours as a consequence of my trying to implement your other complaint, that you expected tuple bindings to work recursively.  I was extending @sarahkf's code to allow either tuple bindings or name bindings to appear where we could make them make sense (i.e. anywhere but var or letrec positions).  The grammar is
```
binding: name-binding | tuple-binding
name-binding: [SHADOW] NAME [COLONCOLON ann]
tuple-binding: LBRACE (binding SEMI)* binding [SEMI] RBRACE [AS name-binding]
```
The rationale is to improve error messages, actually: Joe and I discussed how best to report errors where one sub-sub-sub-field of a nested tuple didn't match the expected annotation, and we had a choice of either reporting the innermost annotation or reporting the entire tuple annotation.  Since finding the diff in a large annotation is a pain, we opted for reporting the innermost one.  Further, since `{a; b; c} :: {X; Y; Z}` doesn't tell you anything particularly mnemonic about which annotation goes with which field (especially since as there are more components, it's harder to align the binding components with the annotation components), and since we already had a perfectly working annotation mechanism for annotating the components of a tuple, there was no need to allow this additional annotation syntax.  Worse, there's _no_ parsing-unambiguous way to say "Please either write `{a :: X; b :: Y}` _or_ write `{a; b} :: {X; Y}`"; can't be done.

The `as` bindings allow you to give a name to the not-deconstructed tuple in addition to binding its pieces.  (When it's not supplied, we gensym a name, internally.)  I've already had occasions to use this, especially in fold-loops, where sometimes I want to pull apart the accumulator and tweak it, and sometimes I want to return it unchanged.

There's one bit of ambiguity that can arise with this syntax: you could write `{a :: X; b :: Y} as f :: {L; M; N}`, and produce utterly incompatible annotations for `f` given its binding.  We can't detect that at compile time, generally speaking, but we'll give appropriate runtime annotation errors, and the type checker will give appropriate type errors if it encounters such absurd code.

**Comment by jpolitz** [comment]
`as` was just added to support both kinds of tuple binding – naming/annotating the pieces, and naming/annotating the whole tuple.

The goal here was to balance some design points in destructuring assignment.  I hadn't actually thought of this example as odd until @sorawee wrote it, because I had a consistent way to think about these.

The invariant coming through here is "each binding of a name comes with an optional :: annotation".  Since tuple bindings define several names at once, each name gets an optional ":: annotation" part.

The thought is that the default for destructuring binding is to name and annotate each piece, e.g.

```
fun draw-labeled-point({{x :: Number; y :: Number}, label :: String}) -> Image:
  ... "Make a labeled point somehow" ...
end
```

Though usually the pieces are all the program needs, _sometimes_ we want to have a name for the whole tuple.  So we added `as` to make it so that was possible with slightly more effort:

```
fun draw-labeled-point({{x :: Number; y :: Number}, label :: String} as the-point):
  ... "Make a tuple somehow, maybe using the-point as well" ...
end
```

Now there's a new name, and it gets an optional ":: annotation as well.

This has a few nice properties:

- Every annotation corresponds to a name (except arrow annotations)
- It's natural to have a mix of annotated and un-annotated tuple fields
- In nested cases, the annotation is right next to the thing it annotates, so less visual matching of the shapes is required

One downside to what we have is that if you define something like

```
type Point = {Number; Number}
```

Then you cannot write:

```
fun translate({x; y} :: Point, dx, dy):
  ...
end
```

Instead, you must write:

```
fun translate({x; y} as p :: Point, dx, dy):
  ...
end
```

Which is extra typing.

I think it's possible to skip the `as x` bit and still parse bindings with a tuple on the left and an annotation on the right.  Note that allowing any destructuring binding to do this leads to lots of ways to write "the same thing" in nested cases.

```
{{x; y} :: {Number; Number}, {dx, dy} :: {Number; Number}}
{{x :: Number, y :: Number}, {dx :: Number, dy :: Number}}
{{x; y}; {dx; dy}} :: {{Number; Number}; {Number; Number}}
```

I don't think I see a reason to _not_ allow this, though; it's meaning is clear in that it designers to an `as _`.  @blerner, is there anything wrong with putting this in?

**Comment by jpolitz** [comment]
Oops, didn't see @blerner's comment.  I guess it's ambiguous to do it without `as`.

**Comment by blerner** [comment]
Joe's points are dead-on: "every name can have an annotation" is the main invariant, and the one unfortunate casualty of that is that we can't say `{x; y} :: Point` for some typedef of `Point`.  It's not grammatically ambiguous to parse `tuple-binding COLONCOLON ann`, but it becomes problematic if you want to allow that, _and_ `as` bindings (which are strictly more useful) _and_ allow element-wise annotations: you now have up to _three_ positions that can annotate an individual nested tuple field, one of which is completely anonymous, so determining how to compile those annotations and determine what locations to blame at runtime (especially if they're inconsistent) becomes very murky.  Plus, as Joe noted, there become far too many ways to write the same thing, with no pedagogical or other mnemonic clue as to which is preferable.
