### ISSUE TITLE
fractional roughnums

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#813]
Is it intentional that this is an error, because it is turned into an operation which must have spaces around the operator? 
```
~1/2
```

**Comment by ds26gte** [comment]
Yes.  (1/2 and -1/2 are valid rationals;  ~1/2 is a syntax error.)

**Comment by blerner** [comment]
Do you recall why we chose to make `~1/2` a syntax error?  (I vaguely recall it was because there's something utterly precise-seeming about `1/2` that makes it being a roughnum seem disingenuous or something.)

**Comment by ds26gte** [comment]
Since Pyret does allow us to enter an impossibly precise decimal numeral as a roughnum (like JavaScript, the extra precision is simply ignored), I guess there is no real reason why we shouldn't allow ~P/Q as a user syntax for the nearest roughnum. Should we go ahead and add?

**Comment by schanzer** [comment]
I see no argument against it

**Comment by jswrenn** [comment]
When I type a fractional literal, I kind of expect there to be a fractional representation. E.g., If I type `1/2` into the REPL, it can be displayed both as `1/2` and `0.5`. The same cannot be said for `~1/2`, because what really is meant is the expression `~1 / 2`, or `num-to-roughnum(1/2)`.

On a related note, I'm not sure which one of those two expressions is the right way to visually parse `~1/2`. Are there any numbers `A` and `B` such that `num-to-roughnum(A/B)` would produce a different result than `~A / B`?

**Comment by ds26gte** [comment]
`num-to-roughnum(A/B)` is the better interpretation.  E.g., it is possible for `A` and `B` to be very small but non-zero, in which case `num-to-roughnum(A/B)` would give something substantial and nonzero, whereas `~A / B` would give `~0`.

**Comment by ds26gte** [comment]
Oops: I forgot `A` and `B` are integers and can't be very small.

**Comment by ds26gte** [comment]
Added ~P/Q user syntax for roughum in 59dcbb6.

**Comment by schanzer** [comment]
Fixed on CPO

**Comment by jswrenn** [comment]
> Oops: I forgot `A` and `B` are integers and can't be very small.

Things get weird when they are very large:
```
> ~9007199254740993/1
9007199254740992
```

**Comment by jpolitz** [comment]
That's just life with roughnums beyond `MAX_SAFE_INTEGER` though.  `9007199254740993` isn't representable as a roughnum; `~9007199254740993` gives the same answer – `~ 9007199254740992`
