### ISSUE TITLE
Some error relating to tables can't display

### ISSUE THREAD

**Issue by blerner** [brownplt/pyret-lang#821]
https://pyret-dev.herokuapp.com/editor#share=0B32bNEogmncOOEh1eEZPTW5TZFk

Insert at line 31, `delta-v: difference() of delta-x`, and run.

The error message doesn't render; I'm not sure which error it actually is, here...

**Comment by jswrenn** [comment]
According to the console, the error seems to be that the `ED.text` constructor call on [line 1865 of compile-structs.arr](https://github.com/brownplt/pyret-lang/blob/sql/src/arr/compiler/compile-structs.arr#L1865) is being passed a _list_ (containing  the one element, the string "delta-v") rather than a string value.

Given what's on [line 1859](https://github.com/brownplt/pyret-lang/blob/sql/src/arr/compiler/compile-structs.arr#L1859), I'm pretty confused.

**Comment by jpolitz** [comment]
Fixed by https://github.com/brownplt/pyret-lang/commit/5735d7d90693b8f80e8053951d1b6243ee6ed088
