### ISSUE TITLE
Tuple bindings and tables

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#823]
Table columns after `using` are one place where tuple bindings still don't work.

It would be nice if we could use (mandatory) `as` bindings here:

```
t = table: time, point
  row: 0, {5; 6}
  row: 1, {7; 8}
end
extend t using {x; y} as point:
  x: x,
  y: y
end
```

It could be nice to reverse the as in this case:

```
extend t using point as {x; y}:
  x: x,
  y: y
end
```

**Comment by blerner** [comment]
Reversing the bindings would likely be grammatically awkward. We have them in the current order because annotations would be weird to have in the middle of a binding, and then consistency argues we should keep it this way for table column bindings too.

It shouldn't be hard, grammatically, to add this feature. But it is tricky to implement, because tuple bindings are simplified away during name resolution, which happens before table operations desugaring. Additionally, the body of most table operations is not a single expression, so the desugaring of tuples (which wraps the subsequent expression with additional let bindings) won't quite work...

**Comment by jpolitz** [comment]
Closing as not likely to be necessary – this table syntax is used in really limited use cases, and the new API allows for functions to use the tuple-binding synax as parameters naturally.
