### ISSUE TITLE
Comment followed by paren parsed as PARENNOSPACE?

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#828]
(All branches)

This program runs and trace-prints two values:

```
### Bug 1
3 * 2

(1 + 2)
```

This program _parses as a function call_ and gives a dynamic error that `2` is not a function:

```
### Bug 1
3 * 2


### Bug 2
(1 + 2)
```

**Comment by blerner** [comment]
You can "fix" that by marking the BLOCKCOMMENT and COMMENT tokens with parenIsForExp, but I'm trying to remember why we chose to not do that, originally... Might be worth looking at the history of the tokenizer, see what we were thinking there?

**Comment by blerner** [comment]
Apparently we weren't thinking anything, since the commit messages relevant to that line are mostly useless.  Also, if I make the change above, none of our parse-tests fail, which means we never checked for this kind of case...

But I sort-of don't like the suggestion above.  I can't decide if I prefer to think of comments as whitespace, or as non-existent.  The distinction is visible in this program:
```
tostring#
(1 + 2)
```
Should that trace-print two expressions, namely `<function:tostring>` and `3`, or should it trace-print just `"3"`?  The first interpretation comes from treating comments as whitespace; the second comes from erasing them entirely.  As a second example, what about
```
map#|I don't know what type here|#(something-weird, some-list)
```
If comments are whitespace, this becomes a two-expressions-on-a-line error; if they're non-existent, this will be a function call.

The principle of least surprise fails me here; I don't know which of these is "less surprising" to an "average" Pyret user.

**Comment by jpolitz** [comment]
This program:

```
tostring#
(1 + 2)
```

Not only has a comment, but has a _newline_.  I would be very surprised if someone tried to convince me that this shouldn't act like other newlines because the newline is "part of" a comment.

The inline block comment could go either way, I think.  But a comment with a newline clearly ought to mean the same thing as a newline to me, that's not surprising at all.

**Comment by jpolitz** [comment]
Also, if the comment was supposed to mean nothing, it very much violates expectations in the originally posted error, where _adding_ a comment had the effect of ignoring newlines that preceded it.  I think there's no sensible argument for this being a single expression:

```
foo




#
(1)
```

While this is two:

```
foo




(1)
```

**Comment by blerner** [comment]
I'm torn on your first example -- if there were a space before the `#`, I'd agree totally.  I'm not 100% sure whether to think of the newline as part of the comment.  As it turns out, in the current implementation of the tokenizer, the newline is not considered part of the comment, which would lead to your interpretation by default.  But I think we did that for expediency in counting lines, or something; it wasn't utterly necessary.

In your second example, there are plenty of newlines not masked by the comment, so I'd certainly think it's two expressions.

I'm not opposed to thinking that comment == whitespace, just trying to think it through fully before committing to that.

**Comment by justinpombrio** [comment]
Comments are whitespace, not non-existent. If they were non-existent, then
ab#|comment|#cd would be *one* identifier.

**Comment by blerner** [comment]
Justin's example above doesn't currently work properly, but Joe's do. Reopening.

**Comment by blerner** [comment]
I think this works now, for all the examples above.  Closing.
