### ISSUE TITLE
add-line doesn't handle bottom-right edges well

### ISSUE THREAD

**Issue by blerner** [brownplt/pyret-lang#829]
`add-line(square(50, "solid", yellow), 10, 50, 40, 50, blue)` doesn't draw any visible line, but `add-line(square(50, "solid", yellow), 10, 25, 40, 25, blue)` does, and so does `add-line(square(50, "solid", yellow), 10, 50, 40, 51, blue)`.  Ditto if you swap x and y coordinates.

Is this related to image crisping, @schanzer ?

**Comment by schanzer** [comment]
Almost certainly. Give me a few days (in LA training right now)

**Comment by schanzer** [comment]
Not specifically related to `add-line`:
```
(overlay/xy (square 50 "solid" "yellow") 
            10 55
            (line 30 0 "blue"))
```

Still investigating...

**Comment by schanzer** [comment]
Okay, so it turns out there was a crisping issue here AND some deviations from the racket spec that had gone unnoticed since 2009.

1) We crisp vertex-based images by trimming 0.5px from all points that are greater-or-equal-to the midpoint, and adding 0.5px to all points that are less-than the midpoint. That works great, as long as the image isn't 1px wide. When this happens (in the case of a line or 0-width rectangle), trimming results in no line whatsoever. This was fixed by removing the "-or-equal" part of the check. This is fixed in WeScheme (along with some cleanup) in https://github.com/bootstrapworld/wescheme2012/commit/e25398fa8bcf1b30562b66d69df216bcf386bdf1

2) Various 0-size shapes (lines and rectangles) are actually floored at 1px, so (rectangle 30 0 "outline" red") should still draw a visible, 1px line. This was fixed in WeScheme with https://github.com/bootstrapworld/wescheme2012/commit/8f22cfdc9450847ae85c603c2a4f522fb5a9cc20

Both the `add-line` and `overlay/xy` samples now work on http://234.wescheme.appspot.com/openEditor . If this looks satisfactory to you, I'll port the fix to Pyret.

**Comment by schanzer** [comment]
Addressed by https://github.com/brownplt/code.pyret.org/commit/f98554d25bc0baa3ddfc392cca48eb7fb8c13709

**Comment by schanzer** [comment]
Closable?

**Comment by schanzer** [comment]
Fixed on CPO
