### ISSUE TITLE
editors in error messages not positioned quite right

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#850]
Here's a program (on CPO).
```
fun rev<T>(l :: List<T>) -> List<T>:
  fun h(shadow l, rv):
    cases (List) l:
      | empty => rv
      | link(f, r) =>
        h(r, link(f, rv))
    end
  end
  h(l)
end

check:
  rev(empty) is empty
  rev([list: 1]) is [list: 1]
  rev([list: 1, 2]) is [list: 2, 1]
  rev([list: 1, 2, 3, 4]) is [list: 4, 3, 2, 1]
  rev([list: "x", "y", "z"]) is [list: "z", "y", "x"]
end
```

When I click on the test failure box, some of the editors are not positioned right. For instance, see how only the bottom bit of the line of code is visible here:

![image](https://cloud.githubusercontent.com/assets/75030/17988962/d3db3134-6af7-11e6-852d-7791bc79b28a.png)

or here:

![image](https://cloud.githubusercontent.com/assets/75030/17988970/e4b757f8-6af7-11e6-8c70-ee6593bc1101.png)

**Comment by jswrenn** [comment]
I've always had a minor overscrolling issue, but nothing so extreme that the code scrolled out of view. 

This has been hard to track down. It seemed to be caused by CodeMirror's [styling of `.CodeMirror-gutter`](https://github.com/codemirror/CodeMirror/blob/5.11.0/lib/codemirror.css#L196-L200). Setting `display: block` eliminates over-scrolling, as does removing both the `height: 100%` and `margin-bottom: -30px` rules. The problem isn't limited to error message snippets, but rather all one-line CodeMirror instances _with line numbers enabled_; if you turn on line numbers for the REPL snippets, they suffer from the same issue.

The apparent trigger for CodeMirror's miscalculation of line height is caused by [a padding override](https://github.com/brownplt/code.pyret.org/blob/1ab84b1cb68c6f6e50fa3221054fc132af12f7a5/src/web/css/editor.css#L15-L17) in our `editor.css`:
```
.repl .CodeMirror-lines {
  padding: 0;
}
```

I'll patch this soon (probably this weekend).
