### ISSUE TITLE
`when` should not be an expression

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#852]
Right now we can't write:

```
fun test():
  x = when 1 < 2:
    0
  end
  1
end
```

So it seems that we don't want `when` to be an expression.

However, `when` return a meaningful value.

```
fun test():
  when 1 < 2:
    123
  end
end
```

returns `123` when invoking `test`.

We should prevent this to happen, and make sure that function can't have `when` at the end, just like how let binding couldn't be at the end.

Moreover, the multiple expression check should whitelist `when` as an exception.

The same goes to `check:` block and mutation.

**Comment by sorawee** [comment]
But I also can see than writing

```
for each(...):
  x := link(..., x)
end
```

is kinda convenient.

So, perhaps we want to allow `when`, `check:`, and variable mutation to be at the ending position. However, IMO it should always return `nothing` and not a meaningful value. And again, they should bypass the multiple expression check.

**Comment by belph** [comment]
> IMO it should always return nothing and not a meaningful value.

Note that this is currently undefined behavior, so it'll need to be specified (quote from the docs):
> If the test condition is true, the block is evaluated. If the test condition is false, nothing is done, and `nothing` is returned.

AFAIC, this issue begs the question: why are `when:` blocks statements in the first place? I mean, sure, it would likely be a code smell to have a `when` 'expression' in place of, say, a function parameter, but I see no reason why one should be barred from doing so in principle.  

```
when x:
  y
end
```
should just be sugar for
```
if x:
  y
else:
  nothing
end
```
or, if we want to make `when:` blocks always evaluate to `nothing`, 
```
if x block:
  y
  nothing
else:
  nothing
end
```
(note that, unless I am misreading, our [current desugaring][current-desugar] is doing _both_, which seems buggy...also, yes, this snippet is the same on `master` and `horizon`)

Knowing that this is just sugar, it seems strangely inconsistent that I can use the desugared form of a syntactic construct in places that I cannot use the sugared form.

Pinging @blerner, since he likes to ~~put me in my place~~ express his opinion when I have qualms such as this :)

[statements]: http://blog.brownplt.org/pyret-docs/horizon/Statements.html
[current-desugar]: https://github.com/brownplt/pyret-lang/blob/067624c2fd24ef9e5d4d98c30ca145fc65bb8af2/src/arr/compiler/desugar.arr#L410-L411

**Comment by blerner** [comment]
Yes it's buggy. When statements are us being opinionated about how they should be used: for side effects only. The fact that they don't always return nothing is a desugaring mistake.  That code tried to be clever about not nesting s-block constructions, and screwed up in the else branch.

**Comment by blerner** [comment]
Also note that they "return nothing" because ultimately Pyret desugars to an expression-based language. It shouldn't be considered to really have a return value, any more than assignment statements should, or let bindings... Which is why none of them are allowed as the final expression in a block.

**Comment by belph** [comment]
> Which is why none of them are allowed as the final expression in a block.

In that case, shouldn't `when` blocks be banned from the end of blocks as well (for consistency's sake)? See @sorawee's comment

**Comment by blerner** [comment]
Yup

**Comment by blerner** [comment]
Well, turns out I was wrong about assignment statements -- those are allowed as the final statements of blocks.  So I'm going to fix this issue for now by making the desugaring of `when` always produce nothing.  I'll leave it to a separate issue to decide if we want to make `when` be disallowed from being the final statement in a block.  (When I try that, it breaks the compiler for some reason, so it's a not-completely-trivial change.)  I'm also not going to make them be implicit blocky forms, for consistency with the lack of any implicit blocky forms anywhere.
