### ISSUE TITLE
should `num-floor` make roughness disappear?

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#862]
```
> num-floor(~3.14)
3
```

I can see an argument both ways, but it feels a bit weird for roughness to disappear just because I took a floor. If a value is `~3.00001`, it could in reality just as well be `2.999`, whose `num-floor` would have been `2` rather than `3`…

**Comment by jpolitz** [comment]
Here's an old issue where the "should be exact" felt important: https://github.com/brownplt/pyret-lang/issues/262#issuecomment-53508179

**Comment by schanzer** [comment]
I don't see how we can return both `2` and `3` in this situation, so we'd need to choose. Returning `~3`  seems like a non-starter, since the expectation of rounding operators is that you're giving up accuracy for the sake of the "nearest integer" (for some definition of "nearest").

To me, `~3.00001` reads as "something just over 3", as opposed to "something around 3". Am I crazy in thinking most people will also see it that way, and expect `num-floor` to result in `3`?

**Comment by ds26gte** [comment]
A roughnum is a number that is within a continuous and contiguous smear (interval) on the real line. Both the number and the size of the smear are vague. (So `~3.00001` could well be something _below_ `3`.)

"Either 2 or 3" is not a continuous smear.

**Comment by schanzer** [comment]
Yes, I'm aware of what `~3.00001` _could_ mean, but I'm suggesting that we apply an intuitive falsehood to the behavior of various rounding operators if we want them to work with roughnums.

**Comment by shriram** [comment]
I'm not sure why we're discussing "either `2` or `3`", which was not at all my proposal. My point was that the true number that is represented by `num-floor(~3.0001)` _may very well be `2`, not `3`_. So that's an argument for making the result of that expression be `~3`.

Even Dorai's semantics for a roughnum doesn't go far enough. Because of non-associativity, you could have a negative answer for something that is truly a positive value — which makes the smear rather larger than one might think (though to his credit Dorai did say the smear's size is "vague"). This also assumes you didn't have a chaotic computation, in which case the roughnum and the true value have not even a passing acquaintance with each other.

**Comment by shriram** [comment]
@jpolitz Thanks for dredging that up. On re-reading it, I'm not convinced that it makes a case for `num-floor` to return an exact number. It does make the case for `num-exact`. 

It's worth noting that `num-exact` is a violation of the rule of roughness contagion, but at least it makes sense for it to be the _only_ exception: roughnums are always contagious unless you explicitly say "I hereby forfeit my right to the truth". That seems like a good principle. Maybe there are other primitives that have the same ring to them.

I ran into this `num-floor` issue when editing PAPL and wanted to say roughnums are contagious, tried `num-floor`, was surprised by the result, and _could not construct a reason why it should be that way_. The italicized part is the important bit. I can't come up with a good reason why `num-floor` is _not_ roughnum contagious.

**Comment by blerner** [comment]
num-floor and num-ceil have the same ring to them, to me: by discretizing the result, you lose the smooth spread that roughnums imply.  If you truly wanted to say "nothing but num-exact will discard roughness", then you are inexorably forced to rough boolean comparisons, too -- which Dorai's suggested at one point, too -- at which point roughnums are pragmatically useless to work with and unworkably expensive to use.

So I think of roughnum contagion as holding _for any continuous function on numbers_, and that seems plausible, pragmatic and internally consistent to me.

**Comment by awstlaur** [comment]
What the agreement ends up being, I request that `num-floor`, `num-celing`, `num-round`, and `num-round-even` all have keep the same type conversion (whether it's Rought -> Exact, or no conversion).

(If I had a roughnum result I expected to be very close to _some_ integer, I would just use `num-round`.)

**Comment by jpolitz** [comment]
@shriram – in that old issue @blerner was annoyed that he had to use `num-exact`, which was the whole issue.  Maybe you misunderstood that in your response.

It would be truly bizarre if `num-exact` didn't return an exact number, since that's its sole raison d'être.  So I didn't think that was up for argument.

I think the whole issue could be solved by introducing an exact variant of functions whose ergonomics is hurt by returning a roughnum.  Here, I predict lots of user frustration with `num-floor` not producing an integer for an array index, or a RGB number, etc.  I've tried `floor` before in those cases and been surprised that it wasn't a convenient way to "get exactness back."  The argument for not returning an exact by default is mathematically sound, of course.

It would be useful to simply give them a pointer to `num-floor-exact`, or even `exact-floor`, in those cases, as a contraction of the `num-exact(num-floor(n))` pattern, which I would expect to come up a lot.  Ditto for `truncate`, `round`, `ceiling`, and perhaps others.

**Comment by ds26gte** [comment]
Also: bubbling up contagion for its own sake may not even be correct, let alone inconvenient.  Two examples that come to mind: 

- multiplying a roughnum by an exact `0` produces exact `0`

- raising a roughnum to exact `0` produces exact `1`

**Comment by blerner** [comment]
The "argument for not returning an exact by default" _isn't_ so mathematically sound, to me: while I agree ~3.0 may be roughly ~2.999999 and may be roughly ~3.000001, taking `num-floor(~3.0) == ~3` doesn't convey to me "Hey, this might actually be 2!" at all.  If I were willing to believe that it could be so far wrong, I'd have to also believe that it might be 4 (equally wrong in the other direction), and that's an utterly implausible result.  (To believe that, I'd have to believe  ~3.000001 might be so far wrong that it's really 4.5, or something.)

Point is, we don't have a precise semantics for "how rough are roughnums?", beyond "whatever IEEE 754 says, unless we've modified things in our numeric tower"  And the roughness obviously changes with the magnitude of the number -- I'd be more willing to believe that ~3000000000 might be ~2999999999 or ~3000000001, and so `num-floor` of it could vary by a few integers, than I would be willing to believe the same of ~3.00000001.  That's two very different notions of roughness, to me...

**Comment by jpolitz** [comment]
I think the point is that a Roughnum may be arbitrarily rough. `~3` could be mathematical 82648.2, if the right error margins are stacked. The application is responsible for tracking and managing error based on the operations that have been performed.

So ~3 represents the value 3 plus or minus and unknown delta that could be arbitrary size. It's a reasonable argument that dropping the knowledge of the existence of such a delta is a bad idea.

**Comment by blerner** [comment]
If that's truly the case, then roughnums are computationally meaningless: they could be 0 +/- NUM_MAX, and literally have only the meaning "I'm some number; sorry I can't be more helpful than that."  

We know that roughnums do not have sufficient innate information to track their remaining significant digits -- and any application that truly cares about such accuracy will need to track it manually, and therefore won't be able to use discontinuous functions anyway, because (a) the types don't line up and (b) they have to contend with the case where the in-accuracy straddles whatever discrete boundary the app wants to use.

Roughnums have pragmatic semantics: they work with comparisons, they print as if they actually had meaningful digits, they respond to arithmetic operations.  I think the pragmatics of this one outweigh mathematical purity.

**Comment by blerner** [comment]
This seems to have been resolved in favor of making num-floor/num-round/num-ceil/etc return exact results.  Closing.

**Comment by shriram** [comment]
For the record, we have had this discussion one more time now. I argued for allowing `<` and `>` but *not* `<=` and `>=` on RoughNums, since one can use it to reconstruct equality. Ben disagrees. No new knowledge was gained. (-:
