### ISSUE TITLE
rudimentary table program produces type checker internal error

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#863]
```
email =
  table: sender, subject
    row: "Matthias", "hi"
    row: "Kathi", "foo"
    row: "Joe", "bar"
    row: "Matthias", "bye"
  end
```

Type-checking this produces
«An error occurred rendering the reason for this error; details logged to the console»

(Given that the error was logged, I assume someone already saw this; but just in case.)

Note that adding type annotations does not make any difference:

```
email =
  table: sender :: String, subject :: String
    row: "Matthias", "hi"
    row: "Kathi", "foo"
    row: "Joe", "bar"
    row: "Matthias", "bye"
  end
```

**Comment by blerner** [comment]
@mkolosick : this is a bug in type-check.arr, in pretty much every usage of the `lookup-id` function.  The `unbound-id` error expects to get an `s-id` or `s-id-var` or `s-id-letrec` as its argument, and you're passing in just about every type of expression possible.  More, in the `s-prim-app` case, you're passing in a string (the function name) instead of a key for lookup.

I think that type checking ought not to report unbound id errors; you shouldn't be allowed to run type checking if there are unbound ids in the program.  @jpolitz agree?

**Comment by mkolosick** [comment]
This `unbound-id` is because `makeTable` is not in `type-defaults`. I've created a new `unbound-id` error that is structured slightly differently for the type-checker to use so it doesn't blow up anymore.

I am unsure what the type for `makeTable` should be though.

**Comment by blerner** [comment]
I don't think we want to add a new kind of error here. What you're saying is that the underlying problem is due to desugaring, which is a general we-screwed-up issue, not a user-error issue. Pinging @jswrenn and @justinpombrio for their input.

As for the type of makeTable, I'd be ok with something approximate for now, like `Any -> Table`, or whatever it needs to be. But if you can tell that it definitely came from desugaring, you can be a bit more precise in the output, I'd bet...

**Comment by mkolosick** [comment]
I see what you mean.
