### ISSUE TITLE
more TMI in error message

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#870]
I thought we'd got most of the overly verbose error messages, but we seem to have missed a few. For instance:

![image](https://cloud.githubusercontent.com/assets/75030/18671302/a3b127ce-7f11-11e6-9ae7-99b61f7ef034.png)

Many high-school students won't even understand several of the _words_: "if and only if", `equal-always` (what's that?), "satisfied", "operand" (I thought we were using just "left" and "right"?), "applied"…and there's passive speech without a clear reason. Also "reported failure" (I'm envisioning something like this: http://l7.alamy.com/zooms/c0cfe7d427a34cc198ca24a7515b3d85/1930s-businessman-talking-on-public-pay-telephone-in-phone-booth-cmt448.jpg).

**Comment by jswrenn** [comment]
I've addressed this in brownplt/pyret-lang@71005da7f5e891f8549e5244314130a254e89eba (and updated tests accordingly in brownplt/code.pyret.org@857bcecec834727281eda3d85ef3961c252faf10):
![Declutter testing failure messages.](https://cloud.githubusercontent.com/assets/3820879/18725433/46a32eda-800e-11e6-9994-9f477552c8fd.png)

Looking at that screenshot, I realize I forgot to change "evaluated to" to "was"; I'll do that now.

**Comment by jswrenn** [comment]
Screenshot of the message as of 10e112bea06fc2fff61c103125e8c06bf83b5ea6:
![Declutter testing failure messages.](https://cloud.githubusercontent.com/assets/3820879/18725865/fab18f56-800f-11e6-82ec-0bccf103e5d6.png)

@shriram Can I mark this issue `horizon-fixed`?

**Comment by jpolitz** [comment]
What about "Didn't pass this test", or "Didn't pass this `is` test" for the before-code part?

I don't really know if "test operator" adds much here.

**Comment by justinpombrio** [comment]
This "is" test failed because the [left] and [right] sides were not equal:

...

The [left] side was:

...

The [right] side was:

...

**Comment by shriram** [comment]
And so many… _words_! "It succeeds if": “succeeds” is such a big word! Are we really using “succeeds” everywhere? Does `+` only _succeed_ if both operands are numbers?

**Comment by jswrenn** [comment]
> Are we really using “succeeds” everywhere?

The use of "success" and "failure" to describe the behavior of the testing operators is taken [straight from the docs](https://www.pyret.org/docs/horizon/latest/testing.html#%28part._testing-operators%29).

> Does + only succeed if both operands are numbers?

No, for functions, we talk about the function _expecting_ certain things.

**Comment by shriram** [comment]
Right. Those were meant to be leading questions. As I've said before, in this very setting, the docs are not authoritative texts; in fact, we should assume this is the first attempt to comprehensively dictate a crisp and consistent vocabulary for Pyret, which we can then carry through everything. (Which is why I suggested making a vocabulary document à la Guillaume's for Racket.) The error messages should control the docs, not the other way around.

**Comment by jswrenn** [comment]
> The error messages should control the docs, not the other way around.

Interesting.

> And big words, too [...]

I don't think number of letters a word has is generally a good proxy for estimating our user's comprehension of a word. By [some counts](https://en.wiktionary.org/wiki/Wiktionary:Frequency_lists/PG/2006/04/1-10000), 'success' is a top-1000 word (which would make it fair game for Randall Munroe's _Thing Explainer_). Can you explain your criticism a bit more?

**Comment by shriram** [comment]
A lot of our users are or are going to be

• younger readers, who are still slow at reading
• teenagers, who are impatient
• non-native speakers of English, for whom reading English is difficult

Every word counts. Every pixel of screen acreage also counts.

**Comment by jswrenn** [comment]
I understand all of those concerns, but not in relation to "success". What's a word we could use instead?

**Comment by jpolitz** [comment]
Didn't pass this is test:

<code>

The [left] and [right] sides were not equal.   # could even be "were not the same"

The left side was:

<value>

The right side was:

<value>

**Comment by blerner** [comment]
I worry that if we simplify the "were not equal" wording too much, that we lose the informativeness that we have in explaining the differences in `is`, `is==`, `is=~` and `is<=>`.  I don't think we should say "were not always equal (because you chose to use equal-always by dint of using `is`)", but I don't think we should lose the deliberate association with "equality is tricky"...

**Comment by blerner** [comment]
Looking back over this issue, after having updated test feedback messages in #1350, I think our current wording is pretty good.  

* I don't like "Didn't pass this `is` test", because the subject of the sentence is missing -- who or what didn't pass?  It's not that Pyret didn't pass this test (contrast with "Pyret didn't understand your program"), and so the implicit subject of the sentence is *You* or *Your program* didn't pass the test -- i.e., it's accusative, which we're trying hard to avoid.  Saying "test operator" makes the statement more neutral, accusing neither Pyret nor the programmer.

* The styling of `is` within "The test operator `is` failed..." is very subtle, unlike here on github where code has a gray background.   As a result, "The `is` test failed" just reads clunkily to me, because it looks too much like "the is test failed", which ain't grammatical.

* We use "success!" a lot in our simulations and our talking-to-teachers, so I don't think "succeeds" is too much of a stretch any more.

* No one's complained about this in two years :)

Any further objections to the current wording, or can we close this?

**Comment by shriram** [comment]
We can close and create a new one if and when it looks problematic. Thanks.
