### ISSUE TITLE
Treat `is` specially in parse errors

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#876]
For people coming from Python, `is` is a predicate used in conditionals. Therefore, it's reasonable to write something like

```
if x is y:
```

The current error message is totally generic. If you read it with Python glasses, you literally will not see _an_ error at all. 

If you write

```
fun f(x, y):
  x is y
end
```

you do get a meaningful error (that `is` needs to be inside a check or where block), but if you write it as an _expression_, you don't. So the logic is clearly there, it just needs to be applied in more places.

Also, note that the error does not list `examples` blocks.

**Comment by jpolitz** [comment]
This is a good idea to fix.

The reason it isn't trivial is that `is` is parsed as a statement, not as an expression.  So those two situations look very different from the point of view of the parser – one parses as a statement that's in the wrong context, and the other doesn't parse at all.

We could make `is` parse as a binary operator expression, and then have more well-formedness rules for it.  We've analogous choices with other forms, and it may be the right thing to do here as well.

**Comment by shriram** [comment]
Separately, note the last line. Can we create a term like “checking block” and use it consistently? Maybe hovering over it pops up to say “`check`, `test`, or `examples` blocks”, and that is authored in only one place.

**Comment by blerner** [comment]
I can fairly easily get Pyret to produce
```
The testing operator
     (3 ****is**** 4)
must be used inside a check or where block.

Did you mean to use one of the comparison operators instead?
```
where the highlighting is solely on the operator itself.  It is drastically harder (as in, I do not think it is feasible with the current grammar) to highlight the entire expression, because as Joe points out, testing operators are parsed as statements, not as expressions.

My error message text above is meant to be identical in phrasing to the meaningful error you currently get from the `x is y` statement in the second example; in the absence of consensus on what the rephrasing here should be, I'm just going for consistency.

**Comment by shriram** [comment]
Anything that improves on the present would be good, thanks. Note also the vocabulary issue.

**Comment by blerner** [comment]
@shriram, @jswrenn : I'm going to mark this issue as horizon-fixed, but it still explicitly says "check or where block".  Please include this as a todo item in your review of all the error message text.
