### ISSUE TITLE
`when` syntax and behavior

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#944]
I don't quite understand `when`. Here are three programs:
```
when true: 1 end
```
works as expected (produces `1`).
```
when true:
  1
  2
end
```
syntax error, even though `when` is a strong candidate for implicit `block`ing. Okay, let's add `block`:
```
when true block:
  1
  2
end
```
This appears to return a void value instead of `2`.

1. I suggest making this an implicit block context, unless for consistency we want to have none.
2. Either way, that last statement should return `2`.

**Comment by blerner** [comment]
The desugaring of `when` should always return `nothing`.  It is currently buggy, due to an intended peephole optimization in desugaring that instead allows that first example to return `1` when it shouldn't.  (When statements shouldn't ever return values, because they're implicitly if-expressions whose else-clause must return `nothing`, and therefore the then-clause must also return `nothing` by type-consistency.)

I don't think I'd want anything to be an implicitly block context, though; a single exception is annoying to have to explain and remember.

**Comment by sorawee** [comment]
See also #852: I agree that `when` should be implicit block.
