### ISSUE TITLE
code.pyret.org folder mapping changed

### ISSUE THREAD

**Issue by taps3** [brownplt/pyret-lang#982]
On our school Google Apps domain we use Teacherdashboard to create folders for students linked to teachers for automating copy and distribute of working resources.

Somehow the folder that opens from the 'Open' and 'My Programs' buttons in Pyret is mapped to one of these student folders.

The attached picture is the folder location that opens from 'My Programs'
![pyret_folder_error](https://cloud.githubusercontent.com/assets/4141430/22837728/d96b7ac4-ef8f-11e6-8d08-e1e9f8fe1fde.PNG)

**Comment by jpolitz** [comment]
Thanks for reporting this, and sorry you ran into it.

We recently saw a similar issue, and the cause is simply CPO getting confused by multiple folders named `code.pyret.org`.  We're thinking about several workarounds here, and should have a solution soon.

We can also configure the Picker interface to provide more navigation options to see more files.

Do you know if your account owns those other `code.pyret.org` folders, or if they are owned by students?

The reason this issue is _new_ is that code.pyret.org used to only be set to view files that it had created on behalf of the current user, so the other code.pyret.org folders created for students wouldn't be shown.  But we widened that permission because of unavoidable constraints elsewhere in the APIs Google provides, so we need to revisit this.

**Comment by taps3** [comment]
The student owns the folder. 

If you could open up the picker to allow me to navigate to my root code.pyret.org folder that would be very helpful in the short term.

**Comment by jpolitz** [comment]
I made a slightly different change.  For now, I've changed this so it only opens code.pyret.org folders that you (the current user) _own_.  So this should fix the immediate issue.  My hope is that it will be less confusing to folks who are used to their CPO folder opening directly, and would find it jarring if it were suddenly at the root.

This issue is useful feedback for better navigation/design for the Picker in general, which we're looking at this spring anyway.

Thanks for reporting, as always.
