### ISSUE TITLE
Tuple error message improvement

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#995]
```
{({a; b}): a }(1)
```

results in:

```
The annotation:

{a;b}

was not satisfied by the value
1
```

Anywhere else, this is called tuple annotation.

**Comment by blerner** [comment]
Awkward... This isn't an annotation so much as it is a destructuring binding, but because of how those bindings are desugared, it manifests as an annotation failure.  Moreover, since there is no actual source location for the annotation, the desugaring claims that the annotation exists at the destructuring binding itself.

I don't know what the right engineering solution is here; we might need to augment our annotations with a boolean `implicit` field that says whether they're phantom annotations that our compiler generated, and so the error messages need to be worded differently.

**Comment by blerner** [comment]
This message is now improved to say "Evaluating this tuple binding statement errored..."; closing as fixed
